//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface AppUsage1pLogEvent : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *androidPackageName; // @dynamic androidPackageName;
@property(nonatomic) int appType; // @dynamic appType;
@property(nonatomic) _Bool hasAndroidPackageName; // @dynamic hasAndroidPackageName;
@property(nonatomic) _Bool hasAppType; // @dynamic hasAppType;
@property(nonatomic) _Bool hasVersion; // @dynamic hasVersion;
@property(retain, nonatomic) NSString *version; // @dynamic version;

@end

