//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPImage, LocalizedEntityNames, NSMutableArray, NSString;

@interface Athlete_Team : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIsCaptain; // @dynamic hasIsCaptain;
@property(nonatomic) _Bool hasJerseyNumber; // @dynamic hasJerseyNumber;
@property(nonatomic) _Bool hasStatus; // @dynamic hasStatus;
@property(nonatomic) _Bool hasTeam; // @dynamic hasTeam;
@property(nonatomic) _Bool hasTeamImage; // @dynamic hasTeamImage;
@property(nonatomic) _Bool isCaptain; // @dynamic isCaptain;
@property(copy, nonatomic) NSString *jerseyNumber; // @dynamic jerseyNumber;
@property(retain, nonatomic) NSMutableArray *roleArray; // @dynamic roleArray;
@property(readonly, nonatomic) unsigned long long roleArray_Count; // @dynamic roleArray_Count;
@property(retain, nonatomic) LocalizedEntityNames *status; // @dynamic status;
@property(retain, nonatomic) LocalizedEntityNames *team; // @dynamic team;
@property(retain, nonatomic) GWPImage *teamImage; // @dynamic teamImage;

@end

