//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface AttributionRequirement : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *sourceArray; // @dynamic sourceArray;
@property(readonly, nonatomic) unsigned long long sourceArray_Count; // @dynamic sourceArray_Count;

@end

