//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface BackspaceMetadata : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int deletedTextLength; // @dynamic deletedTextLength;
@property(nonatomic) _Bool hasDeletedTextLength; // @dynamic hasDeletedTextLength;
@property(nonatomic) _Bool hasHasTextSelection; // @dynamic hasHasTextSelection;
@property(nonatomic) _Bool hasRevertDoubleSpaceToPeriodTransformation; // @dynamic hasRevertDoubleSpaceToPeriodTransformation;
@property(nonatomic) _Bool hasRevertSwapPunctuation; // @dynamic hasRevertSwapPunctuation;
@property(nonatomic) _Bool hasTextSelection; // @dynamic hasTextSelection;
@property(nonatomic) _Bool revertDoubleSpaceToPeriodTransformation; // @dynamic revertDoubleSpaceToPeriodTransformation;
@property(nonatomic) _Bool revertSwapPunctuation; // @dynamic revertSwapPunctuation;

@end

