//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface BatchedLogRequest : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLogRequestArray; // @dynamic hasLogRequestArray;
@property(retain, nonatomic) PBMutableArray *logRequestArray; // @dynamic logRequestArray;

@end

