//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface BracketsResult_Advancement : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *fromMatch; // @dynamic fromMatch;
@property(nonatomic) _Bool hasFromMatch; // @dynamic hasFromMatch;
@property(nonatomic) _Bool hasRank; // @dynamic hasRank;
@property(nonatomic) _Bool hasToMatch; // @dynamic hasToMatch;
@property(nonatomic) int rank; // @dynamic rank;
@property(copy, nonatomic) NSString *toMatch; // @dynamic toMatch;

@end

