//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class BracketsResult_Round_Match_AdvanceIndex, NSMutableArray;

@interface BracketsResult_Round_Match : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *eventArray; // @dynamic eventArray;
@property(readonly, nonatomic) unsigned long long eventArray_Count; // @dynamic eventArray_Count;
@property(nonatomic) int gamesPerSeries; // @dynamic gamesPerSeries;
@property(nonatomic) _Bool hasGamesPerSeries; // @dynamic hasGamesPerSeries;
@property(nonatomic) _Bool hasHighlightedEventIndex; // @dynamic hasHighlightedEventIndex;
@property(nonatomic) _Bool hasLoserAdvance; // @dynamic hasLoserAdvance;
@property(nonatomic) _Bool hasWinnerAdvance; // @dynamic hasWinnerAdvance;
@property(nonatomic) int highlightedEventIndex; // @dynamic highlightedEventIndex;
@property(retain, nonatomic) BracketsResult_Round_Match_AdvanceIndex *loserAdvance; // @dynamic loserAdvance;
@property(retain, nonatomic) BracketsResult_Round_Match_AdvanceIndex *winnerAdvance; // @dynamic winnerAdvance;

@end

