//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class BracketsResult_Round_Match_AdvanceIndex, LocalizedEntityNames, Metadata, NSMutableArray, NSString, SubRequestIdentifier;

@interface BracketsResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *advancementArray; // @dynamic advancementArray;
@property(readonly, nonatomic) unsigned long long advancementArray_Count; // @dynamic advancementArray_Count;
@property(nonatomic) _Bool hasIdentifier; // @dynamic hasIdentifier;
@property(nonatomic) _Bool hasMetadata; // @dynamic hasMetadata;
@property(nonatomic) _Bool hasSelectedIndex; // @dynamic hasSelectedIndex;
@property(nonatomic) _Bool hasSelectedMatch; // @dynamic hasSelectedMatch;
@property(nonatomic) _Bool hasSelectedRound; // @dynamic hasSelectedRound;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(retain, nonatomic) SubRequestIdentifier *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSMutableArray *matchArray; // @dynamic matchArray;
@property(readonly, nonatomic) unsigned long long matchArray_Count; // @dynamic matchArray_Count;
@property(retain, nonatomic) Metadata *metadata; // @dynamic metadata;
@property(retain, nonatomic) NSMutableArray *roundArray; // @dynamic roundArray;
@property(readonly, nonatomic) unsigned long long roundArray_Count; // @dynamic roundArray_Count;
@property(retain, nonatomic) BracketsResult_Round_Match_AdvanceIndex *selectedIndex; // @dynamic selectedIndex;
@property(copy, nonatomic) NSString *selectedMatch; // @dynamic selectedMatch;
@property(copy, nonatomic) NSString *selectedRound; // @dynamic selectedRound;
@property(retain, nonatomic) LocalizedEntityNames *title; // @dynamic title;

@end

