//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface BracketsResult_Round_Match_AdvanceIndex : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasMatch; // @dynamic hasMatch;
@property(nonatomic) _Bool hasMatchGroup; // @dynamic hasMatchGroup;
@property(nonatomic) _Bool hasRank; // @dynamic hasRank;
@property(nonatomic) _Bool hasRound; // @dynamic hasRound;
@property(nonatomic) int match; // @dynamic match;
@property(nonatomic) int matchGroup; // @dynamic matchGroup;
@property(nonatomic) int rank; // @dynamic rank;
@property(nonatomic) int round; // @dynamic round;

@end

