//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPTimeSpan, LocalizedEntityNames, NSMutableArray;

@interface BracketsResult_Round : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasTimeSpan; // @dynamic hasTimeSpan;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(retain, nonatomic) NSMutableArray *matchGroupArray; // @dynamic matchGroupArray;
@property(readonly, nonatomic) unsigned long long matchGroupArray_Count; // @dynamic matchGroupArray_Count;
@property(retain, nonatomic) GWPTimeSpan *timeSpan; // @dynamic timeSpan;
@property(retain, nonatomic) LocalizedEntityNames *title; // @dynamic title;

@end

