//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GeoRestrictionInfo, LocalizedEntityNames;

@interface BroadcastChannel : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GeoRestrictionInfo *geoRestriction; // @dynamic geoRestriction;
@property(nonatomic) _Bool hasGeoRestriction; // @dynamic hasGeoRestriction;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(retain, nonatomic) LocalizedEntityNames *name; // @dynamic name;

@end

