//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface BrowserInfo : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *browser; // @dynamic browser;
@property(retain, nonatomic) NSString *browserVersion; // @dynamic browserVersion;
@property(retain, nonatomic) NSString *flashVersion; // @dynamic flashVersion;
@property(nonatomic) _Bool hasBrowser; // @dynamic hasBrowser;
@property(nonatomic) _Bool hasBrowserVersion; // @dynamic hasBrowserVersion;
@property(nonatomic) _Bool hasFlashVersion; // @dynamic hasFlashVersion;
@property(nonatomic) _Bool hasLocale; // @dynamic hasLocale;
@property(retain, nonatomic) NSString *locale; // @dynamic locale;

@end

