//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock;

@interface C2QConv2Query : NSObject
{
    struct unique_ptr<cerebra_sense::messaging::Conv2Query, std::__1::default_delete<cerebra_sense::messaging::Conv2Query>> _conv2query;
    NSLock *_conv2queryLock;
}

+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CollectionConfig *)CStyleCollectionConfig:(id)arg1;
- (struct QueryRule_Metadata *)CStyleMetadata:(id)arg1;
- (struct QueryRuleSet *)CStyleQueryRuleSet:(id)arg1;
- (id)NSStringForCStyleString:(const basic_string_3f66b750 *)arg1;
- (id)queriesFromChat:(id)arg1;
- (void)loadConv2QueryWithLocalSlices:(id)arg1;
- (id)localSliceSourcePaths:(id)arg1 forLat:(double)arg2 lng:(double)arg3;
- (id)sourceURLDatedFolderPath;
- (id)localIndexSourceURL;
- (void)dealloc;
- (id)init;

@end

