//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface C2QScoredQuery : NSObject <NSCopying>
{
    NSString *_query;
    NSString *_rule;
    double _score;
    long long _ruleType;
    long long _triggerType;
}

@property(nonatomic) long long triggerType; // @synthesize triggerType=_triggerType;
@property(readonly, nonatomic) long long ruleType; // @synthesize ruleType=_ruleType;
@property(nonatomic) double score; // @synthesize score=_score;
@property(readonly, nonatomic) NSString *rule; // @synthesize rule=_rule;
@property(readonly, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)capitalizedWord:(id)arg1;
- (id)capitalizedQuery:(id)arg1 ruleType:(long long)arg2;
- (id)initWithQuery:(id)arg1 rule:(id)arg2 ruleType:(long long)arg3 score:(double)arg4;

@end

