//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class StyledText;

@interface CalculatorResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLeftHandSide; // @dynamic hasLeftHandSide;
@property(nonatomic) _Bool hasRightHandSide; // @dynamic hasRightHandSide;
@property(retain, nonatomic) StyledText *leftHandSide; // @dynamic leftHandSide;
@property(retain, nonatomic) StyledText *rightHandSide; // @dynamic rightHandSide;

@end

