//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLink, NSMutableArray;

@interface CareerStatsResult_SeasonStats : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSeason; // @dynamic hasSeason;
@property(nonatomic) _Bool hasTeam; // @dynamic hasTeam;
@property(retain, nonatomic) GWPLink *season; // @dynamic season;
@property(retain, nonatomic) NSMutableArray *statisticArray; // @dynamic statisticArray;
@property(readonly, nonatomic) unsigned long long statisticArray_Count; // @dynamic statisticArray_Count;
@property(retain, nonatomic) GWPLink *team; // @dynamic team;

@end

