//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class AndroidClientInfo, BrowserInfo, DesktopClientInfo, IosClientInfo, JsClientInfo, NSString, PancettaClientInfo, PlayCeClientInfo, VrClientInfo;

@interface ClientInfo : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) AndroidClientInfo *androidClientInfo; // @dynamic androidClientInfo;
@property(retain, nonatomic) BrowserInfo *browserInfo; // @dynamic browserInfo;
@property(nonatomic) int clientType; // @dynamic clientType;
@property(retain, nonatomic) DesktopClientInfo *desktopClientInfo; // @dynamic desktopClientInfo;
@property(nonatomic) _Bool hasAndroidClientInfo; // @dynamic hasAndroidClientInfo;
@property(nonatomic) _Bool hasBrowserInfo; // @dynamic hasBrowserInfo;
@property(nonatomic) _Bool hasClientType; // @dynamic hasClientType;
@property(nonatomic) _Bool hasDesktopClientInfo; // @dynamic hasDesktopClientInfo;
@property(nonatomic) _Bool hasIosClientInfo; // @dynamic hasIosClientInfo;
@property(nonatomic) _Bool hasJsClientInfo; // @dynamic hasJsClientInfo;
@property(nonatomic) _Bool hasPancettaClientInfo; // @dynamic hasPancettaClientInfo;
@property(nonatomic) _Bool hasPlayCeClientInfo; // @dynamic hasPlayCeClientInfo;
@property(nonatomic) _Bool hasRemoteHost; // @dynamic hasRemoteHost;
@property(nonatomic) _Bool hasRemoteHost6; // @dynamic hasRemoteHost6;
@property(nonatomic) _Bool hasVrClientInfo; // @dynamic hasVrClientInfo;
@property(retain, nonatomic) IosClientInfo *iosClientInfo; // @dynamic iosClientInfo;
@property(retain, nonatomic) JsClientInfo *jsClientInfo; // @dynamic jsClientInfo;
@property(retain, nonatomic) PancettaClientInfo *pancettaClientInfo; // @dynamic pancettaClientInfo;
@property(retain, nonatomic) PlayCeClientInfo *playCeClientInfo; // @dynamic playCeClientInfo;
@property(retain, nonatomic) NSString *remoteHost; // @dynamic remoteHost;
@property(retain, nonatomic) NSString *remoteHost6; // @dynamic remoteHost6;
@property(retain, nonatomic) VrClientInfo *vrClientInfo; // @dynamic vrClientInfo;

@end

