//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class ClientSpecificConsumptionActionData, Url;

@interface ConsumptionAction : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Url *URL; // @dynamic URL;
@property(retain, nonatomic) ClientSpecificConsumptionActionData *clientSpecificData; // @dynamic clientSpecificData;
@property(nonatomic) _Bool hasClientSpecificData; // @dynamic hasClientSpecificData;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;

@end

