//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class ConsumptionAction, NSString, StyledText;

@interface ConsumptionOffer : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) ConsumptionAction *consumptionAction; // @dynamic consumptionAction;
@property(nonatomic) _Bool hasConsumptionAction; // @dynamic hasConsumptionAction;
@property(nonatomic) _Bool hasLocalizedFormattedLabel; // @dynamic hasLocalizedFormattedLabel;
@property(retain, nonatomic) StyledText *localizedFormattedLabel; // @dynamic localizedFormattedLabel;
@property(copy, nonatomic) NSString *sourceId; // @dynamic sourceId;

@end

