//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchNextRequest, Image, NSMutableArray, NSString, Url;

@interface ConsumptionSource : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Url *URL; // @dynamic URL;
@property(nonatomic) _Bool hasIconImage; // @dynamic hasIconImage;
@property(nonatomic) _Bool hasNextRequest; // @dynamic hasNextRequest;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(retain, nonatomic) Image *iconImage; // @dynamic iconImage;
@property(copy, nonatomic) NSString *localizedName; // @dynamic localizedName;
@property(retain, nonatomic) DataFetchNextRequest *nextRequest; // @dynamic nextRequest;
@property(retain, nonatomic) NSMutableArray *userSubscriptionTierIdArray; // @dynamic userSubscriptionTierIdArray;
@property(readonly, nonatomic) unsigned long long userSubscriptionTierIdArray_Count; // @dynamic userSubscriptionTierIdArray_Count;

@end

