//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityContent, DataFetchNextRequest, NSString;

@interface DataFetchEntityContentList_Item : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchEntityContent *content; // @dynamic content;
@property(nonatomic) _Bool hasContent; // @dynamic hasContent;
@property(nonatomic) _Bool hasItemSelectedEntityRequest; // @dynamic hasItemSelectedEntityRequest;
@property(retain, nonatomic) DataFetchNextRequest *itemSelectedEntityRequest; // @dynamic itemSelectedEntityRequest;
@property(copy, nonatomic) NSString *localizedDisplayLabel; // @dynamic localizedDisplayLabel;

@end

