//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class CommonAttributionSourceList, DataFetchVerticalsMusicSongLyrics_DisplayHint, DataFetchVerticalsMusicStanzaList;

@interface DataFetchVerticalsMusicSongLyrics : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchVerticalsMusicSongLyrics_DisplayHint *displayHint; // @dynamic displayHint;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) _Bool hasSourceList; // @dynamic hasSourceList;
@property(nonatomic) _Bool hasStanzaList; // @dynamic hasStanzaList;
@property(retain, nonatomic) CommonAttributionSourceList *sourceList; // @dynamic sourceList;
@property(retain, nonatomic) DataFetchVerticalsMusicStanzaList *stanzaList; // @dynamic stanzaList;

@end

