//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityEntityList_AttributeIdList, DataFetchEntityEntityList_Item_DisplayHint, DataFetchEntityId, DataFetchEntityRefinementQuery, DataFetchNextRequest, DataFetchVerticalsVerticalSpecificEntityData, Image, NSMutableDictionary, NSString;

@interface DataFetchEntityEntityList_Item : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *attributeIdToFact; // @dynamic attributeIdToFact;
@property(readonly, nonatomic) unsigned long long attributeIdToFact_Count; // @dynamic attributeIdToFact_Count;
@property(retain, nonatomic) DataFetchEntityEntityList_AttributeIdList *contextualMetadataAttributeIdList; // @dynamic contextualMetadataAttributeIdList;
@property(retain, nonatomic) DataFetchEntityEntityList_Item_DisplayHint *displayHint; // @dynamic displayHint;
@property(retain, nonatomic) DataFetchEntityId *entityId; // @dynamic entityId;
@property(retain, nonatomic) DataFetchNextRequest *entityRequest; // @dynamic entityRequest;
@property(nonatomic) _Bool hasContextualMetadataAttributeIdList; // @dynamic hasContextualMetadataAttributeIdList;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) _Bool hasEntityId; // @dynamic hasEntityId;
@property(nonatomic) _Bool hasEntityRequest; // @dynamic hasEntityRequest;
@property(nonatomic) _Bool hasRefinementQuery; // @dynamic hasRefinementQuery;
@property(nonatomic) _Bool hasThumbnailImage; // @dynamic hasThumbnailImage;
@property(nonatomic) _Bool hasVerticalSpecificData; // @dynamic hasVerticalSpecificData;
@property(copy, nonatomic) NSString *localizedName; // @dynamic localizedName;
@property(retain, nonatomic) DataFetchEntityRefinementQuery *refinementQuery; // @dynamic refinementQuery;
@property(retain, nonatomic) Image *thumbnailImage; // @dynamic thumbnailImage;
@property(retain, nonatomic) DataFetchVerticalsVerticalSpecificEntityData *verticalSpecificData; // @dynamic verticalSpecificData;

@end

