//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchCommonListSizeInfo, DataFetchNextRequest, NSMutableArray;

@interface DataFetchVerticalsMusicVerseList : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasListSizeInfo; // @dynamic hasListSizeInfo;
@property(nonatomic) _Bool hasNextPageRequest; // @dynamic hasNextPageRequest;
@property(retain, nonatomic) DataFetchCommonListSizeInfo *listSizeInfo; // @dynamic listSizeInfo;
@property(retain, nonatomic) DataFetchNextRequest *nextPageRequest; // @dynamic nextPageRequest;
@property(retain, nonatomic) NSMutableArray *verseArray; // @dynamic verseArray;
@property(readonly, nonatomic) unsigned long long verseArray_Count; // @dynamic verseArray_Count;

@end

