//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityFactProperty, DataFetchEntityProperty_DisplayHint, DataFetchEntityProperty_Id, DataFetchEntityRefinementsEntityListProperty;

@interface DataFetchEntityProperty : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int contentOneOfCase; // @dynamic contentOneOfCase;
@property(retain, nonatomic) DataFetchEntityProperty_DisplayHint *displayHint; // @dynamic displayHint;
@property(retain, nonatomic) DataFetchEntityRefinementsEntityListProperty *entityListProperty; // @dynamic entityListProperty;
@property(retain, nonatomic) DataFetchEntityFactProperty *factProperty; // @dynamic factProperty;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(retain, nonatomic) DataFetchEntityProperty_Id *id_p; // @dynamic id_p;

@end

