//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32Value;

@interface DataFetchEntityContentList_DisplayHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSelectedIndex; // @dynamic hasSelectedIndex;
@property(retain, nonatomic) GPBInt32Value *selectedIndex; // @dynamic selectedIndex;

@end

