//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityRefinementsTabularFormat, DataFetchEntityRefinementsThumbnailListFormat;

@interface DataFetchEntityRefinementsEntityListProperty_DisplayHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int formatOneOfCase; // @dynamic formatOneOfCase;
@property(retain, nonatomic) DataFetchEntityRefinementsTabularFormat *tabularFormat; // @dynamic tabularFormat;
@property(retain, nonatomic) DataFetchEntityRefinementsThumbnailListFormat *thumbnailListFormat; // @dynamic thumbnailListFormat;

@end

