//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchFetchRequest;

@interface DataFetchDataRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchFetchRequest *fetchRequest; // @dynamic fetchRequest;
@property(readonly, nonatomic) int typeOneOfCase; // @dynamic typeOneOfCase;

@end

