//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityPropertyGroup_DisplayHint, NSMutableArray;

@interface DataFetchEntityPropertyGroup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchEntityPropertyGroup_DisplayHint *displayHint; // @dynamic displayHint;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(retain, nonatomic) NSMutableArray *propertyArray; // @dynamic propertyArray;
@property(readonly, nonatomic) unsigned long long propertyArray_Count; // @dynamic propertyArray_Count;

@end

