//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityEntityList, DataFetchEntityRefinementsEntityListProperty_DisplayHint, DataFetchEntityRefinementsLabel;

@interface DataFetchEntityRefinementsEntityListProperty : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchEntityRefinementsEntityListProperty_DisplayHint *displayHint; // @dynamic displayHint;
@property(retain, nonatomic) DataFetchEntityEntityList *entityList; // @dynamic entityList;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) _Bool hasEntityList; // @dynamic hasEntityList;
@property(nonatomic) _Bool hasLabel; // @dynamic hasLabel;
@property(retain, nonatomic) DataFetchEntityRefinementsLabel *label; // @dynamic label;

@end

