//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchVerticalsMusicVerseList;

@interface DataFetchVerticalsMusicStanza : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasVerseList; // @dynamic hasVerseList;
@property(retain, nonatomic) DataFetchVerticalsMusicVerseList *verseList; // @dynamic verseList;

@end

