//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchCommonListSizeInfo, DataFetchEntityEntityList_AttributeIdList, DataFetchNextRequest, NSMutableArray, NSString;

@interface DataFetchEntityEntityList : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchEntityEntityList_AttributeIdList *contextualMetadataAttributeIdList; // @dynamic contextualMetadataAttributeIdList;
@property(copy, nonatomic) NSString *focusedAnswerAttributeId; // @dynamic focusedAnswerAttributeId;
@property(nonatomic) _Bool hasContextualMetadataAttributeIdList; // @dynamic hasContextualMetadataAttributeIdList;
@property(nonatomic) _Bool hasListSizeInfo; // @dynamic hasListSizeInfo;
@property(nonatomic) _Bool hasNextPageRequest; // @dynamic hasNextPageRequest;
@property(retain, nonatomic) NSMutableArray *itemArray; // @dynamic itemArray;
@property(readonly, nonatomic) unsigned long long itemArray_Count; // @dynamic itemArray_Count;
@property(retain, nonatomic) DataFetchCommonListSizeInfo *listSizeInfo; // @dynamic listSizeInfo;
@property(retain, nonatomic) DataFetchNextRequest *nextPageRequest; // @dynamic nextPageRequest;

@end

