//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DataFetchEntityRefinementsFieldMask_DisplayHint, NSString;

@interface DataFetchEntityRefinementsFieldMask : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DataFetchEntityRefinementsFieldMask_DisplayHint *displayHint; // @dynamic displayHint;
@property(nonatomic) int field; // @dynamic field;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) int index; // @dynamic index;
@property(copy, nonatomic) NSString *localizedDefaultValue; // @dynamic localizedDefaultValue;

@end

