//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPB2Timestamp;

@interface DawnDuskTimes : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GPB2Timestamp *dawn; // @dynamic dawn;
@property(retain, nonatomic) GPB2Timestamp *dusk; // @dynamic dusk;
@property(nonatomic) _Bool hasDawn; // @dynamic hasDawn;
@property(nonatomic) _Bool hasDusk; // @dynamic hasDusk;

@end

