//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface EntityImagesCollection : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *defaultAvailableSizesArray; // @dynamic defaultAvailableSizesArray;
@property(readonly, nonatomic) unsigned long long defaultAvailableSizesArray_Count; // @dynamic defaultAvailableSizesArray_Count;
@property(copy, nonatomic) NSString *defaultBasePath; // @dynamic defaultBasePath;
@property(retain, nonatomic) NSMutableArray *entityImagesArray; // @dynamic entityImagesArray;
@property(readonly, nonatomic) unsigned long long entityImagesArray_Count; // @dynamic entityImagesArray_Count;
@property(nonatomic) _Bool hasDefaultBasePath; // @dynamic hasDefaultBasePath;

@end

