//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class EntityImagesCollection_Size, NSString;

@interface EntityImagesCollection_EntityImages_Image : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPath; // @dynamic hasPath;
@property(nonatomic) _Bool hasSize; // @dynamic hasSize;
@property(copy, nonatomic) NSString *path; // @dynamic path;
@property(retain, nonatomic) EntityImagesCollection_Size *size; // @dynamic size;

@end

