//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface EntityImagesCollection_EntityImages : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *availableSizesArray; // @dynamic availableSizesArray;
@property(readonly, nonatomic) unsigned long long availableSizesArray_Count; // @dynamic availableSizesArray_Count;
@property(copy, nonatomic) NSString *basePath; // @dynamic basePath;
@property(nonatomic) _Bool hasBasePath; // @dynamic hasBasePath;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(retain, nonatomic) NSMutableArray *imageArray; // @dynamic imageArray;
@property(readonly, nonatomic) unsigned long long imageArray_Count; // @dynamic imageArray_Count;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;

@end

