//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface EntityNicknames : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int entityType; // @dynamic entityType;
@property(copy, nonatomic) NSString *fullName; // @dynamic fullName;
@property(nonatomic) _Bool hasEntityType; // @dynamic hasEntityType;
@property(nonatomic) _Bool hasFullName; // @dynamic hasFullName;
@property(nonatomic) _Bool hasLeagueName; // @dynamic hasLeagueName;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasStatsId; // @dynamic hasStatsId;
@property(nonatomic) _Bool hasStatsType; // @dynamic hasStatsType;
@property(nonatomic) _Bool hasSupportName; // @dynamic hasSupportName;
@property(nonatomic) _Bool hasSupportNameType; // @dynamic hasSupportNameType;
@property(copy, nonatomic) NSString *leagueName; // @dynamic leagueName;
@property(retain, nonatomic) NSMutableArray *locFullNameArray; // @dynamic locFullNameArray;
@property(readonly, nonatomic) unsigned long long locFullNameArray_Count; // @dynamic locFullNameArray_Count;
@property(retain, nonatomic) NSMutableArray *locLeagueNameArray; // @dynamic locLeagueNameArray;
@property(readonly, nonatomic) unsigned long long locLeagueNameArray_Count; // @dynamic locLeagueNameArray_Count;
@property(retain, nonatomic) NSMutableArray *locNameArray; // @dynamic locNameArray;
@property(readonly, nonatomic) unsigned long long locNameArray_Count; // @dynamic locNameArray_Count;
@property(retain, nonatomic) NSMutableArray *locSupportNameArray; // @dynamic locSupportNameArray;
@property(readonly, nonatomic) unsigned long long locSupportNameArray_Count; // @dynamic locSupportNameArray_Count;
@property(retain, nonatomic) NSMutableArray *locSupportNameTypeArray; // @dynamic locSupportNameTypeArray;
@property(readonly, nonatomic) unsigned long long locSupportNameTypeArray_Count; // @dynamic locSupportNameTypeArray_Count;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSMutableArray *nicknameArray; // @dynamic nicknameArray;
@property(readonly, nonatomic) unsigned long long nicknameArray_Count; // @dynamic nicknameArray_Count;
@property(copy, nonatomic) NSString *statsId; // @dynamic statsId;
@property(copy, nonatomic) NSString *statsType; // @dynamic statsType;
@property(copy, nonatomic) NSString *supportName; // @dynamic supportName;
@property(copy, nonatomic) NSString *supportNameType; // @dynamic supportNameType;

@end

