//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface EventsCountFilter : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int count; // @dynamic count;
@property(nonatomic) _Bool fullTimePeriodsOnly; // @dynamic fullTimePeriodsOnly;
@property(nonatomic) _Bool hasCount; // @dynamic hasCount;
@property(nonatomic) _Bool hasFullTimePeriodsOnly; // @dynamic hasFullTimePeriodsOnly;
@property(nonatomic) _Bool hasOnlyAfter; // @dynamic hasOnlyAfter;
@property(nonatomic) _Bool hasOnlyBefore; // @dynamic hasOnlyBefore;
@property(nonatomic) _Bool hasPivotDate; // @dynamic hasPivotDate;
@property(nonatomic) _Bool hasUserOffsetFromUtc; // @dynamic hasUserOffsetFromUtc;
@property(copy, nonatomic) NSString *onlyAfter; // @dynamic onlyAfter;
@property(copy, nonatomic) NSString *onlyBefore; // @dynamic onlyBefore;
@property(copy, nonatomic) NSString *pivotDate; // @dynamic pivotDate;
@property(nonatomic) double userOffsetFromUtc; // @dynamic userOffsetFromUtc;

@end

