//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Event_DeepLink_Thumbnail, GWPLink, GeoRestrictionInfo;

@interface Event_DeepLink : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GeoRestrictionInfo *geoRestriction; // @dynamic geoRestriction;
@property(nonatomic) _Bool hasGeoRestriction; // @dynamic hasGeoRestriction;
@property(nonatomic) _Bool hasLink; // @dynamic hasLink;
@property(nonatomic) _Bool hasThumbnail; // @dynamic hasThumbnail;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(retain, nonatomic) GWPLink *link; // @dynamic link;
@property(retain, nonatomic) Event_DeepLink_Thumbnail *thumbnail; // @dynamic thumbnail;
@property(nonatomic) int type; // @dynamic type;

@end

