//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface ExperimentIdList : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasId_pArray; // @dynamic hasId_pArray;
@property(retain, nonatomic) PBMutableArray *id_pArray; // @dynamic id_pArray;

@end

