//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface FilteredResultsMessage_MandatorilyFilteredMessage : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHelpLink; // @dynamic hasHelpLink;
@property(nonatomic) _Bool hasMsgType; // @dynamic hasMsgType;
@property(nonatomic) _Bool hasNumResults; // @dynamic hasNumResults;
@property(nonatomic) _Bool hasSingleComplaintLink; // @dynamic hasSingleComplaintLink;
@property(copy, nonatomic) NSString *helpLink; // @dynamic helpLink;
@property(nonatomic) int msgType; // @dynamic msgType;
@property(nonatomic) int numResults; // @dynamic numResults;
@property(copy, nonatomic) NSString *singleComplaintLink; // @dynamic singleComplaintLink;

@end

