//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPB2Timestamp, NSString;

@interface FinanceResult_Stock : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *afterHoursLastPrice; // @dynamic afterHoursLastPrice;
@property(nonatomic) _Bool hasAfterHoursLastPrice; // @dynamic hasAfterHoursLastPrice;
@property(nonatomic) _Bool hasHighPrice; // @dynamic hasHighPrice;
@property(nonatomic) _Bool hasLastPrice; // @dynamic hasLastPrice;
@property(nonatomic) _Bool hasLastPriceTimestamp; // @dynamic hasLastPriceTimestamp;
@property(nonatomic) _Bool hasLowPrice; // @dynamic hasLowPrice;
@property(nonatomic) _Bool hasMarketCap; // @dynamic hasMarketCap;
@property(nonatomic) _Bool hasOpenPrice; // @dynamic hasOpenPrice;
@property(nonatomic) _Bool hasPriceChange; // @dynamic hasPriceChange;
@property(nonatomic) _Bool hasPriceChangePercent; // @dynamic hasPriceChangePercent;
@property(copy, nonatomic) NSString *highPrice; // @dynamic highPrice;
@property(copy, nonatomic) NSString *lastPrice; // @dynamic lastPrice;
@property(retain, nonatomic) GPB2Timestamp *lastPriceTimestamp; // @dynamic lastPriceTimestamp;
@property(copy, nonatomic) NSString *lowPrice; // @dynamic lowPrice;
@property(copy, nonatomic) NSString *marketCap; // @dynamic marketCap;
@property(copy, nonatomic) NSString *openPrice; // @dynamic openPrice;
@property(copy, nonatomic) NSString *priceChange; // @dynamic priceChange;
@property(copy, nonatomic) NSString *priceChangePercent; // @dynamic priceChangePercent;

@end

