//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LocalizedEntityNames, NSMutableArray, NSString;

@interface FocusedAnswer : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int category; // @dynamic category;
@property(copy, nonatomic) NSString *compositeStatisticType; // @dynamic compositeStatisticType;
@property(nonatomic) int context; // @dynamic context;
@property(retain, nonatomic) LocalizedEntityNames *entity; // @dynamic entity;
@property(nonatomic) _Bool hasCategory; // @dynamic hasCategory;
@property(nonatomic) _Bool hasCompositeStatisticType; // @dynamic hasCompositeStatisticType;
@property(nonatomic) _Bool hasContext; // @dynamic hasContext;
@property(nonatomic) _Bool hasEntity; // @dynamic hasEntity;
@property(nonatomic) _Bool hasRole; // @dynamic hasRole;
@property(nonatomic) _Bool hasSeason; // @dynamic hasSeason;
@property(copy, nonatomic) NSString *role; // @dynamic role;
@property(copy, nonatomic) NSString *season; // @dynamic season;
@property(retain, nonatomic) NSMutableArray *statisticArray; // @dynamic statisticArray;
@property(readonly, nonatomic) unsigned long long statisticArray_Count; // @dynamic statisticArray_Count;

@end

