//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPB2Timestamp, StyledText, Url;

@interface ForumClusterResult_ForumClusterTopic : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIsQna; // @dynamic hasIsQna;
@property(nonatomic) _Bool hasLink; // @dynamic hasLink;
@property(nonatomic) _Bool hasPostCount; // @dynamic hasPostCount;
@property(nonatomic) _Bool hasTimestamp; // @dynamic hasTimestamp;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool isQna; // @dynamic isQna;
@property(retain, nonatomic) Url *link; // @dynamic link;
@property(nonatomic) int postCount; // @dynamic postCount;
@property(retain, nonatomic) GPB2Timestamp *timestamp; // @dynamic timestamp;
@property(retain, nonatomic) StyledText *title; // @dynamic title;

@end

