//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray;

@interface GD4DecodedCandidate : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool autoCorrection; // @dynamic autoCorrection;
@property(retain, nonatomic) NSString *candidate; // @dynamic candidate;
@property(nonatomic) int candidateType; // @dynamic candidateType;
@property(nonatomic) _Bool hasAutoCorrection; // @dynamic hasAutoCorrection;
@property(nonatomic) _Bool hasCandidate; // @dynamic hasCandidate;
@property(nonatomic) _Bool hasCandidateType; // @dynamic hasCandidateType;
@property(nonatomic) _Bool hasLmMask; // @dynamic hasLmMask;
@property(nonatomic) _Bool hasLmScore; // @dynamic hasLmScore;
@property(nonatomic) _Bool hasLmScoresArray; // @dynamic hasLmScoresArray;
@property(nonatomic) _Bool hasScore; // @dynamic hasScore;
@property(nonatomic) _Bool hasSpatialScore; // @dynamic hasSpatialScore;
@property(nonatomic) int lmMask; // @dynamic lmMask;
@property(nonatomic) float lmScore; // @dynamic lmScore;
@property(retain, nonatomic) PBMutableArray *lmScoresArray; // @dynamic lmScoresArray;
@property(nonatomic) float score; // @dynamic score;
@property(nonatomic) float spatialScore; // @dynamic spatialScore;

@end

