//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class GD4Ngram;

@interface GD4DynamicLmSetNgramRequest : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNgram; // @dynamic hasNgram;
@property(retain, nonatomic) GD4Ngram *ngram; // @dynamic ngram;

@end

