//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface GD4DynamicLmGetNgramResponse : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNgramsArray; // @dynamic hasNgramsArray;
@property(retain, nonatomic) PBMutableArray *ngramsArray; // @dynamic ngramsArray;

@end

