//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class GD4LanguageModelDescriptor, NSString;

@interface GD4DynamicLmIterateRequest : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIterationToken; // @dynamic hasIterationToken;
@property(nonatomic) _Bool hasLanguageModelDescriptor; // @dynamic hasLanguageModelDescriptor;
@property(nonatomic) _Bool hasMinimumTimestamp; // @dynamic hasMinimumTimestamp;
@property(retain, nonatomic) NSString *iterationToken; // @dynamic iterationToken;
@property(retain, nonatomic) GD4LanguageModelDescriptor *languageModelDescriptor; // @dynamic languageModelDescriptor;
@property(nonatomic) long long minimumTimestamp; // @dynamic minimumTimestamp;

@end

