//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface GD4Key : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int codepoint; // @dynamic codepoint;
@property(nonatomic) _Bool hasCodepoint; // @dynamic hasCodepoint;
@property(nonatomic) _Bool hasHeight; // @dynamic hasHeight;
@property(nonatomic) _Bool hasWidth; // @dynamic hasWidth;
@property(nonatomic) _Bool hasX; // @dynamic hasX;
@property(nonatomic) _Bool hasY; // @dynamic hasY;
@property(nonatomic) float height; // @dynamic height;
@property(nonatomic) float width; // @dynamic width;
@property(nonatomic) float x; // @dynamic x;
@property(nonatomic) float y; // @dynamic y;

@end

