//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface GD4LanguageModelDescriptor : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long contentVersion; // @dynamic contentVersion;
@property(retain, nonatomic) NSString *country; // @dynamic country;
@property(nonatomic) int dynamicLmState; // @dynamic dynamicLmState;
@property(nonatomic) int fileLength; // @dynamic fileLength;
@property(nonatomic) int fileOffset; // @dynamic fileOffset;
@property(retain, nonatomic) NSString *filePath; // @dynamic filePath;
@property(nonatomic) _Bool hasContentVersion; // @dynamic hasContentVersion;
@property(nonatomic) _Bool hasCountry; // @dynamic hasCountry;
@property(nonatomic) _Bool hasDynamicLmState; // @dynamic hasDynamicLmState;
@property(nonatomic) _Bool hasFileLength; // @dynamic hasFileLength;
@property(nonatomic) _Bool hasFileOffset; // @dynamic hasFileOffset;
@property(nonatomic) _Bool hasFilePath; // @dynamic hasFilePath;
@property(nonatomic) _Bool hasLanguage; // @dynamic hasLanguage;
@property(nonatomic) _Bool hasStatus; // @dynamic hasStatus;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(retain, nonatomic) NSString *language; // @dynamic language;
@property(nonatomic) int status; // @dynamic status;
@property(nonatomic) int type; // @dynamic type;

@end

