//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface GD4ShortcutMap : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PBMutableArray *blockGestureAutoexpansionArray; // @dynamic blockGestureAutoexpansionArray;
@property(nonatomic) _Bool hasBlockGestureAutoexpansionArray; // @dynamic hasBlockGestureAutoexpansionArray;
@property(nonatomic) _Bool hasShortcutsArray; // @dynamic hasShortcutsArray;
@property(nonatomic) _Bool hasWordsArray; // @dynamic hasWordsArray;
@property(retain, nonatomic) PBMutableArray *shortcutsArray; // @dynamic shortcutsArray;
@property(retain, nonatomic) PBMutableArray *wordsArray; // @dynamic wordsArray;

@end

