//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface GD4SpanInstrumentation : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PBMutableArray *delight3DecoderCallsArray; // @dynamic delight3DecoderCallsArray;
@property(nonatomic) _Bool hasDelight3DecoderCallsArray; // @dynamic hasDelight3DecoderCallsArray;

@end

