//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GD4TextSpanUtils : NSObject
{
}

+ (unsigned long long)stringLengthFromSpansArray:(id)arg1 fromStartIndex:(int)arg2 toEndIndex:(int)arg3;
+ (id)stringFromSpansArray:(id)arg1 fromStartIndex:(int)arg2 toEndIndex:(int)arg3;
+ (id)textSpanWithCFStringRef:(struct __CFString *)arg1 isSeparator:(_Bool)arg2;
+ (id)textSpanWithNSString:(id)arg1 isSeparator:(_Bool)arg2;

@end

