//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface GD4TouchData : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasIsGesture; // @dynamic hasIsGesture;
@property(nonatomic) _Bool hasTouchPointsArray; // @dynamic hasTouchPointsArray;
@property(nonatomic) _Bool isGesture; // @dynamic isGesture;
@property(retain, nonatomic) PBMutableArray *touchPointsArray; // @dynamic touchPointsArray;

@end

