//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GeneralInfoResult_Thumbnail : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImageDocId; // @dynamic hasImageDocId;
@property(nonatomic) _Bool hasOriginalHeight; // @dynamic hasOriginalHeight;
@property(nonatomic) _Bool hasOriginalWidth; // @dynamic hasOriginalWidth;
@property(nonatomic) _Bool hasReferrerURL; // @dynamic hasReferrerURL;
@property(copy, nonatomic) NSString *imageDocId; // @dynamic imageDocId;
@property(nonatomic) int originalHeight; // @dynamic originalHeight;
@property(nonatomic) int originalWidth; // @dynamic originalWidth;
@property(copy, nonatomic) NSString *referrerURL; // @dynamic referrerURL;

@end

