//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPImage, GWPLink, GWPLocalizedString, GWPRefinements, GWPTimeSpan, GeneralInfoResult_Day, GeneralInfoResult_Thumbnail, LocalizedEntityNames, NSMutableArray, NSString, OlympicSport;

@interface GeneralInfoResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GWPLocalizedString *contestType; // @dynamic contestType;
@property(copy, nonatomic) NSString *countryName; // @dynamic countryName;
@property(retain, nonatomic) GeneralInfoResult_Day *day; // @dynamic day;
@property(retain, nonatomic) GWPLink *descriptionSource; // @dynamic descriptionSource;
@property(retain, nonatomic) GWPLocalizedString *description_p; // @dynamic description_p;
@property(copy, nonatomic) NSString *entityId; // @dynamic entityId;
@property(nonatomic) _Bool hasContestType; // @dynamic hasContestType;
@property(nonatomic) _Bool hasCountryName; // @dynamic hasCountryName;
@property(nonatomic) _Bool hasDay; // @dynamic hasDay;
@property(nonatomic) _Bool hasDescriptionSource; // @dynamic hasDescriptionSource;
@property(nonatomic) _Bool hasDescription_p; // @dynamic hasDescription_p;
@property(nonatomic) _Bool hasEntityId; // @dynamic hasEntityId;
@property(nonatomic) _Bool hasHostingCity; // @dynamic hasHostingCity;
@property(nonatomic) _Bool hasHostingCityFactName; // @dynamic hasHostingCityFactName;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasImageSource; // @dynamic hasImageSource;
@property(nonatomic) _Bool hasImageThumbnail; // @dynamic hasImageThumbnail;
@property(nonatomic) _Bool hasLiveBroadcastFactName; // @dynamic hasLiveBroadcastFactName;
@property(nonatomic) _Bool hasLiveWatch; // @dynamic hasLiveWatch;
@property(nonatomic) _Bool hasOfficialSite; // @dynamic hasOfficialSite;
@property(nonatomic) _Bool hasOfficialSiteFactName; // @dynamic hasOfficialSiteFactName;
@property(nonatomic) _Bool hasOlympicInfo; // @dynamic hasOlympicInfo;
@property(nonatomic) _Bool hasPlusPage; // @dynamic hasPlusPage;
@property(nonatomic) _Bool hasRefinements; // @dynamic hasRefinements;
@property(nonatomic) _Bool hasSubtitle; // @dynamic hasSubtitle;
@property(nonatomic) _Bool hasTimeSpan; // @dynamic hasTimeSpan;
@property(nonatomic) _Bool hasTimeSpanFactName; // @dynamic hasTimeSpanFactName;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool hasVenue; // @dynamic hasVenue;
@property(nonatomic) _Bool hasVenueFactName; // @dynamic hasVenueFactName;
@property(retain, nonatomic) LocalizedEntityNames *hostingCity; // @dynamic hostingCity;
@property(copy, nonatomic) NSString *hostingCityFactName; // @dynamic hostingCityFactName;
@property(retain, nonatomic) GWPImage *image; // @dynamic image;
@property(retain, nonatomic) GWPLink *imageSource; // @dynamic imageSource;
@property(retain, nonatomic) GeneralInfoResult_Thumbnail *imageThumbnail; // @dynamic imageThumbnail;
@property(retain, nonatomic) NSMutableArray *liveBroadcastArray; // @dynamic liveBroadcastArray;
@property(readonly, nonatomic) unsigned long long liveBroadcastArray_Count; // @dynamic liveBroadcastArray_Count;
@property(copy, nonatomic) NSString *liveBroadcastFactName; // @dynamic liveBroadcastFactName;
@property(retain, nonatomic) GWPLink *liveWatch; // @dynamic liveWatch;
@property(retain, nonatomic) GWPLink *officialSite; // @dynamic officialSite;
@property(copy, nonatomic) NSString *officialSiteFactName; // @dynamic officialSiteFactName;
@property(retain, nonatomic) OlympicSport *olympicInfo; // @dynamic olympicInfo;
@property(retain, nonatomic) GWPLink *plusPage; // @dynamic plusPage;
@property(retain, nonatomic) GWPRefinements *refinements; // @dynamic refinements;
@property(copy, nonatomic) NSString *subtitle; // @dynamic subtitle;
@property(retain, nonatomic) GWPTimeSpan *timeSpan; // @dynamic timeSpan;
@property(copy, nonatomic) NSString *timeSpanFactName; // @dynamic timeSpanFactName;
@property(retain, nonatomic) GWPLocalizedString *title; // @dynamic title;
@property(retain, nonatomic) NSMutableArray *topCollectionArray; // @dynamic topCollectionArray;
@property(readonly, nonatomic) unsigned long long topCollectionArray_Count; // @dynamic topCollectionArray_Count;
@property(retain, nonatomic) GWPLink *venue; // @dynamic venue;
@property(copy, nonatomic) NSString *venueFactName; // @dynamic venueFactName;
@property(retain, nonatomic) NSMutableArray *venueSetArray; // @dynamic venueSetArray;
@property(readonly, nonatomic) unsigned long long venueSetArray_Count; // @dynamic venueSetArray_Count;

@end

