//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface GeoRestrictionInfo_GeoRestrictionRule : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPolicy; // @dynamic hasPolicy;
@property(retain, nonatomic) NSMutableArray *locationArray; // @dynamic locationArray;
@property(readonly, nonatomic) unsigned long long locationArray_Count; // @dynamic locationArray_Count;
@property(nonatomic) int policy; // @dynamic policy;

@end

