//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@class CADisplayLink, GIPAnimatedImage;

@interface GIPAnimatedGIFImageView : UIImageView
{
    GIPAnimatedImage *_animatedImage;
    CADisplayLink *_displayLink;
    unsigned long long _currentFrameIndex;
    unsigned long long _currentLoopCount;
    double _initialFrameDuration;
    double _currentFrameDuration;
    double _nextUpdateTime;
    double _backgroundTime;
}

- (void).cxx_destruct;
- (void)didDisplayFrame:(id)arg1;
- (void)purgeCachedImages;
- (void)showNextFrame:(id)arg1;
- (void)showFirstFrame;
- (void)willEnterForeground;
- (void)didEnterBackground;
- (void)updatePausedState:(_Bool)arg1;
- (void)stopObservingAppState;
- (void)startObservingAppState;
- (void)didMoveToWindow;
- (_Bool)isAnimating;
- (void)stopAnimatingAndShowFirstFrame:(_Bool)arg1;
- (void)stopAnimating;
- (void)startAnimating;
- (id)image;
- (void)setImage:(id)arg1;
- (_Bool)isAnimatedImage;
- (void)dealloc;

@end

