//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GIPDevice.h"

@class NSString;

@interface GIPDevice (Legacy)
@property(readonly, nonatomic) _Bool isRecognizedModel;
@property(readonly, nonatomic) NSString *generation;
@property(readonly, nonatomic) NSString *deviceCategory;
- (void)determineGeneration;
@end

