//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIDevice;

@interface GIPDevice : NSObject
{
    NSString *_generation;
    NSString *_deviceCategory;
    _Bool _isRecognizedModel;
    UIDevice *_currentDevice;
    unsigned long long _iPhoneOSVersion;
    struct CGSize _keyboardSize;
    NSString *_machineName;
}

+ (void)ensureInitialized;
+ (id)currentDevice;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)stopListeningToKeyboardEvents;
- (void)startListeningToKeyboardEvents;
@property(readonly, nonatomic) struct CGSize keyboardSize;
@property(readonly, nonatomic) _Bool proximityState;
@property(nonatomic, setter=setProximitySensingEnabled:) _Bool isProximitySensingEnabled;
@property(readonly, nonatomic) double screenScaleFactor;
@property(readonly, nonatomic) struct CGSize screenDimensions;
@property(readonly, nonatomic) unsigned long long iPhoneOSVersion;
@property(readonly, nonatomic) NSString *modelVersion;
- (id)init;

@end

