//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GIPViewableImage.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"

@class GTMSessionFetcher, NSData, NSString, NSURL, NSURLRequest, UIImage;

@interface GIPNetworkImage : NSObject <GIPViewableImage, NSSecureCoding, NSCopying>
{
    NSURL *contextURL_;
    long long cookieStorageMethod_;
    id <GTMSessionFetcherServiceProtocol> fetcherService_;
    UIImage *fullImage_;
    NSData *rawImageData_;
    GTMSessionFetcher *fullImageFetcher_;
    _Bool fullImageFetchFailed_;
    NSURL *fullImageURL_;
    NSURLRequest *fullImageURLRequest_;
    long long index_;
    _Bool loadImageImmediately_;
    struct CGSize maxFullimageSize_;
    struct CGSize maxThumbnailSize_;
    NSString *subtitle_;
    UIImage *thumbnail_;
    GTMSessionFetcher *thumbnailFetcher_;
    _Bool thumbnailFetchFailed_;
    NSURL *thumbnailURL_;
    NSURLRequest *thumbnailURLRequest_;
    NSString *title_;
    _Bool allowResizeAsynchronously_;
    _Bool allowTransparentResize_;
    _Bool allowFetchRetriesForFailures_;
    id <GTMFetcherAuthorizationProtocol> authorizer_;
}

+ (id)fallbackHTTPFetcherService;
+ (_Bool)supportsSecureCoding;
+ (id)requestWithSecureURLForRequest:(id)arg1;
+ (_Bool)forcesSecureImageLoads;
+ (void)setForcesSecureImageLoads:(_Bool)arg1;
+ (void)setDefaultHTTPFetcherService:(id)arg1;
+ (id)defaultHTTPFetcherService;
+ (id)networkImageErrorWithCode:(long long)arg1;
+ (id)imageCreationErrorWithData:(id)arg1;
+ (void)setDefaultCacheProvider:(id)arg1;
+ (id)defaultCacheProvider;
+ (id)cacheKeyForImageURL:(id)arg1 maxSize:(struct CGSize)arg2;
+ (_Bool)cacheContainsImageWithURL:(id)arg1 maxSize:(struct CGSize)arg2;
@property(nonatomic) _Bool allowTransparentResize; // @synthesize allowTransparentResize=allowTransparentResize_;
@property(nonatomic) _Bool allowResizeAsynchronously; // @synthesize allowResizeAsynchronously=allowResizeAsynchronously_;
@property(nonatomic) _Bool allowFetchRetriesForFailures; // @synthesize allowFetchRetriesForFailures=allowFetchRetriesForFailures_;
@property(readonly, nonatomic) NSString *title; // @synthesize title=title_;
@property(readonly, nonatomic) NSURLRequest *thumbnailURLRequest; // @synthesize thumbnailURLRequest=thumbnailURLRequest_;
@property(readonly, nonatomic) NSURL *thumbnailURL; // @synthesize thumbnailURL=thumbnailURL_;
@property(retain, nonatomic) UIImage *thumbnail; // @synthesize thumbnail=thumbnail_;
@property(readonly, nonatomic) NSString *subtitle; // @synthesize subtitle=subtitle_;
@property(nonatomic) struct CGSize maxThumbnailSize; // @synthesize maxThumbnailSize=maxThumbnailSize_;
@property(nonatomic) struct CGSize maxFullimageSize; // @synthesize maxFullimageSize=maxFullimageSize_;
@property(nonatomic) _Bool loadImageImmediately; // @synthesize loadImageImmediately=loadImageImmediately_;
@property(nonatomic) long long index; // @synthesize index=index_;
@property(readonly, nonatomic) NSURLRequest *fullImageURLRequest; // @synthesize fullImageURLRequest=fullImageURLRequest_;
@property(readonly, nonatomic) NSURL *fullImageURL; // @synthesize fullImageURL=fullImageURL_;
@property(retain, nonatomic) UIImage *fullImage; // @synthesize fullImage=fullImage_;
@property(retain, nonatomic) NSData *rawImageData; // @synthesize rawImageData=rawImageData_;
@property(retain, nonatomic) id <GTMSessionFetcherServiceProtocol> fetcherService; // @synthesize fetcherService=fetcherService_;
@property(nonatomic) long long cookieStorageMethod; // @synthesize cookieStorageMethod=cookieStorageMethod_;
@property(readonly, nonatomic) NSURL *contextURL; // @synthesize contextURL=contextURL_;
@property(retain, nonatomic) id <GTMFetcherAuthorizationProtocol> authorizer; // @synthesize authorizer=authorizer_;
- (id)resampleImage:(id)arg1 size:(struct CGSize)arg2 scale:(double)arg3;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setThumbnailImageFromCacheForURL:(id)arg1 maxSize:(struct CGSize)arg2;
- (void)setFullImageAndMaybeRawDataFromCacheForURL:(id)arg1 maxSize:(struct CGSize)arg2;
- (id)resizeAndCacheImage:(id)arg1 rawImageData:(id)arg2 url:(id)arg3 maxSize:(struct CGSize)arg4;
- (void)cacheImage:(id)arg1 rawImageData:(id)arg2 url:(id)arg3 maxSize:(struct CGSize)arg4;
- (id)resampleImage:(id)arg1 size:(struct CGSize)arg2;
- (id)imageCache;
- (void)sendNotification:(id)arg1 error:(id)arg2;
- (void)fullImageFetchDidFinish:(id)arg1 data:(id)arg2 error:(id)arg3;
- (_Bool)fetchFullImage;
- (void)thumbnailFetchDidFinish:(id)arg1 data:(id)arg2 error:(id)arg3;
- (double)screenScaleFactor;
- (_Bool)fetchThumbnail;
- (id)fetcherWithURLRequest:(id)arg1;
- (void)dealloc;
- (id)initWithFullImageURLRequest:(id)arg1 thumbnailURLRequest:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4 title:(id)arg5 subtitle:(id)arg6;
- (id)initWithFullImageURL:(id)arg1 thumbnailURL:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4 title:(id)arg5 subtitle:(id)arg6;
- (id)initWithFullImageURLRequest:(id)arg1 thumbnailURLRequest:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4 title:(id)arg5;
- (id)initWithFullImageURL:(id)arg1 thumbnailURL:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4 title:(id)arg5;
- (id)initWithFullImageURLRequest:(id)arg1 thumbnailURLRequest:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4;
- (id)initWithFullImageURL:(id)arg1 thumbnailURL:(id)arg2 contextURL:(id)arg3 fetcherService:(id)arg4 index:(unsigned long long)arg5;
- (id)initWithFullImageURL:(id)arg1 thumbnailURL:(id)arg2 contextURL:(id)arg3 index:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

