//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBAutoSuggestionDataSource, NSArray, NSError, NSString;

@protocol GKBAutoSuggestionDataSourceDelegate
- (void)autoSuggestionDataSource:(GKBAutoSuggestionDataSource *)arg1 didFetchSuggestions:(NSArray *)arg2 forSnippet:(NSString *)arg3 error:(NSError *)arg4;
@end

