//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBArtLoggerUtilities : NSObject
{
}

+ (id)imageHost:(id)arg1;
+ (id)GIFCategory:(id)arg1 isSearching:(_Bool)arg2;
+ (id)stickerCategory:(id)arg1 isSearching:(_Bool)arg2;
+ (id)emojiCategory:(long long)arg1 isSearching:(_Bool)arg2;
+ (int)artTab:(long long)arg1;

@end

