//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBAnimatedGIFImageView.h"

@class GIPCachedNetworkImage, GKBImageAsset, GTMSessionFetcherService, NSArray, NSData, QTMActivityIndicator;

@interface GKBAsyncImageView : GKBAnimatedGIFImageView
{
    GTMSessionFetcherService *_fetcherService;
    GIPCachedNetworkImage *_networkImage;
    QTMActivityIndicator *_activityIndicator;
    long long _imageType;
    NSArray *_layoutConstraints;
    GKBImageAsset *_imageAsset;
    _Bool _saveImageToDisk;
    _Bool _hideActivityIndicator;
    id <GKBAsyncImageViewDelegate> _delegate;
}

@property(nonatomic) _Bool hideActivityIndicator; // @synthesize hideActivityIndicator=_hideActivityIndicator;
@property(nonatomic) __weak id <GKBAsyncImageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleNetworkImage:(id)arg1;
- (void)processAndSetImage;
- (id)createConstraints;
- (void)stopActivityIndicator;
- (void)showActivityIndicator;
- (void)fullImageFetchFailed:(id)arg1;
- (void)fullImageFetchSucceeded:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) NSData *imageData;
- (void)unload;
- (void)setImage:(id)arg1 animated:(_Bool)arg2;
- (_Bool)loadImageFromData:(id)arg1 imageType:(long long)arg2;
- (void)loadImageAsyncFromURL:(id)arg1 imageType:(long long)arg2;
- (void)loadImageAsyncFromURL:(id)arg1;
- (_Bool)loadImageFromAsset:(id)arg1 imageType:(long long)arg2 synchronousOnlyFromCache:(_Bool)arg3;
- (_Bool)loadImageFromCachedAsset:(id)arg1 imageType:(long long)arg2;
- (_Bool)loadImageFromAsset:(id)arg1 imageType:(long long)arg2;
- (_Bool)loadImageFromAsset:(id)arg1;
- (id)initWithImage:(id)arg1;
- (id)init;

@end

