//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBAutoCapHelper : NSObject
{
}

+ (_Bool)isCursorAtStartOfSentence:(id)arg1;
+ (_Bool)isCursorAtStartOfWord:(id)arg1;
+ (_Bool)shouldCapitalizeAtCurrentPosition:(long long)arg1 textBeforeInsertionPoint:(id)arg2;

@end

