//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBAutoSuggestionDataSourceDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GKBAutoSuggestion, GKBAutoSuggestionDataSource, GKBContactsDataSource, GKBSearchUserDefaults, NSArray, NSMutableArray, NSString, UITableView;

@interface GKBAutoSuggestionsView : UIView <GKBAutoSuggestionDataSourceDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_tableView;
    GKBAutoSuggestionDataSource *_dataSource;
    GKBSearchUserDefaults *_userDefaults;
    unsigned long long _maxSuggestionCount;
    NSArray *_autoCompleteSuggestions;
    NSArray *_contactsSuggestions;
    NSMutableArray *_suggestions;
    NSString *_lastSnippet;
    NSArray *_layoutConstraints;
    unsigned long long _lastCount;
    GKBAutoSuggestion *_contextualSuggestion;
    _Bool _hasSelectedSuggestion;
    id <GKBAutoSuggestionsViewDelegate> _delegate;
    long long _autoSuggestionDataSet;
    GKBContactsDataSource *_contactsDataSource;
}

+ (double)suggestionItemHeight;
@property(nonatomic) _Bool hasSelectedSuggestion; // @synthesize hasSelectedSuggestion=_hasSelectedSuggestion;
@property(retain, nonatomic) GKBContactsDataSource *contactsDataSource; // @synthesize contactsDataSource=_contactsDataSource;
@property(nonatomic) long long autoSuggestionDataSet; // @synthesize autoSuggestionDataSet=_autoSuggestionDataSet;
@property(nonatomic) __weak id <GKBAutoSuggestionsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleGKBUIInputViewControllerDidReceiveRotationNotification:(id)arg1;
- (void)showTooltipForContextualSuggestionIfNecessary;
- (id)validateMirrorInputSuggestion:(id)arg1;
- (void)clearFetchedSuggestions;
- (long long)reverseIndex:(id)arg1;
- (id)fillerQueries;
- (id)fillerSuggestions;
- (id)recentsSuggestions;
- (void)fillWithSuggestions:(id)arg1 alreadyUsed:(id)arg2;
- (void)reloadTable;
- (id)stringBySanitizingAppInputText:(id)arg1;
- (long long)maxSuggestionCountForOrientation:(long long)arg1;
- (void)autoSuggestionDataSource:(id)arg1 didFetchSuggestions:(id)arg2 forSnippet:(id)arg3 error:(id)arg4;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)initiateSuggestionsFetchForSnippet:(id)arg1;
- (void)createAndActivateConstraintsLimitedToRowCount:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithAutoSuggestionDataSet:(long long)arg1;
- (id)initWithAutoSuggestionDataSet:(long long)arg1 contextualSuggestion:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

