//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GKBAutoSuggestion : NSObject
{
    NSString *_strippedSuggestion;
    long long _autoSuggestionType;
    NSString *_suggestion;
}

@property(retain, nonatomic) NSString *suggestion; // @synthesize suggestion=_suggestion;
@property(readonly, nonatomic) long long autoSuggestionType; // @synthesize autoSuggestionType=_autoSuggestionType;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) NSString *strippedSuggestion;
- (id)initWithSuggestion:(id)arg1 autoSuggestionType:(long long)arg2;

@end

