//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBIME.h"
#import "GKBIMEDelegate.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>;

@interface GKBAsyncIME : NSObject <GKBIME, GKBIMEDelegate>
{
    _Bool _hasPendingCursorMoved;
    id <GKBUserMetrics> _userMetrics;
    id <GKBIME> _IME;
    id <GKBIMEDelegate> _IMEDelegate;
    long long _candidateVersionInBackground;
    long long _candidateVersionInForeground;
    long long _requestCandidateVersion;
    NSObject<OS_dispatch_queue> *_backgroundQueue;
    NSMutableDictionary *_pendingDiscardableEvents;
    NSObject<OS_dispatch_semaphore> *_discardableEventSemaphore;
}

@property _Bool hasPendingCursorMoved; // @synthesize hasPendingCursorMoved=_hasPendingCursorMoved;
@property(retain) NSObject<OS_dispatch_semaphore> *discardableEventSemaphore; // @synthesize discardableEventSemaphore=_discardableEventSemaphore;
@property(retain) NSMutableDictionary *pendingDiscardableEvents; // @synthesize pendingDiscardableEvents=_pendingDiscardableEvents;
@property(retain) NSObject<OS_dispatch_queue> *backgroundQueue; // @synthesize backgroundQueue=_backgroundQueue;
@property long long requestCandidateVersion; // @synthesize requestCandidateVersion=_requestCandidateVersion;
@property long long candidateVersionInForeground; // @synthesize candidateVersionInForeground=_candidateVersionInForeground;
@property long long candidateVersionInBackground; // @synthesize candidateVersionInBackground=_candidateVersionInBackground;
@property __weak id <GKBIMEDelegate> IMEDelegate; // @synthesize IMEDelegate=_IMEDelegate;
@property(retain) id <GKBIME> IME; // @synthesize IME=_IME;
@property(readonly, nonatomic) id <GKBUserMetrics> userMetrics; // @synthesize userMetrics=_userMetrics;
- (void).cxx_destruct;
- (void)clearDiscardableEventWithKeyCode:(int)arg1;
- (void)handleDiscardableEvent:(id)arg1;
- (void)handleNormalEvent:(id)arg1;
- (_Bool)isDiscardableEvent:(int)arg1;
- (id)createIME:(id)arg1;
- (id)getUserMetrics;
- (void)clearUserHistory;
- (void)cursorHasMoved;
- (void)keyboardStateChangedFrom:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)keyboardWithTypeDidActivated:(int)arg1;
- (void)requestCandidates:(int)arg1;
- (void)selectReadingTextCandidate:(id)arg1 forCommit:(_Bool)arg2;
- (void)selectTextCandidate:(id)arg1 forCommit:(_Bool)arg2;
- (void)handleEvent:(id)arg1;
- (void)abortComposing;
- (void)finishComposing;
- (void)deactivate;
- (void)activateWithTraits:(id)arg1;
- (void)close;
- (void)configureWithInputBundleDef:(id)arg1 delegate:(id)arg2;
- (void)configureWithLexicon:(id)arg1;
- (void)IME:(id)arg1 updateTextWithBeforeComposingRangeLength:(unsigned long long)arg2 preComposingRangeText:(id)arg3 composingText:(id)arg4;
- (id)textAfterCursor:(long long)arg1;
- (id)textBeforeCursor:(long long)arg1;
- (void)IME:(id)arg1 unconsumedEvent:(id)arg2;
- (void)IME:(id)arg1 setKeyboardState:(unsigned long long)arg2 on:(_Bool)arg3;
- (void)IME:(id)arg1 setComposingRangeWithLength:(unsigned long long)arg2;
- (void)IME:(id)arg1 commitText:(id)arg2;
- (void)IME:(id)arg1 appendTextCandidates:(id)arg2 selection:(id)arg3 hasMore:(_Bool)arg4;
- (void)IME:(id)arg1 textCandidateUpdated:(_Bool)arg2;
- (void)IME:(id)arg1 setComposingText:(id)arg2;
- (id)init;

@end

