//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray;

@interface GKBActionDef : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int action; // @dynamic action;
@property(nonatomic) _Bool actionOnDown; // @dynamic actionOnDown;
@property(nonatomic) _Bool alwaysShowPopup; // @dynamic alwaysShowPopup;
@property(nonatomic) float delay; // @dynamic delay;
@property(nonatomic) _Bool hasAction; // @dynamic hasAction;
@property(nonatomic) _Bool hasActionOnDown; // @dynamic hasActionOnDown;
@property(nonatomic) _Bool hasAlwaysShowPopup; // @dynamic hasAlwaysShowPopup;
@property(nonatomic) _Bool hasDelay; // @dynamic hasDelay;
@property(nonatomic) _Bool hasKeyDatasArray; // @dynamic hasKeyDatasArray;
@property(nonatomic) _Bool hasPopupIconsArray; // @dynamic hasPopupIconsArray;
@property(nonatomic) _Bool hasPopupLabelsArray; // @dynamic hasPopupLabelsArray;
@property(nonatomic) _Bool hasPopupLayout; // @dynamic hasPopupLayout;
@property(nonatomic) _Bool hasRepeatable; // @dynamic hasRepeatable;
@property(nonatomic) _Bool hasSeperator; // @dynamic hasSeperator;
@property(retain, nonatomic) PBMutableArray *keyDatasArray; // @dynamic keyDatasArray;
@property(retain, nonatomic) PBMutableArray *popupIconsArray; // @dynamic popupIconsArray;
@property(retain, nonatomic) PBMutableArray *popupLabelsArray; // @dynamic popupLabelsArray;
@property(retain, nonatomic) NSString *popupLayout; // @dynamic popupLayout;
@property(nonatomic) _Bool repeatable; // @dynamic repeatable;
@property(retain, nonatomic) NSString *seperator; // @dynamic seperator;

@end

