//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class GKBArtExtensionPickerButton, NSArray, NSString, UICollectionView;

@interface GKBArtExtensionPickerView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    _Bool _hasRecentlyUsed;
    id <GKBArtExtensionPickerViewDelegate> _delegate;
    NSArray *_buttons;
    UICollectionView *_collectionView;
    GKBArtExtensionPickerButton *_currentButton;
}

@property(nonatomic) _Bool hasRecentlyUsed; // @synthesize hasRecentlyUsed=_hasRecentlyUsed;
@property(retain, nonatomic) GKBArtExtensionPickerButton *currentButton; // @synthesize currentButton=_currentButton;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) __weak id <GKBArtExtensionPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)buttonClicked:(id)arg1;
- (id)createConstraints;
- (void)deselectAll;
- (void)selectButtonAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

