//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError, NSString, NSURL;

@protocol GKBBackgroundDownloaderDelegate
- (void)didFailedDownloadWithItemID:(NSString *)arg1 error:(NSError *)arg2;
- (void)didFinishDownloadWithItemID:(NSString *)arg1 toFileURL:(NSURL *)arg2;
@end

