//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface GKBCardView : UIView
{
    id <GKBCardViewDelegate> _delegate;
}

+ (Class)cardViewClassForType:(long long)arg1;
+ (id)cardViewForType:(long long)arg1;
@property(nonatomic) __weak id <GKBCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)widthWillChange:(double)arg1;
- (void)unload;
- (void)loadWithModel:(id)arg1 toShare:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

