//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class GKBContact, NSData, NSString;

@interface GKBContactCardModel : GKBCardModel
{
    GKBContact *_contact;
    NSString *_name;
}

@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *emailAddress;
@property(readonly, nonatomic) NSString *phoneNumber;
@property(readonly, nonatomic) NSData *imageData;
@property(readonly, nonatomic) NSString *location;
- (id)shareText;
- (id)accessoryImageData;
- (id)footerActionModels;
- (id)initWithContact:(id)arg1;

@end

