//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBClearcutWriter : NSObject
{
    int _fileDescriptor;
    unsigned long long _numberOfBytes;
}

@property(nonatomic) unsigned long long numberOfBytes; // @synthesize numberOfBytes=_numberOfBytes;
@property(nonatomic) int fileDescriptor; // @synthesize fileDescriptor=_fileDescriptor;
- (_Bool)writeLogEvent:(id)arg1;
- (void)close;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

