//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBCardUtilities : NSObject
{
}

+ (_Bool)whitelistedForFavicon:(id)arg1;
+ (id)dateFromDateString:(id)arg1;
+ (id)dateFromISOString:(id)arg1;
+ (id)faviconURLForURL:(id)arg1;
+ (id)appleTouchIconURLForURL:(id)arg1;

@end

