//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GKBCardActionModel : NSObject
{
    long long _type;
    NSString *_title;
    NSString *_iconName;
    id <GKBCardActionDataSource> _dataSource;
    id <GKBCardActionImageSource> _imageSource;
    id <GKBCardActionDelegate> _delegate;
}

+ (id)playModel;
+ (id)mapsModel;
+ (id)callModel;
+ (id)openModel;
+ (id)shareModel;
@property(nonatomic) __weak id <GKBCardActionDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <GKBCardActionImageSource> imageSource; // @synthesize imageSource=_imageSource;
@property(nonatomic) __weak id <GKBCardActionDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(readonly, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)customOpen;
- (void)play;
- (void)openMap;
- (void)call;
- (void)open;
- (void)share;
- (void)performAction:(id)arg1 event:(id)arg2;
- (id)description;
- (id)initWithTitle:(id)arg1 iconName:(id)arg2 type:(long long)arg3;

@end

