//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer;

@interface GKBCircleView : UIView
{
    NSTimer *_animationTimer;
}

- (void).cxx_destruct;
- (void)timerFired:(id)arg1;
- (void)handleGKBExtensionManagerWillActivate:(id)arg1;
- (void)handleGKBQueryPredictionWillShowSuggestedQuery:(id)arg1;
- (void)stopPulsing;
- (void)startPulsing;
- (void)layoutSublayersOfLayer:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

