//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTMSessionFetcher, GTMSessionFetcherService, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSURL, Reachability;

@interface GKBClearcutLogger : NSObject
{
    GTMSessionFetcherService *_gtmService;
    _Bool _enabled;
    _Bool _sendScheduled;
    NSString *_applicationBuild;
    unsigned long long _maxRequestNumberOfBytes;
    NSString *_installIdentifier;
    NSURL *_serverURL;
    CDUnknownBlockType _accountToAuthorizerBlock;
    id <GTMFetcherAuthorizationProtocol> _authorization;
    NSString *_logDirectory;
    NSMutableDictionary *_accounts;
    GTMSessionFetcher *_fetcher;
    NSMutableArray *_pendingRequests;
    NSObject<OS_dispatch_queue> *_queue;
    unsigned long long _backgroundTaskId;
    Reachability *_reachability;
}

+ (id)newLogEvent;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
@property(nonatomic) unsigned long long backgroundTaskId; // @synthesize backgroundTaskId=_backgroundTaskId;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(readonly, copy, nonatomic) NSMutableArray *pendingRequests; // @synthesize pendingRequests=_pendingRequests;
@property(retain, nonatomic) GTMSessionFetcher *fetcher; // @synthesize fetcher=_fetcher;
@property(nonatomic) _Bool sendScheduled; // @synthesize sendScheduled=_sendScheduled;
@property(readonly, copy, nonatomic) NSMutableDictionary *accounts; // @synthesize accounts=_accounts;
@property(copy, nonatomic) NSString *logDirectory; // @synthesize logDirectory=_logDirectory;
@property(retain, nonatomic) id <GTMFetcherAuthorizationProtocol> authorization; // @synthesize authorization=_authorization;
@property(copy, nonatomic) CDUnknownBlockType accountToAuthorizerBlock; // @synthesize accountToAuthorizerBlock=_accountToAuthorizerBlock;
@property(copy, nonatomic) NSURL *serverURL; // @synthesize serverURL=_serverURL;
@property(copy, nonatomic) NSString *installIdentifier; // @synthesize installIdentifier=_installIdentifier;
@property(nonatomic) unsigned long long maxRequestNumberOfBytes; // @synthesize maxRequestNumberOfBytes=_maxRequestNumberOfBytes;
@property(copy, nonatomic) NSString *applicationBuild; // @synthesize applicationBuild=_applicationBuild;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)endBackgroundTask;
- (void)sendLogsForAccount:(id)arg1;
- (void)sendNextPendingRequest;
- (id)fetcherWithLogRequest:(id)arg1 authorizer:(id)arg2;
- (id)nextPendingRequest;
- (void)updatePendingRequestsForAccount:(id)arg1;
- (void)flushWritersForAccount:(id)arg1;
- (id)logRequestFromPath:(id)arg1 logSource:(int)arg2;
- (id)accountDataForAccount:(id)arg1;
- (void)dealloc;
- (id)init;

@end

