//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBCandidate, NSArray;

@protocol GKBCandidateViewHolder
@property(readonly, nonatomic) int capacity;
- (void)hide;
- (void)show;
- (void)clearCandidates;
- (int)appendCandidates:(NSArray *)arg1 selection:(GKBCandidate *)arg2;
@end

