//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBDeviceUtilities : NSObject
{
}

+ (_Bool)hasInternetConnection;
+ (double)screenWidthForDevice:(long long)arg1;
+ (long long)deviceTypeForDimension:(double)arg1;
+ (long long)displayDeviceTypeFromResponder:(id)arg1;
+ (id)currentDeviceTypeAndOrientationString;
+ (id)currentDeviceOrientationString;
+ (id)currentDeviceTypeString;
+ (long long)deviceOrientationForSize:(struct CGSize)arg1;
+ (long long)currentDeviceOrientation;
+ (long long)currentDeviceType;

@end

