//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink;

@interface GKBDisplayLink : NSObject
{
    long long _frameCount;
    _Bool _isAnimating;
    CDUnknownBlockType _progressBlock;
    CDUnknownBlockType _completionBlock;
    CADisplayLink *_caDisplayLink;
    double _duration;
    double _startTime;
}

+ (id)runDisplayLinkWithDuration:(double)arg1 progressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain, nonatomic) CADisplayLink *caDisplayLink; // @synthesize caDisplayLink=_caDisplayLink;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
- (void).cxx_destruct;
- (void)runBlock:(id)arg1;
- (id)initPrivateWithDuration:(double)arg1 progressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)description;

@end

