//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTMSessionFetcherService, NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface GKBDownloadService : NSObject
{
    GTMSessionFetcherService *_sessionFetcherService;
    NSMutableDictionary *_fileNameToFetchers;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *fileNameToFetchers; // @synthesize fileNameToFetchers=_fileNameToFetchers;
@property(retain, nonatomic) GTMSessionFetcherService *sessionFetcherService; // @synthesize sessionFetcherService=_sessionFetcherService;
- (void).cxx_destruct;
- (void)stopFetchingFile:(id)arg1;
- (void)downloadContentFromURLPostRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)downloadContentFromURL:(id)arg1 toDirectory:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithSessionFetcherService:(id)arg1;
- (id)initWithSessionFetcherService:(id)arg1 inDispatchQueue:(id)arg2;

@end

