//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class GKBEmojiObject, UIImageView;

@interface GKBEmojiCollectionViewCell : UICollectionViewCell
{
    UIImageView *_emojiImageView;
    GKBEmojiObject *_emojiObject;
}

@property(retain, nonatomic) GKBEmojiObject *emojiObject; // @synthesize emojiObject=_emojiObject;
- (void).cxx_destruct;

@end

