//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBKeyboardImpl.h"

@class GKBSoftKeyboardView, UIView;

@interface GKBEnKeyboard : GKBKeyboardImpl
{
    id <GKBCandidateViewHolder> _candidatesView;
    GKBSoftKeyboardView *_headerView;
    UIView *_updatePrompt;
}

- (void).cxx_destruct;
- (void)hidePrompt;
- (void)showPromptIfAvailable;
- (_Bool)shouldShowFullAccessPrompt;
- (_Bool)shouldShowUpdatePrompt;
- (id)candidatesView;
- (void)textCandidateUpdated:(_Bool)arg1;
- (void)appendTextCandidate:(id)arg1 selection:(id)arg2 hasMore:(_Bool)arg3;
- (void)keyboardViewHelper:(id)arg1 didDiscardView:(id)arg2;
- (void)keyboardViewHelper:(id)arg1 didCreateView:(id)arg2;
- (_Bool)consumeEvent:(id)arg1;
- (void)deactivate;
- (void)activateWithTraits:(id)arg1;

@end

