//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface GKBErrorMessageLabel : UILabel
{
    double _topPadding;
    double _height;
}

- (id)messageForMessageType:(long long)arg1;
- (void)didMoveToSuperview;
- (id)initWithMessageType:(long long)arg1 topPadding:(double)arg2 height:(double)arg3;

@end

