//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBArtExtensionPickerButton.h"

@class UIView;

@interface GKBEmojiPickerButton : GKBArtExtensionPickerButton
{
    _Bool _selected;
    UIView *_selectedView;
}

@property(retain, nonatomic) UIView *selectedView; // @synthesize selectedView=_selectedView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1;
- (_Bool)selected;
- (id)initWithImageNamed:(id)arg1;

@end

