//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSSecureCoding.h"

@class NSString, UIImage;

@interface GKBEmoji : NSObject <NSCoding, NSSecureCoding>
{
    NSString *_emojiString;
    NSString *_codepoint;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) NSString *codepoint; // @synthesize codepoint=_codepoint;
@property(retain, nonatomic) NSString *emojiString; // @synthesize emojiString=_emojiString;
- (void).cxx_destruct;
- (id)createEmojiPNGAtPath:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copy;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) UIImage *image;
- (id)initWithEmojiString:(id)arg1 codepoint:(id)arg2;

@end

