//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBCandidateViewHolder.h"

@class GKBCandidateSoftKeyBuilder, GKBSoftKeyView, NSArray, NSMutableArray;

@interface GKBFixedNumberCandidatesView : UIView <GKBCandidateViewHolder>
{
    NSMutableArray *_sortedCandidateViews;
    NSArray *_candidateViews;
    UIView *_containerView;
    GKBSoftKeyView *_singleCandidate;
    GKBCandidateSoftKeyBuilder *_candidateSoftKeyBuilder;
}

@property(retain, nonatomic) GKBCandidateSoftKeyBuilder *candidateSoftKeyBuilder; // @synthesize candidateSoftKeyBuilder=_candidateSoftKeyBuilder;
@property(retain, nonatomic) GKBSoftKeyView *singleCandidate; // @synthesize singleCandidate=_singleCandidate;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) NSArray *candidateViews; // @synthesize candidateViews=_candidateViews;
- (void).cxx_destruct;
@property(readonly, nonatomic) int capacity;
- (void)showSingleCandidate:(id)arg1;
- (void)showMultipleCandidates:(id)arg1;
- (void)initializeCandidateViews;
- (void)hide;
- (void)show;
- (void)clearCandidates;
- (int)appendCandidates:(id)arg1 selection:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

