//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GKBFlightEndpoint : NSObject
{
    NSString *_airportCode;
    NSString *_terminal;
    NSString *_gate;
    NSString *_scheduledISOTime;
    NSString *_actualISOTime;
}

@property(readonly, nonatomic) NSString *actualISOTime; // @synthesize actualISOTime=_actualISOTime;
@property(readonly, nonatomic) NSString *scheduledISOTime; // @synthesize scheduledISOTime=_scheduledISOTime;
@property(readonly, nonatomic) NSString *gate; // @synthesize gate=_gate;
@property(readonly, nonatomic) NSString *terminal; // @synthesize terminal=_terminal;
@property(readonly, nonatomic) NSString *airportCode; // @synthesize airportCode=_airportCode;
- (void).cxx_destruct;
- (id)ISOTime;
- (id)initWithAirportCode:(id)arg1 terminal:(id)arg2 gate:(id)arg3 scheduledISOTime:(id)arg4 actualISOTime:(id)arg5;

@end

