//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBFileUtilities : NSObject
{
}

+ (id)parseFilePaths:(id)arg1;
+ (id)dataForFile:(id)arg1 parentDirectory:(unsigned long long)arg2 childDirectory:(id)arg3;
+ (id)fullPath:(unsigned long long)arg1 childDirectory:(id)arg2;
+ (_Bool)deleteFile:(id)arg1 parentDirectory:(unsigned long long)arg2 childDirectory:(id)arg3;
+ (_Bool)saveToFile:(id)arg1 shortFileName:(id)arg2 parentDirectory:(unsigned long long)arg3 childDirectory:(id)arg4;

@end

