//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class NSArray, NSString, NSURL, UIColor;

@interface GKBFilmCardModel : GKBCardModel
{
    long long _filmMediaType;
    NSString *_title;
    double _numberRating;
    NSString *_ratingAttribution;
    NSString *_category;
    NSString *_genre;
    NSString *_duration;
    NSString *_releaseDate;
    NSArray *_directors;
    NSURL *_imageURL;
    UIColor *_backgroundColor;
}

@property(readonly, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSArray *directors; // @synthesize directors=_directors;
@property(readonly, nonatomic) NSString *releaseDate; // @synthesize releaseDate=_releaseDate;
@property(readonly, nonatomic) NSString *duration; // @synthesize duration=_duration;
@property(readonly, nonatomic) NSString *genre; // @synthesize genre=_genre;
@property(readonly, nonatomic) NSString *category; // @synthesize category=_category;
@property(readonly, nonatomic) NSString *ratingAttribution; // @synthesize ratingAttribution=_ratingAttribution;
@property(readonly, nonatomic) double numberRating; // @synthesize numberRating=_numberRating;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) long long filmMediaType; // @synthesize filmMediaType=_filmMediaType;
- (void).cxx_destruct;
- (id)openURL;
- (id)shareText;
- (_Bool)hasCustomBackgroundColor;
- (id)accessoryImageURL;
- (id)initWithMediaType:(long long)arg1 title:(id)arg2 numberRating:(double)arg3 ratingAttribution:(id)arg4 category:(id)arg5 genre:(id)arg6 duration:(id)arg7 releaseDate:(id)arg8 directors:(id)arg9 imageURL:(id)arg10 backgroundColor:(id)arg11;

@end

