//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GKBGIFDataManager : NSObject
{
    NSArray *_GIFCategories;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSArray *GIFCategories; // @synthesize GIFCategories=_GIFCategories;
- (void).cxx_destruct;
- (void)GIFCategoriesWithCompletionBlock:(CDUnknownBlockType)arg1;

@end

