//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBGIFViewCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class GKBGIFCategory, NSArray, NSString, UICollectionView;

@interface GKBGIFSearchResultsView : UIView <GKBGIFViewCellDelegate, UICollectionViewDataSource, UICollectionViewDelegate>
{
    unsigned long long _GIFResultsStartIndex;
    _Bool _isSearching;
    long long _currentCategoryIndex;
    GKBGIFCategory *_currentCategory;
    id <GKBGIFSearchResultsViewDelegate> _delegate;
    NSArray *_results;
    UICollectionView *_collectionView;
    long long _GIFHeight;
}

@property(nonatomic) long long GIFHeight; // @synthesize GIFHeight=_GIFHeight;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain) NSArray *results; // @synthesize results=_results;
@property(nonatomic) __weak id <GKBGIFSearchResultsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleGKBUIInputViewControllerDidReceiveRotationNotification:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)invalidateGIFResult:(id)arg1;
- (unsigned long long)fileDirectoryForIndex:(long long)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)initSearchResultsCollectionView;
- (void)hideResults;
- (void)displayResults:(id)arg1 appendToPreviousResults:(_Bool)arg2 isSearching:(_Bool)arg3 currentCategoryIndex:(long long)arg4 currentCategory:(id)arg5;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

