//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "GKBAsyncImageViewDelegate.h"

@class GKBAsyncImageView, GKBGIFResult, GKBImageAttributionView, GKBShadowInkTouchController, NSArray;

@interface GKBGIFViewCell : UICollectionViewCell <GKBAsyncImageViewDelegate>
{
    NSArray *_layoutConstraints;
    GKBImageAttributionView *_attributionView;
    GKBShadowInkTouchController *_touchController;
    id <GKBGIFViewCellDelegate> _delegate;
    GKBAsyncImageView *_imageView;
    GKBGIFResult *_GIFResult;
}

@property(retain, nonatomic) GKBGIFResult *GIFResult; // @synthesize GIFResult=_GIFResult;
@property(retain, nonatomic) GKBAsyncImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak id <GKBGIFViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)imageFailedToLoad:(id)arg1;
- (void)imageLoadedWithData:(id)arg1 URL:(id)arg2;
- (void)reinitImageView;
- (void)removeNotificationObservers;
- (void)invalidateGIF;
- (id)GIFData;
- (id)GIFURLString;
- (void)loadGIF:(id)arg1 fromDirectory:(unsigned long long)arg2 withHeight:(double)arg3;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

