//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GKBInputBundle, NSMutableDictionary;

@interface GKBInputBundleManager : NSObject
{
    NSMutableDictionary *_inputBundles;
    NSMutableDictionary *_loadedInputBundles;
    GKBInputBundle *_currentInputBundle;
    id <GKBInputBundleDelegate> _inputBundleDelegate;
}

@property(nonatomic) __weak id <GKBInputBundleDelegate> inputBundleDelegate; // @synthesize inputBundleDelegate=_inputBundleDelegate;
@property(readonly, nonatomic) GKBInputBundle *currentInputBundle; // @synthesize currentInputBundle=_currentInputBundle;
- (void).cxx_destruct;
- (void)sendKeyEvent:(int)arg1 withCode:(int)arg2;
- (id)languageFromKeyboardType:(long long)arg1;
- (id)inputBundleForLanguage:(id)arg1;
- (id)inputBundleForInputTraits:(id)arg1;
- (void)loadNecessaryInputBundles;
- (void)extensionBackspaceUp;
- (void)extensionBackspaceDown;
- (void)discardKeyboardViews;
- (void)cursorHasMoved;
- (void)close;
- (void)deactivate;
- (void)configureWithLexicon:(id)arg1;
- (void)activateWithInputTraits:(id)arg1 keyboardType:(int *)arg2;
- (void)addInputBundleWithDef:(id)arg1 language:(id)arg2;

@end

