//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface GKBImageAsset : NSObject
{
    NSURL *_sourceURL;
    NSURL *_proxyURL;
    unsigned long long *_parentDirectory;
    NSString *_childDirectory;
    NSString *_fileName;
}

@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(readonly, nonatomic) NSString *childDirectory; // @synthesize childDirectory=_childDirectory;
@property(readonly, nonatomic) unsigned long long *parentDirectory; // @synthesize parentDirectory=_parentDirectory;
@property(readonly, nonatomic) NSURL *proxyURL; // @synthesize proxyURL=_proxyURL;
@property(readonly, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
- (void).cxx_destruct;
- (id)fullFilePath;
- (_Bool)isEqual:(id)arg1;
- (id)initWithSourceURL:(id)arg1 proxyURL:(id)arg2 parentDirectory:(unsigned long long)arg3 childDirectory:(id)arg4;

@end

