//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBIMEDelegate.h"
#import "GKBKeyboardDelegate.h"

@class GKBInputBundleDef, GKBKeyboardViewContainerView, GKBPopupViewManager, NSMutableArray, NSTimer;

@interface GKBInputBundle : NSObject <GKBIMEDelegate, GKBKeyboardDelegate>
{
    NSMutableArray *_keyboards;
    id <UITextInputTraits> _textInputTraits;
    _Bool _isActivated;
    GKBKeyboardViewContainerView *_headerViewHolder;
    GKBKeyboardViewContainerView *_bodyViewHolder;
    int _currentDelCode;
    NSTimer *_delKeyTimer;
    long long _lastScrubMoveStop;
    double _lastScrubMoveTime;
    id <GKBIME> _IME;
    id <GKBKeyboard> _currentKeyboard;
    id <GKBInputBundleDelegate> _delegate;
    id <GKBUserMetrics> _userMetrics;
    GKBInputBundleDef *_inputBundleDef;
    unsigned long long _externalCandidateRequiredCount;
}

+ (int)keyboardTypeFromString:(id)arg1;
@property(nonatomic) unsigned long long externalCandidateRequiredCount; // @synthesize externalCandidateRequiredCount=_externalCandidateRequiredCount;
@property(retain, nonatomic) GKBInputBundleDef *inputBundleDef; // @synthesize inputBundleDef=_inputBundleDef;
@property(retain, nonatomic) id <GKBUserMetrics> userMetrics; // @synthesize userMetrics=_userMetrics;
@property(nonatomic) __weak id <GKBInputBundleDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) id <GKBKeyboard> currentKeyboard; // @synthesize currentKeyboard=_currentKeyboard;
@property(readonly, nonatomic) id <GKBIME> IME; // @synthesize IME=_IME;
- (void).cxx_destruct;
- (int)typeForKeyboardType:(int)arg1;
- (void)createKeyboardForEntry:(id)arg1;
- (void)handleScrubMoveEvent:(id)arg1;
- (void)startDeletingWords;
- (void)startChunkedDeleteTimer;
- (void)sendDelEventToIME;
- (void)handleDelUpBeforeIME;
- (void)handleDelDown;
- (void)sendUpdateAutoCapEvent;
- (void)updateReturnKeyState;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)abortComposing;
- (void)finishComposing;
- (void)handleSelectTextCandidate:(id)arg1;
- (_Bool)handleEventBeforeIME:(id)arg1;
- (void)handleEventInternal:(id)arg1;
- (_Bool)handleEventByCurrentKeyboard:(id)arg1;
- (void)keyboard:(id)arg1 sendKeyEvent:(id)arg2;
- (void)keyboard:(id)arg1 requestCandidates:(int)arg2;
- (void)keyboard:(id)arg1 statesChangedFrom:(unsigned long long)arg2 to:(unsigned long long)arg3;
- (void)requestCandidates:(int)arg1;
- (void)keyboard:(id)arg1 selectTextCandidate:(id)arg2 forCommit:(_Bool)arg3;
- (int)currentKeyboardType;
- (void)switchToPrimeKeyboard;
- (void)discardViews;
- (void)cursorHasMoved;
- (id)textAfterCursor:(long long)arg1;
- (id)textBeforeCursor:(long long)arg1;
- (void)IME:(id)arg1 unconsumedEvent:(id)arg2;
- (void)IME:(id)arg1 setComposingRangeWithLength:(unsigned long long)arg2;
- (void)IME:(id)arg1 updateTextWithBeforeComposingRangeLength:(unsigned long long)arg2 preComposingRangeText:(id)arg3 composingText:(id)arg4;
- (void)IME:(id)arg1 setKeyboardState:(unsigned long long)arg2 on:(_Bool)arg3;
- (void)IME:(id)arg1 commitText:(id)arg2;
- (void)IME:(id)arg1 appendTextCandidates:(id)arg2 selection:(id)arg3 hasMore:(_Bool)arg4;
- (void)IME:(id)arg1 textCandidateUpdated:(_Bool)arg2;
- (void)IME:(id)arg1 setComposingText:(id)arg2;
- (void)closeKeyboards;
- (void)closeIme;
- (void)close;
- (void)deactivate;
- (id)keyboardWithType:(int)arg1;
- (void)activateCurrentKeyboard;
- (void)switchToKeyboardType:(int)arg1;
- (void)configureWithLexicon:(id)arg1;
- (void)activateWithTextInputTraits:(id)arg1 keyboardType:(int *)arg2;
- (id)imeFromInputBundleDef:(id)arg1;
- (id)initWithInputBundleDef:(id)arg1;

@end

