//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class NSString, NSURL;

@interface GKBImageCardModel : GKBCardModel
{
    _Bool _isAnimated;
    NSURL *_imageURL;
    NSURL *_sourceURL;
    NSString *_attribution;
    struct CGSize _size;
}

@property(nonatomic) _Bool isAnimated; // @synthesize isAnimated=_isAnimated;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(readonly, nonatomic) NSString *attribution; // @synthesize attribution=_attribution;
@property(readonly, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (_Bool)shouldDisplayWithFooter;
- (_Bool)isFullCardView;
- (id)openURL;
- (id)footerActionModels;
- (id)initWithImageURL:(id)arg1 sourceURL:(id)arg2 attribution:(id)arg3 size:(struct CGSize)arg4;

@end

