//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class GKBImageLayer, UIColor, UIImage;

@interface GKBImageViewWithBackground : UIView
{
    GKBImageLayer *_backgroundLayer;
    _Bool _highlighted;
    UIImage *_image;
    UIImage *_highlightedImage;
    UIImage *_backgroundImage;
    UIImage *_highlightedBackgroundImage;
    UIColor *_foregroundColor;
}

+ (Class)layerClass;
@property(retain, nonatomic) UIColor *foregroundColor; // @synthesize foregroundColor=_foregroundColor;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) UIImage *highlightedBackgroundImage; // @synthesize highlightedBackgroundImage=_highlightedBackgroundImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) UIImage *highlightedImage; // @synthesize highlightedImage=_highlightedImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)prepareBackgroundLayerIfNeeded;
- (void)setFrame:(struct CGRect)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)didMoveToSuperview;

@end

