//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBInputBundle, GKBPopupViewManager, NSArray, NSString, UIView;

@protocol GKBInputBundleDelegate
@property(readonly, nonatomic) id <GKBUserMetrics> userMetrics;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)inputBundleSwitchToOtherKeyboard;
- (void)inputBundle:(GKBInputBundle *)arg1 didFindTextSuggestions:(NSArray *)arg2;
- (void)moveCursorWithOffset:(long long)arg1;
- (void)hideKeyboard;
- (void)activateExtensionWithName:(NSString *)arg1 data:(id)arg2;
- (void)inputBundleCurrentLanguageDidChange;
- (void)inputBundle:(GKBInputBundle *)arg1 setKeyboardView:(UIView *)arg2 forType:(int)arg3;
- (_Bool)hasText;
- (NSString *)textAfterCursor:(long long)arg1;
- (NSString *)textBeforeCursor:(long long)arg1;
- (void)inputBundleDeleteBackward:(GKBInputBundle *)arg1 isWord:(_Bool)arg2;
- (void)inputBundle:(GKBInputBundle *)arg1 setComposingRangeWithLength:(unsigned long long)arg2;
- (void)inputBundle:(GKBInputBundle *)arg1 commitText:(NSString *)arg2;
- (void)inputBundle:(GKBInputBundle *)arg1 updateTextWithBeforeComposingRangeLength:(unsigned long long)arg2 preComposingRangeText:(NSString *)arg3 composingText:(NSString *)arg4;
- (void)inputBundle:(GKBInputBundle *)arg1 setComposingText:(NSString *)arg2;
@end

