//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardView.h"

@class UIButton, UIImageView, UILabel;

@interface GKBImproveGboardCardView : GKBCardView
{
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_leftButton;
    UILabel *_leftButtonLabel;
    UIButton *_rightButton;
    UILabel *_rightButtonLabel;
}

- (void).cxx_destruct;
- (void)handleNotNow:(id)arg1;
- (void)handleSendFeedback:(id)arg1;
- (void)activateConstraintsForButtonLabel:(id)arg1;
- (void)loadWithModel:(id)arg1 toShare:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

