//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GD4Decoder, GD4InputContext, NSArray, NSString;

@interface GKBInputContext : NSObject
{
    id <GKBIMEDelegate> _imeDelegate;
    id <GKBIME> _ime;
    GD4Decoder *_decoder;
    NSArray *_candidates;
    unsigned long long _candidateIndex;
    NSString *_language;
    GD4InputContext *_inputContext;
}

@property(retain, nonatomic) GD4InputContext *inputContext; // @synthesize inputContext=_inputContext;
- (void).cxx_destruct;
- (id)parseInputText;
- (void)updateComposingRange;
- (_Bool)isComposingRangeEmpty;
- (_Bool)resetIfTextBeforeCursorChanged;
- (_Bool)isEmpty;
- (void)applyDiff:(id)arg1 commitReason:(long long)arg2;
- (id)description;
- (id)nextCandidates:(int)arg1;
- (_Bool)hasCandidates;
- (void)truncateTextBeforeCursorIfNeeded;
- (void)extendBeforeLengthIfNeeded;
- (void)resetCandidateIndex;
- (void)reset;
- (void)fullyReset;
- (id)initWithIME:(id)arg1 IMEDelegate:(id)arg2 decoder:(id)arg3 language:(id)arg4;

@end

