//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBCandidate, GKBEvent, GKBPopupViewManager;

@protocol GKBKeyboardDelegate
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)keyboard:(id <GKBKeyboard>)arg1 statesChangedFrom:(unsigned long long)arg2 to:(unsigned long long)arg3;
- (void)keyboard:(id <GKBKeyboard>)arg1 requestCandidates:(int)arg2;
- (void)keyboard:(id <GKBKeyboard>)arg1 selectTextCandidate:(GKBCandidate *)arg2 forCommit:(_Bool)arg3;
- (void)keyboard:(id <GKBKeyboard>)arg1 sendKeyEvent:(GKBEvent *)arg2;
@end

