//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class NSString, NSURL;

@interface GKBKGAnswerCardModel : GKBCardModel
{
    NSString *_entity;
    NSString *_attribute;
    NSString *_answer;
    NSURL *_imageURL;
}

@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSString *answer; // @synthesize answer=_answer;
@property(readonly, nonatomic) NSString *attribute; // @synthesize attribute=_attribute;
@property(readonly, nonatomic) NSString *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (id)openURL;
- (id)shareText;
- (id)accessoryImageURL;
- (id)initWithEntity:(id)arg1 attribute:(id)arg2 answer:(id)arg3 imageURL:(id)arg4;

@end

