//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class GKBKeyboardViewDef, NSString;

@interface GKBKeyboardDef : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *defaultPopupLayout; // @dynamic defaultPopupLayout;
@property(nonatomic) _Bool hasDefaultPopupLayout; // @dynamic hasDefaultPopupLayout;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(nonatomic) _Bool hasInitialStates; // @dynamic hasInitialStates;
@property(nonatomic) _Bool hasKeyboardBodyView; // @dynamic hasKeyboardBodyView;
@property(nonatomic) _Bool hasKeyboardClass; // @dynamic hasKeyboardClass;
@property(nonatomic) _Bool hasKeyboardHeaderView; // @dynamic hasKeyboardHeaderView;
@property(nonatomic) _Bool hasPersistentKey; // @dynamic hasPersistentKey;
@property(nonatomic) _Bool hasPersistentStates; // @dynamic hasPersistentStates;
@property(nonatomic) _Bool hasSessionStates; // @dynamic hasSessionStates;
@property(retain, nonatomic) NSString *id_p; // @dynamic id_p;
@property(nonatomic) long long initialStates; // @dynamic initialStates;
@property(retain, nonatomic) GKBKeyboardViewDef *keyboardBodyView; // @dynamic keyboardBodyView;
@property(retain, nonatomic) NSString *keyboardClass; // @dynamic keyboardClass;
@property(retain, nonatomic) GKBKeyboardViewDef *keyboardHeaderView; // @dynamic keyboardHeaderView;
@property(retain, nonatomic) NSString *persistentKey; // @dynamic persistentKey;
@property(nonatomic) long long persistentStates; // @dynamic persistentStates;
@property(nonatomic) long long sessionStates; // @dynamic sessionStates;

@end

