//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBKeyboardViewHelper, GKBSoftKeyboardView;

@protocol GKBKeyboardViewHelperDelegate
- (void)keyboardViewHelper:(GKBKeyboardViewHelper *)arg1 didDiscardView:(GKBSoftKeyboardView *)arg2;
- (void)keyboardViewHelper:(GKBKeyboardViewHelper *)arg1 didCreateView:(GKBSoftKeyboardView *)arg2;
@end

