//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBEventConsumer.h"

@class GKBCandidate, GKBEvent, GKBKeyboardDef, GKBKeyboardViewContainerView, NSArray, NSString;

@protocol GKBKeyboard <GKBEventConsumer>
@property(readonly, nonatomic) id <UITextInputTraits> textInputTraits;
@property(readonly, nonatomic) unsigned long long states;
@property(readonly, nonatomic) GKBKeyboardDef *keyboardDef;
@property(readonly, nonatomic) int type;
- (void)removeEventConsumer:(id <GKBEventConsumer>)arg1;
- (void)addEventConsumer:(id <GKBEventConsumer>)arg1;
- (_Bool)shouldReturnToPrimeOnKey:(GKBEvent *)arg1;
- (void)setReadingTextCandidate:(NSArray *)arg1;
- (void)appendTextCandidate:(NSArray *)arg1 selection:(GKBCandidate *)arg2 hasMore:(_Bool)arg3;
- (void)textCandidateUpdated:(_Bool)arg1;
- (_Bool)setComposingText:(NSString *)arg1;
- (_Bool)isStateSupported:(unsigned long long)arg1;
- (void)changeKeyboardState:(unsigned long long)arg1 enabled:(_Bool)arg2;
- (void)endBatchChangeState;
- (void)beginBatchChangeState;
- (void)deactivate;
- (void)activateWithTraits:(id <UITextInputTraits>)arg1;
- (void)discardKeyboardView;
- (void)addKeyboardViewForType:(int)arg1 toHolder:(GKBKeyboardViewContainerView *)arg2;
- (void)close;
- (void)configureWithKeyboardDef:(GKBKeyboardDef *)arg1 type:(int)arg2 delegate:(id <GKBKeyboardDelegate>)arg3;
@end

