//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface GKBKeyData : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *data_p; // @dynamic data_p;
@property(nonatomic) _Bool forDecode; // @dynamic forDecode;
@property(nonatomic) _Bool hasData_p; // @dynamic hasData_p;
@property(nonatomic) _Bool hasForDecode; // @dynamic hasForDecode;
@property(nonatomic) _Bool hasKeyCode; // @dynamic hasKeyCode;
@property(nonatomic) int keyCode; // @dynamic keyCode;

@end

