//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface GKBKeyboardViewDef : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasKeymappingArray; // @dynamic hasKeymappingArray;
@property(nonatomic) _Bool hasLayoutmappingArray; // @dynamic hasLayoutmappingArray;
@property(nonatomic) _Bool hasMergeKeymappingArray; // @dynamic hasMergeKeymappingArray;
@property(nonatomic) _Bool hasSoftkeysArray; // @dynamic hasSoftkeysArray;
@property(nonatomic) _Bool hasTouchHandlersArray; // @dynamic hasTouchHandlersArray;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(retain, nonatomic) PBMutableArray *keymappingArray; // @dynamic keymappingArray;
@property(retain, nonatomic) PBMutableArray *layoutmappingArray; // @dynamic layoutmappingArray;
@property(retain, nonatomic) PBMutableArray *mergeKeymappingArray; // @dynamic mergeKeymappingArray;
@property(retain, nonatomic) PBMutableArray *softkeysArray; // @dynamic softkeysArray;
@property(retain, nonatomic) PBMutableArray *touchHandlersArray; // @dynamic touchHandlersArray;
@property(nonatomic) int type; // @dynamic type;

@end

