//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GD4Decoder, GD4DynamicLm, NSString, UILexicon;

@interface GKBLanguageModelDatabase : NSObject
{
    GD4Decoder *_decoder;
    GD4DynamicLm *_dynamicLm;
    UILexicon *_lexicon;
    NSString *_mainLanguage;
}

+ (_Bool)isEmoji:(id)arg1;
+ (id)languageModelDir;
+ (id)MD5FromArray:(id)arg1;
- (void).cxx_destruct;
- (void)updateUILexicon;
- (void)applyDifference:(id)arg1 targetTerms:(id)arg2 key:(id)arg3;
- (void)clearDynamicLanguageModel:(id)arg1;
- (_Bool)setMainLanguage:(id)arg1;
- (id)mainLangaugeModelDescriptor;
- (id)languageModelDescriptorWithType:(int)arg1;
- (void)setUILexicon:(id)arg1 onSuccess:(CDUnknownBlockType)arg2;
- (void)setDecoder:(id)arg1 onSuccess:(CDUnknownBlockType)arg2;
- (id)init;

@end

