//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class GKBRatingsAndReviewsModel, NSString, NSURL;

@interface GKBLocalCardModel : GKBCardModel
{
    NSString *_title;
    NSURL *_URL;
    GKBRatingsAndReviewsModel *_ratingsAndReviews;
    NSString *_address;
    NSString *_hours;
    NSURL *_imageURL;
    NSString *_phoneNumber;
    NSURL *_mapURL;
}

@property(readonly, nonatomic) NSURL *mapURL; // @synthesize mapURL=_mapURL;
@property(readonly, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSString *hours; // @synthesize hours=_hours;
@property(readonly, nonatomic) NSString *address; // @synthesize address=_address;
@property(readonly, nonatomic) GKBRatingsAndReviewsModel *ratingsAndReviews; // @synthesize ratingsAndReviews=_ratingsAndReviews;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)shareText;
- (id)mapsURL;
- (id)openURL;
- (id)accessoryImageURL;
- (id)footerActionModels;
- (id)initWithTitle:(id)arg1 URL:(id)arg2 ratingsAndReviews:(id)arg3 address:(id)arg4 hours:(id)arg5 imageURL:(id)arg6 phoneNumber:(id)arg7 mapURL:(id)arg8;

@end

