//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBLanguageManager.h"

#import "GKBBackgroundDownloaderDelegate.h"

@class GKBBackgroundDownloader, NSArray, NSMutableDictionary;

@interface GKBLanguageManagerWithDownloader : GKBLanguageManager <GKBBackgroundDownloaderDelegate>
{
    NSMutableDictionary *_downloadingLanguages;
    NSMutableDictionary *_downloadingEntries;
    GKBBackgroundDownloader *_downloader;
}

+ (id)mainLanguageModelIDForLanguage:(struct NSString *)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (_Bool)isChecksumValidForItemID:(id)arg1 toFileURL:(id)arg2;
- (void)handleFailedDownloadWithItemID:(id)arg1 error:(id)arg2;
- (void)handleFinishDownloadWithItemID:(id)arg1 toFileURL:(id)arg2;
- (id)defaultVariantForLanguage:(struct NSString *)arg1;
- (id)languageModelEntryForLanguage:(struct NSString *)arg1;
- (id)localLanguageModelFilePath:(id)arg1;
- (void)didFailedDownloadWithItemID:(id)arg1 error:(id)arg2;
- (void)didFinishDownloadWithItemID:(id)arg1 toFileURL:(id)arg2;
- (float)downloadedPercentageForLanguage:(struct NSString *)arg1;
- (unsigned long long)downloadSizeForLanguage:(struct NSString *)arg1;
@property(readonly, nonatomic) NSArray *downloadingLanguages;
- (void)addLanguage:(struct NSString *)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

