//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardView.h"

@class UIButton, UIImageView, UILabel;

@interface GKBLocationPermissionCardView : GKBCardView
{
    UIImageView *_bannerImageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_leftButton;
    UILabel *_leftButtonLabel;
    UIButton *_rightButton;
    UILabel *_rightButtonLabel;
}

- (void).cxx_destruct;
- (void)handleLocationPermissionWasDeniedNotification:(id)arg1;
- (void)handleLocationPermissionWasGrantedNotification:(id)arg1;
- (void)didGrantPermission:(_Bool)arg1;
- (void)handleGoToSettings:(id)arg1;
- (void)handleOK:(id)arg1;
- (void)handleDismiss:(id)arg1;
- (void)handleLocationPermissionTap:(id)arg1;
- (void)activateConstraintsForLabel:(id)arg1 inButton:(id)arg2;
- (void)loadWithModel:(id)arg1 toShare:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

