//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBKeyboardDelegate.h"
#import "GKBTouchHandler.h"

@class GKBKeyboardViewDef, GKBPopupKeyboardHelper, GKBPopupViewManager, GKBSoftKeyView, GKBSoftKeyboardView, NSArray, NSString, NSTimer, UITouch;

@interface GKBLanguageSwitcherHandler : NSObject <GKBTouchHandler, GKBKeyboardDelegate>
{
    _Bool _activated;
    id <GKBTouchHandlerDelegate> _delegate;
    GKBSoftKeyboardView *_softKeyboardView;
    GKBSoftKeyView *_globeKey;
    UITouch *_firstTouch;
    GKBPopupKeyboardHelper *_popupKeyboardHelper;
    NSArray *_labels;
    NSArray *_keyCodes;
    NSArray *_viewIds;
    NSArray *_keyIds;
    _Bool _hasLongPressBeenActivated;
    NSTimer *_longPressTimer;
    GKBKeyboardViewDef *_keyboardDef;
    GKBPopupViewManager *_popupViewManager;
}

@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager; // @synthesize popupViewManager=_popupViewManager;
- (void).cxx_destruct;
- (id)getNextLanguage;
- (_Bool)pointIsInsideGlobeKeyTargetView:(struct CGPoint)arg1;
- (void)destroyLongPressTimer;
- (void)longPressTimerFired:(id)arg1;
- (void)startLongPressTimer;
- (id)createSoftKeyDefWithKeyCode:(int)arg1 label:(id)arg2 name:(id)arg3 data:(id)arg4 layout:(id)arg5;
- (void)updateKeyboardViewDefForLabels:(id)arg1;
- (id)createKeyboardViewDef;
- (id)getPopupViewManager;
- (void)keyboard:(id)arg1 statesChangedFrom:(unsigned long long)arg2 to:(unsigned long long)arg3;
- (void)keyboard:(id)arg1 sendKeyEvent:(id)arg2;
- (void)keyboard:(id)arg1 selectTextCandidate:(id)arg2 forCommit:(_Bool)arg3;
- (void)keyboard:(id)arg1 requestCandidates:(int)arg2;
- (void)handleTouches:(id)arg1 withAction:(long long)arg2;
- (void)onKeyboardStateChangedTo:(unsigned long long)arg1 from:(unsigned long long)arg2;
- (void)onSoftKeyboardViewLayout;
- (void)setSoftKeyboardView:(id)arg1;
- (void)close;
- (void)reset;
- (void)deactivate;
- (void)activate;
- (void)configureWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

