//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface GKBLanguageModelEntry : NSObject <NSCopying>
{
    NSString *_ID;
    NSString *_locale;
    NSString *_label;
    NSString *_update;
    unsigned long long _size;
    NSString *_checkSum;
    NSString *_rawCheckSum;
    NSString *_remoteURL;
    NSString *_localPath;
    unsigned long long _version;
    NSString *_formatVersion;
}

+ (id)entryFromMetaDataEntry:(id)arg1;
@property(retain, nonatomic) NSString *formatVersion; // @synthesize formatVersion=_formatVersion;
@property(nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *localPath; // @synthesize localPath=_localPath;
@property(retain, nonatomic) NSString *remoteURL; // @synthesize remoteURL=_remoteURL;
@property(retain, nonatomic) NSString *rawCheckSum; // @synthesize rawCheckSum=_rawCheckSum;
@property(retain, nonatomic) NSString *checkSum; // @synthesize checkSum=_checkSum;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *update; // @synthesize update=_update;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *locale; // @synthesize locale=_locale;
@property(retain, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)dictionary;

@end

