//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, QTMButton, UIImageView, UILabel;

@interface GKBNoFullAccessView : UIView
{
    UIImageView *_errorImageView;
    UILabel *_noFullAccessLabel;
    QTMButton *_gotoSettingsButton;
    NSMutableArray *_layoutConstraints;
}

@property(retain, nonatomic) NSMutableArray *layoutConstraints; // @synthesize layoutConstraints=_layoutConstraints;
@property(retain, nonatomic) QTMButton *gotoSettingsButton; // @synthesize gotoSettingsButton=_gotoSettingsButton;
@property(retain, nonatomic) UILabel *noFullAccessLabel; // @synthesize noFullAccessLabel=_noFullAccessLabel;
@property(retain, nonatomic) UIImageView *errorImageView; // @synthesize errorImageView=_errorImageView;
- (void).cxx_destruct;
- (void)buttonPressed;
- (void)updateConstraintsForSize:(struct CGSize)arg1;
- (void)gkb_init;
- (id)init;

@end

