//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, UIView;

@interface GKBPopupViewManager : NSObject
{
    NSMutableDictionary *_layoutNibCache;
    NSMutableArray *_hidingPopupViews;
    UIView *_inputView;
}

@property(nonatomic) __weak UIView *inputView; // @synthesize inputView=_inputView;
- (void).cxx_destruct;
- (id)nibWithName:(id)arg1 fromBundle:(id)arg2;
- (void)dismissPopupView:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isPopupViewShown:(id)arg1;
- (id)layoutConstraintsForView:(id)arg1 anchorView:(id)arg2 position:(unsigned long long)arg3 offset:(struct CGVector)arg4;
- (void)showPopupView:(id)arg1 anchorView:(id)arg2 position:(unsigned long long)arg3 offset:(struct CGVector)arg4;
- (id)loadPopupView:(id)arg1 fromBundle:(id)arg2;
- (id)init;

@end

