//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBPopupAnimation.h"

@class CALayer, NSArray, NSLayoutConstraint, UIImage;

@interface GKBPopupBubble : UIView <GKBPopupAnimation>
{
    unsigned long long _popupViewPosition;
    UIView *_contentView;
    struct CGSize _contentSize;
    struct CGSize _anchorSize;
    double _contentLeft;
    _Bool _hasExtendedLeftWing;
    _Bool _hasFoldedLeftWing;
    _Bool _hasExtendedRightWing;
    _Bool _hasFoldedRightWing;
    NSArray *_layoutConstraints;
    NSLayoutConstraint *_containerWidthConstraint;
    NSLayoutConstraint *_containerOffsetConstraint;
    UIImage *_mask;
    CALayer *_maskLayer;
    _Bool _masksToShape;
    double _animationDelay;
    double _animationDuration;
    UIView *_containerView;
    UIView *_extendedLeftWing;
    UIView *_extendedRightWing;
    UIView *_foldedLeftWing;
    UIView *_foldedRightWing;
    UIView *_bodyView;
    NSLayoutConstraint *_widthConstraint;
    NSLayoutConstraint *_heightConstraint;
    long long _layoutDirection;
}

@property(nonatomic) _Bool masksToShape; // @synthesize masksToShape=_masksToShape;
@property(readonly, nonatomic) long long layoutDirection; // @synthesize layoutDirection=_layoutDirection;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *widthConstraint; // @synthesize widthConstraint=_widthConstraint;
@property(retain, nonatomic) UIView *bodyView; // @synthesize bodyView=_bodyView;
@property(retain, nonatomic) UIView *foldedRightWing; // @synthesize foldedRightWing=_foldedRightWing;
@property(retain, nonatomic) UIView *foldedLeftWing; // @synthesize foldedLeftWing=_foldedLeftWing;
@property(retain, nonatomic) UIView *extendedRightWing; // @synthesize extendedRightWing=_extendedRightWing;
@property(retain, nonatomic) UIView *extendedLeftWing; // @synthesize extendedLeftWing=_extendedLeftWing;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(readonly, nonatomic) double animationDelay; // @synthesize animationDelay=_animationDelay;
- (void).cxx_destruct;
- (void)hidePopupAnimationWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) unsigned long long popupViewPosition;
- (id)layoutConstraintsWithAnchorView:(id)arg1 containerLayoutParams:(CDStruct_7b7c8ae7)arg2;
- (id)captureViewInRect:(struct CGRect)arg1;
- (void)createMask;
- (void)didMoveToSuperview;
- (void)inflatePopupView:(struct CGSize)arg1;
- (CDStruct_7b7c8ae7)alignContainerViewToAnchor:(struct CGRect)arg1;
- (void)pickWingsToFitAnchorRect:(struct CGRect)arg1 windowSize:(struct CGSize)arg2;
- (void)centerAlignToAnchor:(struct CGRect)arg1 windowSize:(struct CGSize)arg2 offsetX:(double)arg3;
- (_Bool)rightAlignIfFitsToAnchor:(struct CGRect)arg1 windowSize:(struct CGSize)arg2 offsetX:(double)arg3;
- (_Bool)leftAlignIfFitsToAnchor:(struct CGRect)arg1 windowSize:(struct CGSize)arg2 offsetX:(double)arg3;
- (void)initializeWithContentView:(id)arg1 anchorView:(id)arg2 contentSize:(struct CGSize)arg3 offsetX:(double)arg4 preferredLayoutDirection:(long long)arg5;

@end

