//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GKBKeyData, GKBPopupBubble, GKBPopupViewManager, NSMutableDictionary, NSString;

@interface GKBPopupHandler : NSObject
{
    GKBPopupViewManager *_popupViewManager;
    NSString *_defaultPopupLayout;
    NSString *_currentPopupLayout;
    GKBPopupBubble *_popupView;
    struct UIView *_contentView;
    NSMutableDictionary *_cachedPopupViews;
    GKBKeyData *_selectedKeyData;
}

@property(retain, nonatomic) GKBKeyData *selectedKeyData; // @synthesize selectedKeyData=_selectedKeyData;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool acceptsTouchEvents;
@property(readonly, nonatomic, getter=isPopupShown) _Bool popupShown;
- (void)hidePopupAnimated:(_Bool)arg1;
- (_Bool)handleTouch:(id)arg1;
- (void)showPopupForAction:(id)arg1 targetView:(id)arg2 touchPoint:(struct CGPoint)arg3;
- (id)initWithLayout:(id)arg1 popupViewManager:(id)arg2;

@end

