//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardView.h"

@class NSArray, UIButton, UIImageView, UILabel, UIView;

@interface GKBRateGboardCardView : GKBCardView
{
    UIView *_backgroundView;
    UIImageView *_imageView;
    UILabel *_textLabel;
    UIButton *_leftButton;
    UILabel *_leftButtonLabel;
    UIButton *_rightButton;
    UILabel *_rightButtonLabel;
    NSArray *_imageViewConstraints;
    NSArray *_textLabelConstraints;
}

- (void).cxx_destruct;
- (id)constraintsToCenterView:(id)arg1 inSuperviewWithYOffset:(double)arg2;
- (void)handleGoToFeedback:(id)arg1;
- (void)handleGoToAppStore:(id)arg1;
- (void)handleFeedback:(id)arg1;
- (void)activateConstraintsForButtonLabel:(id)arg1;
- (void)loadWithModel:(id)arg1 toShare:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

