//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBSoftKeyboardView.h"

@class NSMutableDictionary, NSString;

@interface GKBSoftKeyboardViewWithFixedLayout : GKBSoftKeyboardView
{
    const CDStruct_5401d8df *_styleDefinition;
    NSMutableDictionary *_stylesArray;
    const struct {
        char *_field1;
        CDStruct_d2b197d1 _field2;
    } *_fragments;
    NSMutableDictionary *_allFragmentViews;
    NSString *_layoutName;
}

@property(copy, nonatomic) NSString *layoutName; // @synthesize layoutName=_layoutName;
- (void).cxx_destruct;
- (void)createFragmentView:(const CDStruct_21549188 *)arg1;
- (double)resolveSize:(double)arg1 basedOn:(double)arg2;
- (const CDStruct_21549188 *)fragmentWithType:(id)arg1;
- (const CDStruct_5401d8df *)styleWithName:(id)arg1;
- (void)createKeyboard;
- (void)setNeedsLayout;
- (void)layoutSubviews;

@end

