//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class NSString, NSURL;

@interface GKBShortAnswerCardModel : GKBCardModel
{
    NSString *_title;
    NSString *_shortAnswer;
    NSString *_explanation;
    NSString *_attributionName;
    NSURL *_attributionURL;
    NSURL *_imageURL;
}

@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSURL *attributionURL; // @synthesize attributionURL=_attributionURL;
@property(readonly, nonatomic) NSString *attributionName; // @synthesize attributionName=_attributionName;
@property(readonly, nonatomic) NSString *explanation; // @synthesize explanation=_explanation;
@property(readonly, nonatomic) NSString *shortAnswer; // @synthesize shortAnswer=_shortAnswer;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)openURL;
- (id)shareText;
- (id)footerActionModels;
- (id)initWithTitle:(id)arg1 shortAnswer:(id)arg2 explanation:(id)arg3 attributionName:(id)arg4 attributionURL:(id)arg5 imageURL:(id)arg6;

@end

