//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class GKBAsyncImageView, NSString;

@interface GKBStickerViewCell : UICollectionViewCell
{
    NSString *_URLString;
    GKBAsyncImageView *_imageView;
    double _length;
    _Bool _hideActivityIndicator;
    double _padding;
}

@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(nonatomic) _Bool hideActivityIndicator; // @synthesize hideActivityIndicator=_hideActivityIndicator;
- (void).cxx_destruct;
- (void)reinitImageView;
- (id)createConstraints;
- (id)stickerURLString;
- (id)stickerImage;
- (void)loadSticker:(id)arg1 withLength:(double)arg2 animated:(_Bool)arg3;

@end

