//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class GKBSportsTeamModel, NSString;

@interface GKBSportsCardModel : GKBCardModel
{
    _Bool _queriedTeamIsHomeTeam;
    GKBSportsTeamModel *_homeTeam;
    GKBSportsTeamModel *_awayTeam;
    NSString *_venueName;
    long long _status;
    NSString *_startTime;
    NSString *_currentTime;
    long long _currentRound;
    NSString *_title;
}

@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) _Bool queriedTeamIsHomeTeam; // @synthesize queriedTeamIsHomeTeam=_queriedTeamIsHomeTeam;
@property(readonly, nonatomic) long long currentRound; // @synthesize currentRound=_currentRound;
@property(readonly, nonatomic) NSString *currentTime; // @synthesize currentTime=_currentTime;
@property(readonly, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
@property(readonly, nonatomic) NSString *venueName; // @synthesize venueName=_venueName;
@property(readonly, nonatomic) GKBSportsTeamModel *awayTeam; // @synthesize awayTeam=_awayTeam;
@property(readonly, nonatomic) GKBSportsTeamModel *homeTeam; // @synthesize homeTeam=_homeTeam;
- (void).cxx_destruct;
- (id)formattedStartTime:(id)arg1;
- (id)ordinalForNumber:(long long)arg1;
- (id)timeText;
- (id)openURL;
- (id)shareText;
- (id)initWithHomeTeam:(id)arg1 awayTeam:(id)arg2 venueName:(id)arg3 status:(long long)arg4 startTime:(id)arg5 currentTime:(id)arg6 currentRound:(long long)arg7 queriedTeamIsHome:(_Bool)arg8;

@end

