//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface GKBStateToKeyMapEntry : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *exclusiveState; // @dynamic exclusiveState;
@property(nonatomic) _Bool hasExclusiveState; // @dynamic hasExclusiveState;
@property(nonatomic) _Bool hasKeyId; // @dynamic hasKeyId;
@property(nonatomic) _Bool hasState; // @dynamic hasState;
@property(retain, nonatomic) NSString *keyId; // @dynamic keyId;
@property(retain, nonatomic) NSString *state; // @dynamic state;

@end

