//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBSearchLoggerUtilities : NSObject
{
}

+ (int)networkStatus:(int)arg1;
+ (int)searchCardUserAction:(long long)arg1;
+ (int)searchCardType:(long long)arg1;
+ (int)searchTab:(long long)arg1;

@end

