//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray;

@interface GKBSoftKeyDef : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PBMutableArray *actionsArray; // @dynamic actionsArray;
@property(retain, nonatomic) NSString *contentDescription; // @dynamic contentDescription;
@property(nonatomic) _Bool hasActionsArray; // @dynamic hasActionsArray;
@property(nonatomic) _Bool hasContentDescription; // @dynamic hasContentDescription;
@property(nonatomic) _Bool hasIconsArray; // @dynamic hasIconsArray;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(nonatomic) _Bool hasLabelsArray; // @dynamic hasLabelsArray;
@property(nonatomic) _Bool hasLayout; // @dynamic hasLayout;
@property(nonatomic) _Bool hasMultiTouch; // @dynamic hasMultiTouch;
@property(nonatomic) _Bool hasSoftkeyItemsArray; // @dynamic hasSoftkeyItemsArray;
@property(nonatomic) _Bool hasStartGesture; // @dynamic hasStartGesture;
@property(retain, nonatomic) PBMutableArray *iconsArray; // @dynamic iconsArray;
@property(retain, nonatomic) NSString *id_p; // @dynamic id_p;
@property(retain, nonatomic) PBMutableArray *labelsArray; // @dynamic labelsArray;
@property(retain, nonatomic) NSString *layout; // @dynamic layout;
@property(nonatomic) _Bool multiTouch; // @dynamic multiTouch;
@property(retain, nonatomic) PBMutableArray *softkeyItemsArray; // @dynamic softkeyItemsArray;
@property(nonatomic) _Bool startGesture; // @dynamic startGesture;

@end

