//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBCardCellDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSArray, NSLayoutConstraint, NSString, QTMActivityIndicator, UICollectionView, UICollectionViewFlowLayout;

@interface GKBSearchResultsView : UIView <GKBCardCellDelegate, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, UICollectionViewDataSource>
{
    NSArray *_searchResultModels;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomConstraint;
    struct CGSize _defaultItemSize;
    UICollectionViewFlowLayout *_defaultFlowLayout;
    UICollectionViewFlowLayout *_imageFlowLayout;
    UICollectionViewFlowLayout *_spreadFlowLayout;
    NSArray *_layoutConstraints;
    QTMActivityIndicator *_activityIndicator;
    long long _searchMode;
    id <GKBSearchResultsViewDelegate> _delegate;
    UICollectionView *_collectionView;
}

@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <GKBSearchResultsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleGKBUIInputViewControllerDidReceiveRotationNotification:(id)arg1;
- (void)snapToContentOffset:(struct CGPoint)arg1;
- (struct CGPoint)targetContentOffsetForItemAtIndexPath:(id)arg1;
- (id)indexPathForContentOffset:(struct CGPoint)arg1;
- (id)selectedIndexPath;
- (id)sanitizeResults:(id)arg1;
- (id)createConstraints;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)invalidateCardModel:(id)arg1;
- (void)setResults:(id)arg1 mode:(long long)arg2 animated:(_Bool)arg3;
@property(readonly, nonatomic) long long currentlySelectedCardIndex;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

