//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBPopupShowable.h"

@class GKBActionDef, GKBSelectorItemView, UINib;

@interface GKBSelectorPopupView : UIView <GKBPopupShowable>
{
    GKBActionDef *_actionDef;
    UIView *_anchorView;
    struct CGPoint _initialTouchPoint;
    unsigned long long _itemCount;
    struct CGSize _estimatedSize;
    UINib *_popupLayoutNib;
    GKBSelectorItemView *_selectedItem;
    long long _firstKeyViewIndex;
    double _contentHeight;
}

@property(readonly, nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
- (void).cxx_destruct;
- (long long)nextViewIndex:(long long)arg1;
- (void)resolveLayout;
@property(readonly, nonatomic) double offsetX;
@property(readonly, nonatomic) struct CGSize estimatedSize;
@property(readonly, nonatomic) _Bool acceptsTouchEvents;
- (void)reset;
- (void)deselectCurrentItem;
- (id)selectItemByIndex:(unsigned long long)arg1;
- (id)handleTouch:(id)arg1;
- (void)layoutSubviews;
- (void)populateContent;
- (id)loadSelectorItemView;
- (void)didMoveToSuperview;
- (id)initializeWithActionDef:(id)arg1 softKeyView:(id)arg2 touchPoint:(struct CGPoint)arg3;

@end

