//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GKBArtExtensionPickerViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class GKBArtExtensionPickerView, GKBErrorMessageLabel, GKBNoFullAccessView, NSArray, NSString, UICollectionView, UICollectionViewFlowLayout;

@interface GKBStickersView : UIView <GKBArtExtensionPickerViewDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout>
{
    double _stickerLength;
    UICollectionViewFlowLayout *_flowLayout;
    NSArray *_layoutConstraints;
    _Bool _isSearching;
    GKBArtExtensionPickerView *_pickerView;
    GKBErrorMessageLabel *_noResultsLabel;
    _Bool _isPortrait;
    NSString *_currentCategory;
    NSArray *_categoryStickers;
    _Bool _isFullAccessEnabled;
    GKBNoFullAccessView *_noFullAccessView;
    id <GKBStickersViewDelegate> _delegate;
    NSArray *_currentStickers;
    UICollectionView *_collectionView;
}

@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSArray *currentStickers; // @synthesize currentStickers=_currentStickers;
@property(nonatomic) __weak id <GKBStickersViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleGKBUIInputViewControllerDidReceiveRotationNotification:(id)arg1;
- (void)pickerView:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
@property(readonly, nonatomic) unsigned long long currentCategoryIndex;
- (void)clearToPrepareForSearch;
- (void)dismissSearchResults;
- (void)showSearchResults:(id)arg1;
- (void)displayStickersForSetIndex:(unsigned long long)arg1;
- (void)stickerCategoryClickedWithIndex:(unsigned long long)arg1;
- (id)createConstraints;
- (void)initializeStickerCategoryButtons:(id)arg1;
- (void)displayFirstStickerSet;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

