//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface GKBSportsTeamModel : NSObject
{
    NSString *_name;
    NSURL *_imageURL;
    NSString *_score;
}

@property(readonly, nonatomic) NSString *score; // @synthesize score=_score;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithName:(id)arg1 imageURL:(id)arg2 score:(id)arg3;

@end

