//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBGIFSearchDelegate.h"

@class GKBContactsDataSource, GKBGIFSearch, GKBSearchResultsFetcher, GTMSessionFetcherService, NSCache, NSString, NSTimer, NSURLSession, Reachability;

@interface GKBSearch : NSObject <GKBGIFSearchDelegate>
{
    NSURLSession *_session;
    GTMSessionFetcherService *_fetcherService;
    NSString *_cachedQuery;
    Reachability *_reachability;
    GKBSearchResultsFetcher *_fetcher;
    GKBGIFSearch *_GIFSearch;
    GKBContactsDataSource *_contactsDataSource;
    CDUnknownBlockType _GIFFetchCompletionBlock;
    CDUnknownBlockType _contactsFetchCompletionBlock;
    id <GKBSearchDelegate> _searchDelegate;
    double _currentFetchIdentifier;
    NSTimer *_timeoutTimer;
    NSCache *_resultsCache;
}

@property(retain, nonatomic) NSCache *resultsCache; // @synthesize resultsCache=_resultsCache;
@property(retain, nonatomic) NSTimer *timeoutTimer; // @synthesize timeoutTimer=_timeoutTimer;
@property(nonatomic) double currentFetchIdentifier; // @synthesize currentFetchIdentifier=_currentFetchIdentifier;
@property(nonatomic) __weak id <GKBSearchDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
- (void).cxx_destruct;
- (void)GIFSearchResultsFound:(id)arg1;
- (void)fetchContactsResultsForQuery:(id)arg1 fetchCompletionBlock:(CDUnknownBlockType)arg2;
- (void)fetchGIFResultsForQuery:(id)arg1 fetchCompletionBlock:(CDUnknownBlockType)arg2;
- (void)fetchImageResultsForQuery:(id)arg1 fetchCompletionBlock:(CDUnknownBlockType)arg2;
- (void)timedOut:(id)arg1;
- (void)invalidateCacheForMode:(long long)arg1;
- (void)emptyCache;
- (void)cancelSearch;
- (void)search:(id)arg1 mode:(long long)arg2 retry:(_Bool)arg3;
- (void)search:(id)arg1 mode:(long long)arg2;
- (void)dealloc;
- (id)init;

@end

