//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBCardModel.h"

@class NSString, NSURL;

@interface GKBTranslationCardModel : GKBCardModel
{
    NSURL *_URL;
    NSString *_title;
    NSString *_translation;
    NSString *_pronunciation;
    NSString *_translatedLanguage;
}

@property(readonly, nonatomic) NSString *translatedLanguage; // @synthesize translatedLanguage=_translatedLanguage;
@property(readonly, nonatomic) NSString *pronunciation; // @synthesize pronunciation=_pronunciation;
@property(readonly, nonatomic) NSString *translation; // @synthesize translation=_translation;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)shareText;
- (id)openURL;
- (id)initWithTitle:(id)arg1 translation:(id)arg2 pronunciation:(id)arg3 translatedLanguage:(id)arg4 URL:(id)arg5;

@end

