//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBKeyboardViewContainerViewDelegate.h"
#import "GKBSoftKeyboardViewDelegate.h"
#import "GKBTouchHandlerDelegate.h"

@class GKBKeyboardDef, GKBKeyboardViewDef, GKBPopupViewManager, GKBSoftKeyboardView, NSMutableArray;

@interface GKBTouchHandlerManager : NSObject <GKBKeyboardViewContainerViewDelegate, GKBTouchHandlerDelegate, GKBSoftKeyboardViewDelegate>
{
    NSMutableArray *_handlers;
    NSMutableArray *_activatedHandlers;
    id <GKBTouchHandler> _targetHandler;
    long long _touchCount;
    _Bool _isFullAccessEnabled;
    id <GKBKeyboardDelegate> _keyboardDelegate;
    id <GKBKeyboard> _keyboard;
    GKBKeyboardDef *_keyboardDef;
    GKBKeyboardViewDef *_keyboardViewDef;
    GKBSoftKeyboardView *_softKeyboardView;
}

@property(nonatomic) __weak GKBSoftKeyboardView *softKeyboardView; // @synthesize softKeyboardView=_softKeyboardView;
@property(readonly, nonatomic) __weak GKBKeyboardViewDef *keyboardViewDef; // @synthesize keyboardViewDef=_keyboardViewDef;
@property(readonly, nonatomic) __weak GKBKeyboardDef *keyboardDef; // @synthesize keyboardDef=_keyboardDef;
@property(readonly, nonatomic) __weak id <GKBKeyboard> keyboard; // @synthesize keyboard=_keyboard;
@property(readonly, nonatomic) __weak id <GKBKeyboardDelegate> keyboardDelegate; // @synthesize keyboardDelegate=_keyboardDelegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)touchHandler:(id)arg1 playFeedbackForKeyData:(id)arg2;
- (id)createMotionEventHandler:(id)arg1;
- (_Bool)shouldActivateHandlerWithInfo:(id)arg1;
- (void)touchHandlerDeclareTargetHandler:(id)arg1;
- (void)touchHandler:(id)arg1 fireEvent:(id)arg2;
- (void)softKeyboardViewLayoutDidChange:(id)arg1;
- (void)keyboardViewHolder:(id)arg1 touched:(id)arg2 withAction:(long long)arg3;
- (void)keyboardStateDidChangeForm:(unsigned long long)arg1 to:(unsigned long long)arg2;
- (void)close;
- (void)deactivate;
- (void)activate;
- (id)initWithKeyboard:(id)arg1 keyboardDelegate:(id)arg2 viewDef:(id)arg3;

@end

