//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBTouchActionCandidate.h"

@interface GKBTouchActionCandidateForUp : GKBTouchActionCandidate
{
    long long _currentState;
}

- (_Bool)shouldShowPopupOnKeyPress;
- (void)revalidate;
- (void)invalidate;
- (long long)handleTouchAction:(long long)arg1;

@end

