//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBEvent, GKBKeyData, GKBPopupViewManager, GKBSoftKeyView, GKBTouchActionBundle;

@protocol GKBTouchActionBundleDelegate
@property(readonly, nonatomic) __weak GKBSoftKeyView *lastTappedView;
@property(readonly, nonatomic) _Bool shouldShowPopupOnKeyPress;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)touchActionBundle:(GKBTouchActionBundle *)arg1 playFeedbackForKeyData:(GKBKeyData *)arg2;
- (void)touchActionBundleClaimFollowingEvents:(GKBTouchActionBundle *)arg1;
- (void)touchActionBundle:(GKBTouchActionBundle *)arg1 fireEvent:(GKBEvent *)arg2;
@end

