//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBActionDef, GKBSoftKeyView, GKBTouchActionCandidate;

@protocol GKBTouchActionCandidateDelegate
@property(readonly, nonatomic) __weak GKBSoftKeyView *lastTappedView;
@property(readonly, nonatomic) _Bool shouldShowPopupOnKeyPress;
- (void)touchActionCandidateHidePopup:(GKBTouchActionCandidate *)arg1;
- (void)touchActionCandidateShowPopup:(GKBTouchActionCandidate *)arg1;
- (void)touchActionCandidateDeclareTargetTouchHandler:(GKBTouchActionCandidate *)arg1;
- (void)touchActionCandidateActivated:(GKBTouchActionCandidate *)arg1;
- (void)touchActionCandidate:(GKBTouchActionCandidate *)arg1 fireActionDef:(GKBActionDef *)arg2;
@end

