//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKBTouchActionCandidate.h"

@interface GKBTouchActionCandidateForSlide : GKBTouchActionCandidate
{
    struct CGPoint _touchDownPoint;
    _Bool _invalidated;
    int _currentAction;
}

- (_Bool)allowMovingOutside;
- (void)revalidate;
- (void)invalidate;
- (int)computeSlideAction:(struct CGPoint)arg1;
- (long long)handleTouchAction:(long long)arg1;

@end

