//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GKBShiftStateHandlerDelegate.h"
#import "GKBTouchActionBundleDelegate.h"
#import "GKBTouchHandler.h"

@class GKBPopupViewManager, GKBShiftStateHandler, GKBSoftKeyView, GKBSoftKeyboardView, NSMutableArray, NSString;

@interface GKBTapTouchHandler : NSObject <GKBTouchHandler, GKBTouchActionBundleDelegate, GKBShiftStateHandlerDelegate>
{
    id <GKBTouchHandlerDelegate> _delegate;
    GKBSoftKeyboardView *_softKeyboardView;
    _Bool _activated;
    NSMutableArray *_touchActionBundles;
    GKBShiftStateHandler *_shiftStateHandler;
    GKBSoftKeyView *_lastTappedView;
}

@property(readonly, nonatomic) __weak GKBSoftKeyView *lastTappedView; // @synthesize lastTappedView=_lastTappedView;
- (void).cxx_destruct;
- (_Bool)isValidInitialBundle:(id)arg1;
- (void)setShiftStateHandler:(id)arg1;
- (void)touchActionBundle:(id)arg1 playFeedbackForKeyData:(id)arg2;
@property(readonly, nonatomic) _Bool shouldShowPopupOnKeyPress;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager;
- (void)touchActionBundleClaimFollowingEvents:(id)arg1;
- (void)touchActionBundle:(id)arg1 fireEvent:(id)arg2;
- (id)actionBundleForTouch:(id)arg1;
- (void)clearEndedTouches:(id)arg1;
- (void)releasePreviousTouchesIfNeeded;
- (id)createTouchActionBundleForTouch:(id)arg1;
- (id)touchActionBundleForTouch:(id)arg1;
- (void)handleTouches:(id)arg1 withAction:(long long)arg2;
- (void)close;
- (void)onSoftKeyboardViewLayout;
- (void)onKeyboardStateChangedTo:(unsigned long long)arg1 from:(unsigned long long)arg2;
- (void)reset;
- (void)deactivate;
- (void)activate;
- (void)setSoftKeyboardView:(id)arg1;
- (void)configureWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

