//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GKBActionDef, GKBSoftKeyView, NSTimer, UITouch;

@interface GKBTouchActionCandidate : NSObject
{
    NSTimer *_repeatedTimer;
    GKBActionDef *_actionDef;
    GKBSoftKeyView *_view;
    id <GKBTouchActionCandidateDelegate> _delegate;
    UITouch *_touch;
}

+ (id)candidateForAction:(id)arg1 onView:(id)arg2 delegate:(id)arg3 touch:(id)arg4;
@property(nonatomic) __weak UITouch *touch; // @synthesize touch=_touch;
@property(nonatomic) __weak id <GKBTouchActionCandidateDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak GKBSoftKeyView *view; // @synthesize view=_view;
@property(nonatomic) __weak GKBActionDef *actionDef; // @synthesize actionDef=_actionDef;
- (void).cxx_destruct;
- (_Bool)allowMovingOutside;
- (_Bool)isTouchInView;
- (void)revalidate;
- (void)invalidate;
- (void)cancelRepeatedKeyData;
- (void)fireRepeatedKeyData;
- (void)fireKeyData;
- (long long)handleTouchAction:(long long)arg1;

@end

