//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GKBUtilities : NSObject
{
}

+ (id)formatJSONString:(id)arg1;
+ (id)lastSentence:(id)arg1;
+ (id)truncateText:(id)arg1 toLength:(unsigned long long)arg2;
+ (id)replaceSpaceWithPlus:(id)arg1;
+ (id)stripHTMLTags:(id)arg1;
+ (void)setData:(id)arg1 forPasteboardType:(id)arg2;
+ (unsigned long long)extractNumberFromText:(id)arg1;
+ (id)JSONDictFromString:(id)arg1;
+ (id)parseSizeParameters:(id)arg1;
+ (id)parseQueryParameters:(id)arg1;
+ (id)URLEncode:(id)arg1;

@end

