//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class GKBCandidate, GKBEvent, GKBInputBundle, NSString;

@protocol GKBUserMetrics
- (void)trackChangeUserPreference;
- (void)trackCommitText:(long long)arg1 sourceLength:(long long)arg2 targetLength:(long long)arg3 inputType:(int)arg4 language:(NSString *)arg5;
- (void)trackSelectCandidate:(GKBCandidate *)arg1 forCommit:(_Bool)arg2 withIndex:(long long)arg3 isDefault:(_Bool)arg4;
- (void)trackSoftKeyEvent:(GKBEvent *)arg1;
- (void)trackSwitchKeyboard:(GKBInputBundle *)arg1 keyboardType:(int)arg2;
- (void)trackChangeInputTraits:(id <UITextInputTraits>)arg1 orientation:(long long)arg2;
- (void)trackViewWillDisappear;
- (void)trackViewWillAppear;
- (_Bool)trackerStarted;
- (void)stopTracking;
- (void)startTracking;
@end

