//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTMSessionFetcherService, NSString;

@interface GKBUserActionLogger : NSObject
{
    NSString *_C2QQuery;
    NSString *_C2QQueryRule;
    unsigned long long _lowMemoryWarningCount;
    long long _minKeyboardStartupLoadTimeMs;
    long long _maxKeyboardStartupLoadTimeMs;
    GTMSessionFetcherService *_gtmService;
    id <GTMFetcherAuthorizationProtocol> _authorization;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <GTMFetcherAuthorizationProtocol> authorization; // @synthesize authorization=_authorization;
- (void).cxx_destruct;
- (id)gboardExtensionWithAppVersion;
- (int)deviceOrientation:(long long)arg1;
- (_Bool)isRegexRule:(id)arg1;
- (void)logQueryPredictionAutosuggestionSelection:(id)arg1;
- (void)logQueryPredictionCardAction:(id)arg1;
- (void)logEvent:(id)arg1 eventType:(unsigned long long)arg2;
- (void)logOpenedSettingsPage:(int)arg1;
- (void)logSearchSettingInteraction:(int)arg1 searchSetting:(int)arg2;
- (void)logKeyboardSettingInteraction:(int)arg1 keyboardSetting:(int)arg2;
- (void)logConv2QueryModelInitializedWithoutFullAccess;
- (void)logConv2QueryModelInitializedWithDownloadTime:(double)arg1 numLocalModelsDownloaded:(unsigned long long)arg2 numLocalModelsTotal:(unsigned long long)arg3 error:(id)arg4;
- (void)logQueryPredictionSelectedFromAutosuggestionView:(id)arg1;
- (void)logQueryPredictionSelected:(id)arg1 rule:(id)arg2;
- (void)logQueryPredictionSuggested:(id)arg1 rule:(id)arg2 trigger:(unsigned long long)arg3;
- (void)logKeyboardStartupLoadTime:(long long)arg1;
- (void)logLowMemoryWarning:(id)arg1 memoryInUse:(long long)arg2;
- (void)logOnboardingEventTimeToInstallMs:(long long)arg1;
- (void)logOnboardingEventClickedButton:(unsigned long long)arg1;
- (void)logGIFResultUserAction:(int)arg1 atIndex:(unsigned long long)arg2 withGIFCategory:(id)arg3 imageHost:(id)arg4;
- (void)logStickerResultUserAction:(int)arg1 atIndex:(unsigned long long)arg2 withStickerCategory:(id)arg3;
- (void)logEmojiResultUserAction:(int)arg1 atIndex:(unsigned long long)arg2 withEmoji:(id)arg3 withEmojiCategory:(id)arg4;
- (void)logArtUserAction:(int)arg1 inTab:(int)arg2;
- (void)logSearchRequestTimedOutInTab:(int)arg1 networkStatus:(int)arg2;
- (void)logSearchRateGboardInteraction:(int)arg1;
- (void)logSearchLocationPermissionResult:(int)arg1;
- (void)logSearchCardUserAction:(int)arg1 atIndex:(unsigned long long)arg2 withCardType:(int)arg3 inTab:(int)arg4 fromConv2Query:(_Bool)arg5;
- (void)logSearchUserAction:(int)arg1 inTab:(int)arg2;
- (void)dealloc;
- (id)init;

@end

