//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GTMSessionFetcherService;

@interface GKBURLShortener : NSObject
{
    GTMSessionFetcherService *_fetcherService;
}

- (void).cxx_destruct;
- (void)shortenURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)fetchURLShortenerResults:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)init;

@end

