//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIInputViewController.h"

#import "GKBExtensionManagerDelegate.h"
#import "GKBInputBundleDelegate.h"

@class GKBExtensionManager, GKBKeyboardTutorialController, GKBKeyboardViewLayoutHelper, GKBPopupViewManager, GKBTextDocumentProxyWrapper, GKBTextInputTraitsImpl, GKBUITextInputDelegateForExtension, NSDate, NSString, UIView;

@interface GKBUIInputViewController : UIInputViewController <GKBInputBundleDelegate, GKBExtensionManagerDelegate>
{
    GKBTextDocumentProxyWrapper *_textDocumentProxyWrapperFromExtension;
    GKBExtensionManager *_extensionManager;
    UIView *_keyboardHeader;
    UIView *_keyboardBody;
    GKBKeyboardViewLayoutHelper *_keyboardViewLayoutHelper;
    GKBTextInputTraitsImpl *_currentTextInputTraits;
    GKBUITextInputDelegateForExtension *_textInputDelegateForExtension;
    struct CGRect _keyboardHeaderBounds;
    struct CGRect _keyboardBodyBounds;
    NSString *_currentUserInputContext;
    NSDate *_lastTimeQueryPredictionTriggered;
    double _startTime;
    long long _elapsedTimeMs;
    _Bool _elapsedTimeSet;
    NSString *_currentQueryPredictionSuggestion;
    GKBKeyboardTutorialController *_tutorialController;
    GKBPopupViewManager *_popupViewManager;
    id <GKBUserMetrics> _userMetrics;
    GKBTextDocumentProxyWrapper *_textDocumentProxyWrapper;
}

@property(retain, nonatomic) GKBTextDocumentProxyWrapper *textDocumentProxyWrapper; // @synthesize textDocumentProxyWrapper=_textDocumentProxyWrapper;
@property(retain, nonatomic) id <GKBUserMetrics> userMetrics; // @synthesize userMetrics=_userMetrics;
@property(readonly, nonatomic) GKBPopupViewManager *popupViewManager; // @synthesize popupViewManager=_popupViewManager;
- (void).cxx_destruct;
- (id)queryPredictionTooltipMessage;
- (void)handleGKBQueryPredictionWillShowSuggestedQueryTooltip:(id)arg1;
- (void)handleGKBCircleViewDidFinishPulsingAnimation:(id)arg1;
- (void)handleGKBQueryPredictionWillShowSuggestedQuery:(id)arg1;
- (void)stopTutorial;
- (void)showTutorial;
- (void)initializeExtensions;
- (void)activateCurrentInputBundleWithKeyboardType:(int *)arg1;
- (void)extensionTextDidChange;
- (void)checkExpectedCursorMove;
- (void)textDidChange:(id)arg1;
- (void)createInputBundlesIfNeeded;
- (void)moveCursorWithOffset:(long long)arg1;
- (void)hideKeyboard;
- (void)inputBundleSwitchToOtherKeyboard;
- (void)inputBundleCurrentLanguageDidChange;
- (void)inputBundle:(id)arg1 setKeyboardView:(id)arg2 forType:(int)arg3;
- (_Bool)hasText;
- (id)textAfterCursor:(long long)arg1;
- (id)textBeforeCursor:(long long)arg1;
- (void)inputBundle:(id)arg1 didFindTextSuggestions:(id)arg2;
- (void)inputBundleDeleteBackward:(id)arg1 isWord:(_Bool)arg2;
- (void)inputBundle:(id)arg1 updateTextWithBeforeComposingRangeLength:(unsigned long long)arg2 preComposingRangeText:(id)arg3 composingText:(id)arg4;
- (void)inputBundle:(id)arg1 setComposingRangeWithLength:(unsigned long long)arg2;
- (void)inputBundle:(id)arg1 commitText:(id)arg2;
- (void)inputBundle:(id)arg1 setComposingText:(id)arg2;
- (struct CGSize)intrinsicSizeForExtension:(id)arg1 inPosition:(long long)arg2;
- (void)extension:(id)arg1 requestTextSuggestionsWithMaxCount:(unsigned long long)arg2;
- (void)extensionDeactivated:(id)arg1;
- (void)extensionBackspaceUp:(id)arg1;
- (void)extensionBackspaceDown:(id)arg1;
- (void)extension:(id)arg1 setTextDocumentProxy:(id)arg2;
- (void)extension:(id)arg1 openURL:(id)arg2;
- (void)extension:(id)arg1 insertText:(id)arg2;
- (void)extension:(id)arg1 removeHeaderViewController:(id)arg2;
- (void)extension:(id)arg1 attachHeaderViewController:(id)arg2;
- (void)extension:(id)arg1 hideView:(id)arg2;
- (void)extension:(id)arg1 showView:(id)arg2 inPosition:(long long)arg3;
@property(readonly, nonatomic) NSString *textBeforeCursorInApp;
@property(readonly, nonatomic) NSString *textAfterCursorInApp;
- (void)didReceiveMemoryWarning;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)activateExtensionWithName:(id)arg1 data:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

