//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface GKBWeatherDailyForecast : NSObject
{
    NSString *_day;
    NSURL *_conditionImageURL;
    long long _highTemperature;
    long long _lowTemperature;
}

@property(readonly, nonatomic) long long lowTemperature; // @synthesize lowTemperature=_lowTemperature;
@property(readonly, nonatomic) long long highTemperature; // @synthesize highTemperature=_highTemperature;
@property(readonly, nonatomic) NSURL *conditionImageURL; // @synthesize conditionImageURL=_conditionImageURL;
@property(readonly, nonatomic) NSString *day; // @synthesize day=_day;
- (void).cxx_destruct;
- (id)initWithDay:(id)arg1 conditionImageURL:(id)arg2 highTemperature:(long long)arg3 lowTemperature:(long long)arg4;

@end

