//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GMAVCRGoogleRatingsAndReviews, GMAVCRRatingsAndReviews_DisplayHint, GMAVCRThirdPartyRatingsAndReviewsList;

@interface GMAVCRRatingsAndReviews : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GMAVCRRatingsAndReviews_DisplayHint *displayHint; // @dynamic displayHint;
@property(retain, nonatomic) GMAVCRGoogleRatingsAndReviews *google; // @dynamic google;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(nonatomic) _Bool hasGoogle; // @dynamic hasGoogle;
@property(nonatomic) _Bool hasThirdPartyList; // @dynamic hasThirdPartyList;
@property(retain, nonatomic) GMAVCRThirdPartyRatingsAndReviewsList *thirdPartyList; // @dynamic thirdPartyList;

@end

