//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GMAVCRAggregateRating_DisplayHint;

@interface GMAVCRThirdPartyRatingsAndReviewsList_DisplayHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GMAVCRAggregateRating_DisplayHint *defaultAggregateRatingHint; // @dynamic defaultAggregateRatingHint;
@property(nonatomic) _Bool hasDefaultAggregateRatingHint; // @dynamic hasDefaultAggregateRatingHint;

@end

