//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Color, GMAVCRStarRatingDisplayHint, GMAVCRTextRatingDisplayHint;

@interface GMAVCRAggregateRating_DisplayHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Color *color; // @dynamic color;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) _Bool hasStars; // @dynamic hasStars;
@property(nonatomic) _Bool hasText; // @dynamic hasText;
@property(retain, nonatomic) GMAVCRStarRatingDisplayHint *stars; // @dynamic stars;
@property(retain, nonatomic) GMAVCRTextRatingDisplayHint *text; // @dynamic text;

@end

