//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Color, GMAVCRTextRatingCustomFormat, GPBBoolValue;

@interface GMAVCRTextRatingDisplayHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Color *color; // @dynamic color;
@property(retain, nonatomic) GMAVCRTextRatingCustomFormat *custom; // @dynamic custom;
@property(retain, nonatomic) GPBBoolValue *enabled; // @dynamic enabled;
@property(readonly, nonatomic) int formatOneOfCase; // @dynamic formatOneOfCase;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) _Bool hasEnabled; // @dynamic hasEnabled;

@end

