//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GOOBottomSheetControllerDelegate.h"
#import "GOOPopoverViewControllerDelegate.h"

@class GOOActionSheetDialogViewController, NSArray, NSMutableArray, NSString, UIView, UIViewController;

@interface GOOActionSheetController : NSObject <GOOBottomSheetControllerDelegate, GOOPopoverViewControllerDelegate>
{
    UIViewController *_containerViewController;
    GOOActionSheetDialogViewController *_actionsController;
    NSMutableArray *_actions;
    id <GOOActionSheetControllerDelegate> _delegate;
    unsigned long long _permittedArrowDirections;
    unsigned long long _anchorCorner;
    UIView *_sourceView;
    struct CGSize _offset;
}

+ (id)actionSheetControllerWithMessage:(id)arg1;
+ (id)actionSheetController;
@property(nonatomic) struct CGSize offset; // @synthesize offset=_offset;
@property(retain, nonatomic) UIView *sourceView; // @synthesize sourceView=_sourceView;
@property(nonatomic) unsigned long long anchorCorner; // @synthesize anchorCorner=_anchorCorner;
@property(nonatomic) unsigned long long permittedArrowDirections; // @synthesize permittedArrowDirections=_permittedArrowDirections;
@property(nonatomic) __weak id <GOOActionSheetControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)popoverViewControllerDidCancel:(id)arg1;
- (void)bottomSheetControllerDidCancel:(id)arg1;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)dismissWithAction:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismiss;
- (id)bestGuessWindow;
- (void)present;
- (void)presentFromViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addAction:(id)arg1;
@property(readonly, nonatomic) NSArray *actions;
- (id)popoverViewController;
- (id)initWithMessage:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

