//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface GOODimmingBackgroundView : UIView
{
    unsigned long long _referenceCount;
}

@property(nonatomic) unsigned long long referenceCount; // @synthesize referenceCount=_referenceCount;
- (void)removeReference;
- (void)addReference;
- (id)initWithFrame:(struct CGRect)arg1;

@end

