//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLink, NSMutableArray, NSString;

@interface GooglePlusResult_Post : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GWPLink *author; // @dynamic author;
@property(nonatomic) _Bool hasAuthor; // @dynamic hasAuthor;
@property(nonatomic) _Bool hasLink; // @dynamic hasLink;
@property(nonatomic) _Bool hasSnippet; // @dynamic hasSnippet;
@property(nonatomic) _Bool hasTimestamp; // @dynamic hasTimestamp;
@property(retain, nonatomic) GWPLink *link; // @dynamic link;
@property(copy, nonatomic) NSString *snippet; // @dynamic snippet;
@property(retain, nonatomic) NSMutableArray *thumbnailsArray; // @dynamic thumbnailsArray;
@property(readonly, nonatomic) unsigned long long thumbnailsArray_Count; // @dynamic thumbnailsArray_Count;
@property(copy, nonatomic) NSString *timestamp; // @dynamic timestamp;

@end

