//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "GOOViewControllerAnimatedTransitioning.h"
#import "UIGestureRecognizerDelegate.h"

@class GOOPopoverView, GOOPresentationAnimationShim, NSString, UIView;

@interface GOOPopoverViewController : UIViewController <GOOViewControllerAnimatedTransitioning, UIGestureRecognizerDelegate>
{
    UIViewController *_contentViewController;
    UIView *_sourceView;
    unsigned long long _menuAnchor;
    unsigned long long _permittedArrowDirections;
    id <GOOPopoverViewControllerDelegate> _delegate;
    GOOPopoverView *_popoverView;
    UIView *_innerContainer;
    GOOPresentationAnimationShim *_transitionAnimationShim;
    struct CGRect _sourceRect;
}

+ (void)initialize;
@property(retain, nonatomic) GOOPresentationAnimationShim *transitionAnimationShim; // @synthesize transitionAnimationShim=_transitionAnimationShim;
@property(retain, nonatomic) UIView *innerContainer; // @synthesize innerContainer=_innerContainer;
@property(retain, nonatomic) GOOPopoverView *popoverView; // @synthesize popoverView=_popoverView;
@property(nonatomic) __weak id <GOOPopoverViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long permittedArrowDirections; // @synthesize permittedArrowDirections=_permittedArrowDirections;
@property(nonatomic) unsigned long long menuAnchor; // @synthesize menuAnchor=_menuAnchor;
@property(nonatomic) struct CGRect sourceRect; // @synthesize sourceRect=_sourceRect;
@property(retain, nonatomic) UIView *sourceView; // @synthesize sourceView=_sourceView;
@property(readonly, nonatomic) UIViewController *contentViewController; // @synthesize contentViewController=_contentViewController;
- (void).cxx_destruct;
- (void)updateContainerView;
- (void)positionPopover;
- (void)installPopoverInView:(id)arg1;
- (void)updateContentSize;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)accessibilityPerformEscape;
- (void)handleTap:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)presentationControllerForPresentingViewController:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)viewWillLayoutSubviews;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (id)initWithContentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

