//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GOOResources.h"

@interface GOOResources (Core)
- (id)accessibilityNavigateBackString;
- (struct UIEdgeInsets)cardContentPadding;
- (id)highlightedTextColor;
- (id)editableTextColor;
- (id)destructiveLabelColor;
- (id)actionColor;
- (id)lightTextColor;
- (id)mediumTextColor;
- (id)darkTextColor;
- (id)backgroundColor;
- (double)minimumCardHeaderFontSize;
- (id)cardHeaderFont;
- (id)cardDetailTextFont;
- (id)cardTextFont;
- (id)actionButtonFont;
- (id)darkButtonBackgroundImageForState:(unsigned long long)arg1;
- (id)lightButtonBackgroundImageForState:(unsigned long long)arg1;
- (id)redButtonBackgroundImageForState:(unsigned long long)arg1;
- (id)blueButtonBackgroundImageForState:(unsigned long long)arg1;
- (id)buttonBackgroundImageNamed:(id)arg1;
- (id)fadedVerticalDividerImage;
- (id)checkmarkImage;
- (id)cellDisclosureAccessoryImage;
- (id)cellDividerImage;
- (id)cellBackgroundSelectedDarkImage;
- (id)checkboxImageForState:(unsigned long long)arg1;
- (id)highlightedBackgroundForHeight:(double)arg1;
- (id)coreStringForID:(int)arg1;
- (id)coreImageWithResourceName:(id)arg1;
@end

