//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GPCDeviceInfo : NSObject
{
}

+ (_Bool)isRTL;
+ (_Bool)havePhotosAccess;
+ (id)deviceCPUs;
+ (unsigned long long)deviceMemoryClass;
+ (id)freeMemory;
+ (id)usedMemory;
+ (unsigned long long)userInterfaceIdiom;
+ (_Bool)isPad;
+ (_Bool)isRetinaHD;
+ (_Bool)isRetina;
+ (id)macAddress;
+ (id)systemInfoByName:(id)arg1;
+ (id)webViewUserAgent;
+ (id)userAgent;
+ (id)userAgentSuffix;
+ (id)userAgentEncoding;
+ (id)userAgentPrefix;
+ (id)localeName;
+ (struct CGSize)screenSize;
+ (_Bool)isIOS9dot1orLater;
+ (_Bool)isIOS9orLater;
+ (_Bool)isIOS8dot2orLater;
+ (_Bool)isIOS8orLater;
+ (_Bool)isIOS7orLater;
+ (_Bool)isIOS6;
+ (_Bool)hasFrontCamera;
+ (_Bool)hasBackCamera;
+ (id)bundleVersion;
+ (id)bundleId;
+ (id)buildVersion;
- (id)init;

@end

