//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRPCOperation.h"

@interface GRPCOpRecvMessage : GRPCOperation
{
    struct grpc_byte_buffer *_receivedMessage;
}

- (id)initWithHandler:(CDUnknownBlockType)arg1;
- (id)init;

@end

