//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRPCCall.h"

@interface GRPCCall (Tests)
+ (void)useInsecureConnectionsForHost:(id)arg1;
+ (void)useTestCertsPath:(id)arg1 testName:(id)arg2 forHost:(id)arg3;
@end

