//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRPCOperation.h"

@interface GRPCOpRecvMetadata : GRPCOperation
{
    CDStruct_6f820e53 _headers;
}

- (void)dealloc;
- (id)initWithHandler:(CDUnknownBlockType)arg1;
- (id)init;

@end

