//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GRPCOperation : NSObject
{
    struct grpc_op _op;
    CDUnknownBlockType _handler;
}

@property(readonly, nonatomic) struct grpc_op op; // @synthesize op=_op;
- (void).cxx_destruct;
- (void)finish;

@end

