//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRXWriter.h"

#import "GRXWriteable.h"

@class GRPCConnectivityMonitor, GRPCRequestHeaders, GRPCWrappedCall, GRXConcurrentWriteable, NSDictionary, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface GRPCCall : GRXWriter <GRXWriteable>
{
    NSObject<OS_dispatch_queue> *_callQueue;
    NSString *_host;
    NSString *_path;
    GRPCWrappedCall *_wrappedCall;
    long long _callAlreadyInvoked;
    GRPCConnectivityMonitor *_connectivityMonitor;
    GRXConcurrentWriteable *_responseWriteable;
    GRXWriter *_requestWriter;
    GRPCCall *_retainSelf;
    GRPCRequestHeaders *_requestHeaders;
    long long _state;
    NSDictionary *_responseHeaders;
    NSDictionary *_responseTrailers;
}

@property(retain) NSDictionary *responseTrailers; // @synthesize responseTrailers=_responseTrailers;
@property(retain) NSDictionary *responseHeaders; // @synthesize responseHeaders=_responseHeaders;
@property(readonly) NSMutableDictionary *requestHeaders; // @synthesize requestHeaders=_requestHeaders;
- (long long)state;
- (void).cxx_destruct;
- (void)setState:(long long)arg1;
- (void)startWithWriteable:(id)arg1;
- (void)invokeCall;
- (void)invokeCallWithHeadersHandler:(CDUnknownBlockType)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)writesFinishedWithError:(id)arg1;
- (void)finishRequestWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)writeValue:(id)arg1;
- (void)writeMessage:(id)arg1 withErrorHandler:(CDUnknownBlockType)arg2;
- (void)sendHeaders:(id)arg1;
- (void)startNextRead;
- (void)startReadWithHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)cancel;
- (void)cancelCall;
- (void)finishWithError:(id)arg1;
- (id)initWithHost:(id)arg1 path:(id)arg2 requestsWriter:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

