//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GRPCReachabilityFlags : NSObject
{
    unsigned int _flags;
}

+ (id)flagsWithFlags:(unsigned int)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
@property(readonly, nonatomic) _Bool isHostReachable;
@property(readonly, nonatomic) _Bool isDirect;
@property(readonly, nonatomic) _Bool isLocalAddress;
@property(readonly, nonatomic) _Bool connectionOnDemand;
@property(readonly, nonatomic) _Bool interventionRequired;
@property(readonly, nonatomic) _Bool connectionOnTraffic;
@property(readonly, nonatomic) _Bool connectionRequired;
@property(readonly, nonatomic) _Bool transientConnection;
@property(readonly, nonatomic) _Bool reachable;
@property(readonly, nonatomic) _Bool isCell;
- (id)initWithFlags:(unsigned int)arg1;

@end

