//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GRPCChannel, NSString;

@interface GRPCHost : NSObject
{
    GRPCChannel *_channel;
    _Bool _secure;
    NSString *_address;
    NSString *_userAgentPrefix;
    NSString *_pathToCertificates;
    NSString *_hostNameOverride;
}

+ (id)hostWithAddress:(id)arg1;
@property(copy, nonatomic) NSString *hostNameOverride; // @synthesize hostNameOverride=_hostNameOverride;
@property(copy, nonatomic) NSString *pathToCertificates; // @synthesize pathToCertificates=_pathToCertificates;
@property(nonatomic, getter=isSecure) _Bool secure; // @synthesize secure=_secure;
@property(copy, nonatomic) NSString *userAgentPrefix; // @synthesize userAgentPrefix=_userAgentPrefix;
@property(readonly, nonatomic) NSString *address; // @synthesize address=_address;
- (void).cxx_destruct;
- (void)disconnect;
- (id)hostName;
- (id)newChannel;
- (id)channelArgs;
- (struct grpc_call *)unmanagedCallWithPath:(id)arg1 completionQueue:(id)arg2;
- (id)initWithAddress:(id)arg1;

@end

