//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRXWriter.h"

#import "GRXWriteable.h"

@class NSError, NSMutableArray, NSString;

@interface GRXBufferedPipe : GRXWriter <GRXWriteable>
{
    id <GRXWriteable> _writeable;
    NSMutableArray *_queue;
    _Bool _inputIsFinished;
    NSError *_errorOrNil;
    long long _state;
}

+ (id)pipe;
- (long long)state;
- (void).cxx_destruct;
- (void)finishWithError:(id)arg1;
- (void)startWithWriteable:(id)arg1;
- (void)setState:(long long)arg1;
- (void)writesFinishedWithError:(id)arg1;
- (void)writeValue:(id)arg1;
- (_Bool)shouldFastForward;
- (void)writeBufferUntilPausedOrStopped;
- (id)popValue;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

