//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GRXForwardingWriter.h"

@interface GRXMappingWriter : GRXForwardingWriter
{
    CDUnknownBlockType _map;
}

- (void).cxx_destruct;
- (void)writeValue:(id)arg1;
- (id)initWithWriter:(id)arg1 map:(CDUnknownBlockType)arg2;
- (id)initWithWriter:(id)arg1;

@end

