//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GRXWriter : NSObject
{
    long long _state;
}

@property(nonatomic) long long state; // @synthesize state=_state;
- (void)finishWithError:(id)arg1;
- (void)startWithWriteable:(id)arg1;

@end

