//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface GSACCategoryInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *categoryArray; // @dynamic categoryArray;
@property(readonly, nonatomic) unsigned long long categoryArray_Count; // @dynamic categoryArray_Count;

@end

