//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class AppLink, Url;

@interface GSAMMapLink : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) AppLink *appLink; // @dynamic appLink;
@property(nonatomic) _Bool hasAppLink; // @dynamic hasAppLink;
@property(nonatomic) _Bool hasWebURL; // @dynamic hasWebURL;
@property(retain, nonatomic) Url *webURL; // @dynamic webURL;

@end

