//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GSAMMapLink, GSAMViewport, NSMutableArray, NSString;

@interface GSAMStaticMap : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHeight; // @dynamic hasHeight;
@property(nonatomic) _Bool hasLabel; // @dynamic hasLabel;
@property(nonatomic) _Bool hasScale; // @dynamic hasScale;
@property(nonatomic) _Bool hasTargetLink; // @dynamic hasTargetLink;
@property(nonatomic) _Bool hasViewport; // @dynamic hasViewport;
@property(nonatomic) _Bool hasWidth; // @dynamic hasWidth;
@property(nonatomic) int height; // @dynamic height;
@property(copy, nonatomic) NSString *label; // @dynamic label;
@property(retain, nonatomic) NSMutableArray *mapLayerArray; // @dynamic mapLayerArray;
@property(readonly, nonatomic) unsigned long long mapLayerArray_Count; // @dynamic mapLayerArray_Count;
@property(nonatomic) int scale; // @dynamic scale;
@property(retain, nonatomic) GSAMMapLink *targetLink; // @dynamic targetLink;
@property(retain, nonatomic) GSAMViewport *viewport; // @dynamic viewport;
@property(nonatomic) int width; // @dynamic width;

@end

