//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GSAOCurrentStatus, GSAOHoursSchedule;

@interface GSAOOpeningHours : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GSAOCurrentStatus *currentStatus; // @dynamic currentStatus;
@property(nonatomic) _Bool hasCurrentStatus; // @dynamic hasCurrentStatus;
@property(nonatomic) _Bool hasSchedule; // @dynamic hasSchedule;
@property(retain, nonatomic) GSAOHoursSchedule *schedule; // @dynamic schedule;

@end

