//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GSACCategoryInfo, GSAMMapLink, GSAMMaps, GSAOOpeningHours, GSAPExistence, GSAPFeatureId, GSAPLocation, GSAPPrice, NSMutableArray;

@interface GSAPPlace : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) GSACCategoryInfo *category; // @dynamic category;
@property(retain, nonatomic) GSAMMapLink *directionsLink; // @dynamic directionsLink;
@property(retain, nonatomic) GSAPExistence *existence; // @dynamic existence;
@property(retain, nonatomic) GSAPFeatureId *featureId; // @dynamic featureId;
@property(retain, nonatomic) NSMutableArray *formattedAddressArray; // @dynamic formattedAddressArray;
@property(readonly, nonatomic) unsigned long long formattedAddressArray_Count; // @dynamic formattedAddressArray_Count;
@property(nonatomic) _Bool hasCategory; // @dynamic hasCategory;
@property(nonatomic) _Bool hasDirectionsLink; // @dynamic hasDirectionsLink;
@property(nonatomic) _Bool hasExistence; // @dynamic hasExistence;
@property(nonatomic) _Bool hasFeatureId; // @dynamic hasFeatureId;
@property(nonatomic) _Bool hasLocation; // @dynamic hasLocation;
@property(nonatomic) _Bool hasMaps; // @dynamic hasMaps;
@property(nonatomic) _Bool hasOpeningHours; // @dynamic hasOpeningHours;
@property(nonatomic) _Bool hasPrice; // @dynamic hasPrice;
@property(retain, nonatomic) GSAPLocation *location; // @dynamic location;
@property(retain, nonatomic) GSAMMaps *maps; // @dynamic maps;
@property(retain, nonatomic) GSAOOpeningHours *openingHours; // @dynamic openingHours;
@property(retain, nonatomic) NSMutableArray *phoneNumberArray; // @dynamic phoneNumberArray;
@property(readonly, nonatomic) unsigned long long phoneNumberArray_Count; // @dynamic phoneNumberArray_Count;
@property(retain, nonatomic) GSAPPrice *price; // @dynamic price;

@end

