//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GSAIQueryInterpretation, GSAMMaps, NSMutableArray;

@interface GSAPGeoResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *entityArray; // @dynamic entityArray;
@property(readonly, nonatomic) unsigned long long entityArray_Count; // @dynamic entityArray_Count;
@property(nonatomic) _Bool hasInterpretation; // @dynamic hasInterpretation;
@property(nonatomic) _Bool hasMaps; // @dynamic hasMaps;
@property(retain, nonatomic) GSAIQueryInterpretation *interpretation; // @dynamic interpretation;
@property(retain, nonatomic) GSAMMaps *maps; // @dynamic maps;

@end

