//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface GSAPLocation : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *formattedDistanceFromDevice; // @dynamic formattedDistanceFromDevice;
@property(nonatomic) _Bool hasFormattedDistanceFromDevice; // @dynamic hasFormattedDistanceFromDevice;
@property(nonatomic) _Bool hasIsUserCurrentLocation; // @dynamic hasIsUserCurrentLocation;
@property(nonatomic) _Bool isUserCurrentLocation; // @dynamic isUserCurrentLocation;

@end

