//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface GTPTimeOfDay : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int hours; // @dynamic hours;
@property(nonatomic) int minutes; // @dynamic minutes;
@property(nonatomic) int nanos; // @dynamic nanos;
@property(nonatomic) int seconds; // @dynamic seconds;

@end

