//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLocalizedString, NSMutableArray, NSString;

@interface GWPLink : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *URL; // @dynamic URL;
@property(retain, nonatomic) NSMutableArray *allowedLocalesArray; // @dynamic allowedLocalesArray;
@property(readonly, nonatomic) unsigned long long allowedLocalesArray_Count; // @dynamic allowedLocalesArray_Count;
@property(retain, nonatomic) GWPLocalizedString *anchor; // @dynamic anchor;
@property(nonatomic) _Bool hasAnchor; // @dynamic hasAnchor;
@property(nonatomic) _Bool hasInternal; // @dynamic hasInternal;
@property(nonatomic) _Bool hasTooltip; // @dynamic hasTooltip;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(nonatomic) _Bool hasVisualElementId; // @dynamic hasVisualElementId;
@property(nonatomic) _Bool internal; // @dynamic internal;
@property(retain, nonatomic) NSMutableArray *queryPartsArray; // @dynamic queryPartsArray;
@property(readonly, nonatomic) unsigned long long queryPartsArray_Count; // @dynamic queryPartsArray_Count;
@property(retain, nonatomic) NSMutableArray *restrictedLocalesArray; // @dynamic restrictedLocalesArray;
@property(readonly, nonatomic) unsigned long long restrictedLocalesArray_Count; // @dynamic restrictedLocalesArray_Count;
@property(retain, nonatomic) GWPLocalizedString *tooltip; // @dynamic tooltip;
@property(nonatomic) int visualElementId; // @dynamic visualElementId;

@end

