//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableDictionary;

@interface GWSHeaderContext : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableDictionary *headers; // @dynamic headers;
@property(readonly, nonatomic) unsigned long long headers_Count; // @dynamic headers_Count;

@end

