//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LOCULocationDescriptorSet, NSString;

@interface GWSLocalizationContext : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) LOCULocationDescriptorSet *clientLocationInputs; // @dynamic clientLocationInputs;
@property(copy, nonatomic) NSString *countryCode; // @dynamic countryCode;
@property(nonatomic) _Bool hasCountryCode; // @dynamic hasCountryCode;
@property(nonatomic) _Bool hasLanguageCode; // @dynamic hasLanguageCode;
@property(copy, nonatomic) NSString *languageCode; // @dynamic languageCode;
@property(readonly, nonatomic) int locationOneOfCase; // @dynamic locationOneOfCase;

@end

