//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLink;

@interface HotTrendsOlympicsResult_SearchTerm : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHotnessLevel; // @dynamic hasHotnessLevel;
@property(nonatomic) _Bool hasRefinementLink; // @dynamic hasRefinementLink;
@property(nonatomic) _Bool hasVolumeBucket; // @dynamic hasVolumeBucket;
@property(nonatomic) int hotnessLevel; // @dynamic hotnessLevel;
@property(retain, nonatomic) GWPLink *refinementLink; // @dynamic refinementLink;
@property(nonatomic) long long volumeBucket; // @dynamic volumeBucket;

@end

