//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, Url;

@interface ImageResults : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool expandedImageBlock; // @dynamic expandedImageBlock;
@property(nonatomic) _Bool hasExpandedImageBlock; // @dynamic hasExpandedImageBlock;
@property(nonatomic) _Bool hasJsonMetadata; // @dynamic hasJsonMetadata;
@property(nonatomic) _Bool hasMoreURL; // @dynamic hasMoreURL;
@property(copy, nonatomic) NSString *jsonMetadata; // @dynamic jsonMetadata;
@property(retain, nonatomic) Url *moreURL; // @dynamic moreURL;
@property(retain, nonatomic) NSMutableArray *resultArray; // @dynamic resultArray;
@property(readonly, nonatomic) unsigned long long resultArray_Count; // @dynamic resultArray_Count;

@end

