//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, ScalableImage;

@interface ImageSource : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasScalable; // @dynamic hasScalable;
@property(retain, nonatomic) NSMutableArray *rasterArray; // @dynamic rasterArray;
@property(readonly, nonatomic) unsigned long long rasterArray_Count; // @dynamic rasterArray_Count;
@property(retain, nonatomic) ScalableImage *scalable; // @dynamic scalable;

@end

