//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Image2, ImageAttribution, NSString, Thumbnail, Url;

@interface ImageResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) ImageAttribution *attribution; // @dynamic attribution;
@property(retain, nonatomic) Url *coupledURL; // @dynamic coupledURL;
@property(copy, nonatomic) NSString *docid; // @dynamic docid;
@property(nonatomic) _Bool hasAttribution; // @dynamic hasAttribution;
@property(nonatomic) _Bool hasCoupledURL; // @dynamic hasCoupledURL;
@property(nonatomic) _Bool hasDocid; // @dynamic hasDocid;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasResultURL; // @dynamic hasResultURL;
@property(nonatomic) _Bool hasThumbnail; // @dynamic hasThumbnail;
@property(retain, nonatomic) Image2 *image; // @dynamic image;
@property(retain, nonatomic) Url *resultURL; // @dynamic resultURL;
@property(retain, nonatomic) Thumbnail *thumbnail; // @dynamic thumbnail;

@end

