//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface JsClientInfo : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSString *country; // @dynamic country;
@property(nonatomic) int deviceType; // @dynamic deviceType;
@property(nonatomic) _Bool hasCountry; // @dynamic hasCountry;
@property(nonatomic) _Bool hasDeviceType; // @dynamic hasDeviceType;
@property(nonatomic) _Bool hasLocale; // @dynamic hasLocale;
@property(nonatomic) _Bool hasOs; // @dynamic hasOs;
@property(nonatomic) _Bool hasOsVersion; // @dynamic hasOsVersion;
@property(retain, nonatomic) NSString *locale; // @dynamic locale;
@property(retain, nonatomic) NSString *os; // @dynamic os;
@property(retain, nonatomic) NSString *osVersion; // @dynamic osVersion;

@end

