//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class PBMutableArray;

@interface KeyboardSettings : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool autoCapitalization; // @dynamic autoCapitalization;
@property(nonatomic) _Bool autoCorrectEnabled; // @dynamic autoCorrectEnabled;
@property(nonatomic) _Bool autoSpaceEnabled; // @dynamic autoSpaceEnabled;
@property(nonatomic) _Bool blockOffensiveWords; // @dynamic blockOffensiveWords;
@property(nonatomic) _Bool chinesePredictionEnabled; // @dynamic chinesePredictionEnabled;
@property(nonatomic) _Bool dictUpdateEnabled; // @dynamic dictUpdateEnabled;
@property(nonatomic) _Bool gestureInputEnabled; // @dynamic gestureInputEnabled;
@property(nonatomic) _Bool gestureTrailEnabled; // @dynamic gestureTrailEnabled;
@property(nonatomic) int handwritingSpeed; // @dynamic handwritingSpeed;
@property(nonatomic) int handwritingStrokeWidthScale; // @dynamic handwritingStrokeWidthScale;
@property(nonatomic) _Bool hasAutoCapitalization; // @dynamic hasAutoCapitalization;
@property(nonatomic) _Bool hasAutoCorrectEnabled; // @dynamic hasAutoCorrectEnabled;
@property(nonatomic) _Bool hasAutoSpaceEnabled; // @dynamic hasAutoSpaceEnabled;
@property(nonatomic) _Bool hasBlockOffensiveWords; // @dynamic hasBlockOffensiveWords;
@property(nonatomic) _Bool hasChinesePredictionEnabled; // @dynamic hasChinesePredictionEnabled;
@property(nonatomic) _Bool hasDictUpdateEnabled; // @dynamic hasDictUpdateEnabled;
@property(nonatomic) _Bool hasGestureInputEnabled; // @dynamic hasGestureInputEnabled;
@property(nonatomic) _Bool hasGestureTrailEnabled; // @dynamic hasGestureTrailEnabled;
@property(nonatomic) _Bool hasHandwritingSpeed; // @dynamic hasHandwritingSpeed;
@property(nonatomic) _Bool hasHandwritingStrokeWidthScale; // @dynamic hasHandwritingStrokeWidthScale;
@property(nonatomic) _Bool hasIncludeOtherImesInLanguageSwitchList; // @dynamic hasIncludeOtherImesInLanguageSwitchList;
@property(nonatomic) _Bool hasKeyboardHeightInPercentage; // @dynamic hasKeyboardHeightInPercentage;
@property(nonatomic) _Bool hasLongPressDelay; // @dynamic hasLongPressDelay;
@property(nonatomic) _Bool hasOptInHandwritingFeedback; // @dynamic hasOptInHandwritingFeedback;
@property(nonatomic) _Bool hasOptInUserMetrics; // @dynamic hasOptInUserMetrics;
@property(nonatomic) _Bool hasPersonalizedSuggestions; // @dynamic hasPersonalizedSuggestions;
@property(nonatomic) _Bool hasPhraseGestureEnabled; // @dynamic hasPhraseGestureEnabled;
@property(nonatomic) _Bool hasPopupOnKeypress; // @dynamic hasPopupOnKeypress;
@property(nonatomic) _Bool hasPredictionEnabled; // @dynamic hasPredictionEnabled;
@property(nonatomic) _Bool hasScTcConversion; // @dynamic hasScTcConversion;
@property(nonatomic) _Bool hasShowLanguageSwitchKey; // @dynamic hasShowLanguageSwitchKey;
@property(nonatomic) _Bool hasSoundOnKeypress; // @dynamic hasSoundOnKeypress;
@property(nonatomic) _Bool hasSpellCorrectionEnabled; // @dynamic hasSpellCorrectionEnabled;
@property(nonatomic) _Bool hasSubtypeArray; // @dynamic hasSubtypeArray;
@property(nonatomic) _Bool hasSuggestEnglishWord; // @dynamic hasSuggestEnglishWord;
@property(nonatomic) _Bool hasThemeType; // @dynamic hasThemeType;
@property(nonatomic) _Bool hasUseAutoConversion; // @dynamic hasUseAutoConversion;
@property(nonatomic) _Bool hasUseContactsDict; // @dynamic hasUseContactsDict;
@property(nonatomic) _Bool hasUseDictionarySuggest; // @dynamic hasUseDictionarySuggest;
@property(nonatomic) _Bool hasUseDoubleSpacePeriod; // @dynamic hasUseDoubleSpacePeriod;
@property(nonatomic) _Bool hasUseEmojiConversion; // @dynamic hasUseEmojiConversion;
@property(nonatomic) _Bool hasUseFullPinyinScheme; // @dynamic hasUseFullPinyinScheme;
@property(nonatomic) _Bool hasUseFuzzyPinyin; // @dynamic hasUseFuzzyPinyin;
@property(nonatomic) _Bool hasUseHistorySuggest; // @dynamic hasUseHistorySuggest;
@property(nonatomic) _Bool hasUseJapaneseLayout; // @dynamic hasUseJapaneseLayout;
@property(nonatomic) _Bool hasUseNumberConversion; // @dynamic hasUseNumberConversion;
@property(nonatomic) _Bool hasUsePersonalizedDicts; // @dynamic hasUsePersonalizedDicts;
@property(nonatomic) _Bool hasUseSymbolConversion; // @dynamic hasUseSymbolConversion;
@property(nonatomic) _Bool hasUseT13NConversion; // @dynamic hasUseT13NConversion;
@property(nonatomic) _Bool hasUserDictSyncEnabled; // @dynamic hasUserDictSyncEnabled;
@property(nonatomic) _Bool hasVibrateOnKeypress; // @dynamic hasVibrateOnKeypress;
@property(nonatomic) _Bool hasVoiceInputKey; // @dynamic hasVoiceInputKey;
@property(nonatomic) _Bool includeOtherImesInLanguageSwitchList; // @dynamic includeOtherImesInLanguageSwitchList;
@property(nonatomic) int keyboardHeightInPercentage; // @dynamic keyboardHeightInPercentage;
@property(nonatomic) int longPressDelay; // @dynamic longPressDelay;
@property(nonatomic) _Bool optInHandwritingFeedback; // @dynamic optInHandwritingFeedback;
@property(nonatomic) _Bool optInUserMetrics; // @dynamic optInUserMetrics;
@property(nonatomic) _Bool personalizedSuggestions; // @dynamic personalizedSuggestions;
@property(nonatomic) _Bool phraseGestureEnabled; // @dynamic phraseGestureEnabled;
@property(nonatomic) _Bool popupOnKeypress; // @dynamic popupOnKeypress;
@property(nonatomic) _Bool predictionEnabled; // @dynamic predictionEnabled;
@property(nonatomic) _Bool scTcConversion; // @dynamic scTcConversion;
@property(nonatomic) _Bool showLanguageSwitchKey; // @dynamic showLanguageSwitchKey;
@property(nonatomic) _Bool soundOnKeypress; // @dynamic soundOnKeypress;
@property(nonatomic) _Bool spellCorrectionEnabled; // @dynamic spellCorrectionEnabled;
@property(retain, nonatomic) PBMutableArray *subtypeArray; // @dynamic subtypeArray;
@property(nonatomic) _Bool suggestEnglishWord; // @dynamic suggestEnglishWord;
@property(nonatomic) int themeType; // @dynamic themeType;
@property(nonatomic) _Bool useAutoConversion; // @dynamic useAutoConversion;
@property(nonatomic) _Bool useContactsDict; // @dynamic useContactsDict;
@property(nonatomic) _Bool useDictionarySuggest; // @dynamic useDictionarySuggest;
@property(nonatomic) _Bool useDoubleSpacePeriod; // @dynamic useDoubleSpacePeriod;
@property(nonatomic) _Bool useEmojiConversion; // @dynamic useEmojiConversion;
@property(nonatomic) _Bool useFullPinyinScheme; // @dynamic useFullPinyinScheme;
@property(nonatomic) _Bool useFuzzyPinyin; // @dynamic useFuzzyPinyin;
@property(nonatomic) _Bool useHistorySuggest; // @dynamic useHistorySuggest;
@property(nonatomic) _Bool useJapaneseLayout; // @dynamic useJapaneseLayout;
@property(nonatomic) _Bool useNumberConversion; // @dynamic useNumberConversion;
@property(nonatomic) _Bool usePersonalizedDicts; // @dynamic usePersonalizedDicts;
@property(nonatomic) _Bool useSymbolConversion; // @dynamic useSymbolConversion;
@property(nonatomic) _Bool useT13NConversion; // @dynamic useT13NConversion;
@property(nonatomic) _Bool userDictSyncEnabled; // @dynamic userDictSyncEnabled;
@property(nonatomic) _Bool vibrateOnKeypress; // @dynamic vibrateOnKeypress;
@property(nonatomic) _Bool voiceInputKey; // @dynamic voiceInputKey;

@end

