//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface KeyboardSubtype : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLayout; // @dynamic hasLayout;
@property(nonatomic) _Bool hasLocale; // @dynamic hasLocale;
@property(retain, nonatomic) NSString *layout; // @dynamic layout;
@property(retain, nonatomic) NSString *locale; // @dynamic locale;

@end

