//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface KeyboardEditorMetadata : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool causeKeyboardRestart; // @dynamic causeKeyboardRestart;
@property(nonatomic) _Bool hasCauseKeyboardRestart; // @dynamic hasCauseKeyboardRestart;
@property(nonatomic) _Bool hasInputType; // @dynamic hasInputType;
@property(nonatomic) _Bool hasOrientation; // @dynamic hasOrientation;
@property(nonatomic) int inputType; // @dynamic inputType;
@property(nonatomic) int orientation; // @dynamic orientation;

@end

