//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface KeyEventMetadata : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int actionType; // @dynamic actionType;
@property(nonatomic) int count; // @dynamic count;
@property(nonatomic) _Bool hardKey; // @dynamic hardKey;
@property(nonatomic) _Bool hasActionType; // @dynamic hasActionType;
@property(nonatomic) _Bool hasCount; // @dynamic hasCount;
@property(nonatomic) _Bool hasHardKey; // @dynamic hasHardKey;
@property(nonatomic) _Bool hasKeyCodeType; // @dynamic hasKeyCodeType;
@property(nonatomic) _Bool hasPreviousActionType; // @dynamic hasPreviousActionType;
@property(nonatomic) _Bool hasPreviousKeyCodeType; // @dynamic hasPreviousKeyCodeType;
@property(nonatomic) _Bool hasResultEventType; // @dynamic hasResultEventType;
@property(nonatomic) int keyCodeType; // @dynamic keyCodeType;
@property(nonatomic) int previousActionType; // @dynamic previousActionType;
@property(nonatomic) int previousKeyCodeType; // @dynamic previousKeyCodeType;
@property(nonatomic) int resultEventType; // @dynamic resultEventType;

@end

