//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface LanguageTipNotification : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRequeryURL; // @dynamic hasRequeryURL;
@property(nonatomic) _Bool hasShow; // @dynamic hasShow;
@property(nonatomic) _Bool hasTipText; // @dynamic hasTipText;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(copy, nonatomic) NSString *requeryURL; // @dynamic requeryURL;
@property(nonatomic) _Bool show; // @dynamic show;
@property(copy, nonatomic) NSString *tipText; // @dynamic tipText;
@property(nonatomic) int type; // @dynamic type;

@end

