//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface LanguageConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *code; // @dynamic code;
@property(nonatomic) _Bool hasCode; // @dynamic hasCode;
@property(nonatomic) _Bool hasIsOriginal; // @dynamic hasIsOriginal;
@property(nonatomic) _Bool hasShowDirectObject; // @dynamic hasShowDirectObject;
@property(nonatomic) _Bool hasShowGender; // @dynamic hasShowGender;
@property(nonatomic) _Bool hasShowIndirectObject; // @dynamic hasShowIndirectObject;
@property(nonatomic) _Bool hasShowPlurality; // @dynamic hasShowPlurality;
@property(nonatomic) _Bool hasShowSubject; // @dynamic hasShowSubject;
@property(nonatomic) _Bool hasSpreadsheetKey; // @dynamic hasSpreadsheetKey;
@property(nonatomic) _Bool isOriginal; // @dynamic isOriginal;
@property(nonatomic) _Bool showDirectObject; // @dynamic showDirectObject;
@property(nonatomic) _Bool showGender; // @dynamic showGender;
@property(nonatomic) _Bool showIndirectObject; // @dynamic showIndirectObject;
@property(nonatomic) _Bool showPlurality; // @dynamic showPlurality;
@property(nonatomic) _Bool showSubject; // @dynamic showSubject;
@property(copy, nonatomic) NSString *spreadsheetKey; // @dynamic spreadsheetKey;

@end

