//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface LeadersResult_LeaderBoard : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasStatId; // @dynamic hasStatId;
@property(retain, nonatomic) NSMutableArray *playerArray; // @dynamic playerArray;
@property(readonly, nonatomic) unsigned long long playerArray_Count; // @dynamic playerArray_Count;
@property(copy, nonatomic) NSString *statId; // @dynamic statId;

@end

