//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface LiveResultVisualElements : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int container; // @dynamic container;
@property(nonatomic) _Bool hasContainer; // @dynamic hasContainer;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasImageLink; // @dynamic hasImageLink;
@property(nonatomic) _Bool hasResultLink; // @dynamic hasResultLink;
@property(nonatomic) _Bool hasTableRow; // @dynamic hasTableRow;
@property(nonatomic) _Bool hasTitleLink; // @dynamic hasTitleLink;
@property(nonatomic) int image; // @dynamic image;
@property(nonatomic) int imageLink; // @dynamic imageLink;
@property(nonatomic) int resultLink; // @dynamic resultLink;
@property(nonatomic) int tableRow; // @dynamic tableRow;
@property(nonatomic) int titleLink; // @dynamic titleLink;

@end

