//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DisambiguationData, EntityColorsCollection, EntityImagesCollection, GWPImage, GWPLocalizedString, LiveResultVisualElements, LocaleInfo, LocalizedEntityNamesCollection, NSMutableArray, NSString, TextToSpeechWrapper, UnclicksLoggingControl;

@interface LiveResultData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double confidenceAfterVoter; // @dynamic confidenceAfterVoter;
@property(nonatomic) int currentExtension; // @dynamic currentExtension;
@property(retain, nonatomic) NSMutableArray *debugMsgArray; // @dynamic debugMsgArray;
@property(readonly, nonatomic) unsigned long long debugMsgArray_Count; // @dynamic debugMsgArray_Count;
@property(retain, nonatomic) DisambiguationData *disambiguationData; // @dynamic disambiguationData;
@property(retain, nonatomic) EntityColorsCollection *entityColors; // @dynamic entityColors;
@property(retain, nonatomic) EntityImagesCollection *entityImages; // @dynamic entityImages;
@property(nonatomic) int familyWiseRank; // @dynamic familyWiseRank;
@property(nonatomic) _Bool hasConfidenceAfterVoter; // @dynamic hasConfidenceAfterVoter;
@property(nonatomic) _Bool hasCurrentExtension; // @dynamic hasCurrentExtension;
@property(nonatomic) _Bool hasDisambiguationData; // @dynamic hasDisambiguationData;
@property(nonatomic) _Bool hasEntityColors; // @dynamic hasEntityColors;
@property(nonatomic) _Bool hasEntityImages; // @dynamic hasEntityImages;
@property(nonatomic) _Bool hasFamilyWiseRank; // @dynamic hasFamilyWiseRank;
@property(nonatomic) _Bool hasHeader; // @dynamic hasHeader;
@property(nonatomic) _Bool hasImpressionTag; // @dynamic hasImpressionTag;
@property(nonatomic) _Bool hasLocaleInfo; // @dynamic hasLocaleInfo;
@property(nonatomic) _Bool hasLocalizedEntityNames; // @dynamic hasLocalizedEntityNames;
@property(nonatomic) _Bool hasMobileHeaderImage; // @dynamic hasMobileHeaderImage;
@property(nonatomic) _Bool hasNumberOfResultsToShowInCollapsedMode; // @dynamic hasNumberOfResultsToShowInCollapsedMode;
@property(nonatomic) _Bool hasPlatform; // @dynamic hasPlatform;
@property(nonatomic) _Bool hasResponseType; // @dynamic hasResponseType;
@property(nonatomic) _Bool hasSecondaryHeader; // @dynamic hasSecondaryHeader;
@property(nonatomic) _Bool hasTextToSpeech; // @dynamic hasTextToSpeech;
@property(nonatomic) _Bool hasUnclicksLoggingControl; // @dynamic hasUnclicksLoggingControl;
@property(nonatomic) _Bool hasUseJavaPlugin; // @dynamic hasUseJavaPlugin;
@property(nonatomic) _Bool hasUseMainColumn; // @dynamic hasUseMainColumn;
@property(nonatomic) _Bool hasUseRhsPanel; // @dynamic hasUseRhsPanel;
@property(nonatomic) _Bool hasVisualElementTags; // @dynamic hasVisualElementTags;
@property(retain, nonatomic) GWPLocalizedString *header; // @dynamic header;
@property(copy, nonatomic) NSString *impressionTag; // @dynamic impressionTag;
@property(retain, nonatomic) LocaleInfo *localeInfo; // @dynamic localeInfo;
@property(retain, nonatomic) LocalizedEntityNamesCollection *localizedEntityNames; // @dynamic localizedEntityNames;
@property(retain, nonatomic) GWPImage *mobileHeaderImage; // @dynamic mobileHeaderImage;
@property(nonatomic) int numberOfResultsToShowInCollapsedMode; // @dynamic numberOfResultsToShowInCollapsedMode;
@property(copy, nonatomic) NSString *platform; // @dynamic platform;
@property(nonatomic) int responseType; // @dynamic responseType;
@property(retain, nonatomic) NSMutableArray *resultArray; // @dynamic resultArray;
@property(readonly, nonatomic) unsigned long long resultArray_Count; // @dynamic resultArray_Count;
@property(retain, nonatomic) GWPLocalizedString *secondaryHeader; // @dynamic secondaryHeader;
@property(retain, nonatomic) TextToSpeechWrapper *textToSpeech; // @dynamic textToSpeech;
@property(retain, nonatomic) UnclicksLoggingControl *unclicksLoggingControl; // @dynamic unclicksLoggingControl;
@property(nonatomic) _Bool useJavaPlugin; // @dynamic useJavaPlugin;
@property(nonatomic) _Bool useMainColumn; // @dynamic useMainColumn;
@property(nonatomic) _Bool useRhsPanel; // @dynamic useRhsPanel;
@property(retain, nonatomic) LiveResultVisualElements *visualElementTags; // @dynamic visualElementTags;

@end

