//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface LocalizedEntityNames_Name : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *directObject; // @dynamic directObject;
@property(copy, nonatomic) NSString *fallbackLocale; // @dynamic fallbackLocale;
@property(nonatomic) _Bool hasDirectObject; // @dynamic hasDirectObject;
@property(nonatomic) _Bool hasFallbackLocale; // @dynamic hasFallbackLocale;
@property(nonatomic) _Bool hasIndirectObject; // @dynamic hasIndirectObject;
@property(nonatomic) _Bool hasSubject; // @dynamic hasSubject;
@property(nonatomic) _Bool hasValue; // @dynamic hasValue;
@property(copy, nonatomic) NSString *indirectObject; // @dynamic indirectObject;
@property(copy, nonatomic) NSString *subject; // @dynamic subject;
@property(copy, nonatomic) NSString *value; // @dynamic value;

@end

