//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface LocationQualifier : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNonUserLocation; // @dynamic hasNonUserLocation;
@property(nonatomic) _Bool hasPreciseLocation; // @dynamic hasPreciseLocation;
@property(nonatomic) _Bool nonUserLocation; // @dynamic nonUserLocation;
@property(nonatomic) _Bool preciseLocation; // @dynamic preciseLocation;

@end

