//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LocalizedEntityNames_Location, LocalizedEntityNames_Name, NSString;

@interface LocalizedEntityNames : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) LocalizedEntityNames_Name *abbreviation; // @dynamic abbreviation;
@property(retain, nonatomic) LocalizedEntityNames_Name *affiliationName; // @dynamic affiliationName;
@property(copy, nonatomic) NSString *debugString; // @dynamic debugString;
@property(retain, nonatomic) LocalizedEntityNames_Name *familyName; // @dynamic familyName;
@property(retain, nonatomic) LocalizedEntityNames_Name *fullName; // @dynamic fullName;
@property(retain, nonatomic) LocalizedEntityNames_Name *givenName; // @dynamic givenName;
@property(nonatomic) _Bool hasAbbreviation; // @dynamic hasAbbreviation;
@property(nonatomic) _Bool hasAffiliationName; // @dynamic hasAffiliationName;
@property(nonatomic) _Bool hasDebugString; // @dynamic hasDebugString;
@property(nonatomic) _Bool hasFamilyName; // @dynamic hasFamilyName;
@property(nonatomic) _Bool hasFullName; // @dynamic hasFullName;
@property(nonatomic) _Bool hasGivenName; // @dynamic hasGivenName;
@property(nonatomic) _Bool hasLocation; // @dynamic hasLocation;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(nonatomic) _Bool hasShortName; // @dynamic hasShortName;
@property(nonatomic) _Bool hasSpokenShortName; // @dynamic hasSpokenShortName;
@property(nonatomic) _Bool hasTopicalSquery; // @dynamic hasTopicalSquery;
@property(retain, nonatomic) LocalizedEntityNames_Location *location; // @dynamic location;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;
@property(retain, nonatomic) LocalizedEntityNames_Name *shortName; // @dynamic shortName;
@property(retain, nonatomic) LocalizedEntityNames_Name *spokenShortName; // @dynamic spokenShortName;
@property(copy, nonatomic) NSString *topicalSquery; // @dynamic topicalSquery;

@end

