//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LocalizedEntityNames, NSString;

@interface Localization : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLanguage; // @dynamic hasLanguage;
@property(nonatomic) _Bool hasNames; // @dynamic hasNames;
@property(copy, nonatomic) NSString *language; // @dynamic language;
@property(retain, nonatomic) LocalizedEntityNames *names; // @dynamic names;

@end

