//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface LocaleInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *country; // @dynamic country;
@property(copy, nonatomic) NSString *countryMid; // @dynamic countryMid;
@property(nonatomic) _Bool hasCountry; // @dynamic hasCountry;
@property(nonatomic) _Bool hasCountryMid; // @dynamic hasCountryMid;
@property(nonatomic) _Bool hasLang; // @dynamic hasLang;
@property(nonatomic) _Bool hasLocalizedTimezone; // @dynamic hasLocalizedTimezone;
@property(nonatomic) _Bool hasTimezone; // @dynamic hasTimezone;
@property(copy, nonatomic) NSString *lang; // @dynamic lang;
@property(copy, nonatomic) NSString *localizedTimezone; // @dynamic localizedTimezone;
@property(copy, nonatomic) NSString *timezone; // @dynamic timezone;

@end

