//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LOCULatLng;

@interface LOCULatLngRect : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHi; // @dynamic hasHi;
@property(nonatomic) _Bool hasLo; // @dynamic hasLo;
@property(retain, nonatomic) LOCULatLng *hi; // @dynamic hi;
@property(retain, nonatomic) LOCULatLng *lo; // @dynamic lo;

@end

