//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface LOCUFeatureIdProto : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) unsigned long long cellId; // @dynamic cellId;
@property(nonatomic) unsigned long long fprint; // @dynamic fprint;
@property(nonatomic) _Bool hasCellId; // @dynamic hasCellId;
@property(nonatomic) _Bool hasFprint; // @dynamic hasFprint;

@end

