//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface MatchDetails_Lineup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *awayArray; // @dynamic awayArray;
@property(readonly, nonatomic) unsigned long long awayArray_Count; // @dynamic awayArray_Count;
@property(retain, nonatomic) NSMutableArray *homeArray; // @dynamic homeArray;
@property(readonly, nonatomic) unsigned long long homeArray_Count; // @dynamic homeArray_Count;
@property(retain, nonatomic) NSMutableArray *refereeArray; // @dynamic refereeArray;
@property(readonly, nonatomic) unsigned long long refereeArray_Count; // @dynamic refereeArray_Count;

@end

