//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MatchDetails_Time : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasMinute; // @dynamic hasMinute;
@property(nonatomic) _Bool hasSecond; // @dynamic hasSecond;
@property(nonatomic) _Bool hasStoppageTime; // @dynamic hasStoppageTime;
@property(nonatomic) int minute; // @dynamic minute;
@property(nonatomic) int second; // @dynamic second;
@property(nonatomic) int stoppageTime; // @dynamic stoppageTime;

@end

