//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MatchDetails_Baseball_TeamInfo;

@interface MatchDetails_Baseball : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MatchDetails_Baseball_TeamInfo *awayParticipant; // @dynamic awayParticipant;
@property(nonatomic) int balls; // @dynamic balls;
@property(nonatomic) _Bool hasAwayParticipant; // @dynamic hasAwayParticipant;
@property(nonatomic) _Bool hasBalls; // @dynamic hasBalls;
@property(nonatomic) _Bool hasHomeParticipant; // @dynamic hasHomeParticipant;
@property(nonatomic) _Bool hasInningStatus; // @dynamic hasInningStatus;
@property(nonatomic) _Bool hasOuts; // @dynamic hasOuts;
@property(nonatomic) _Bool hasStrikes; // @dynamic hasStrikes;
@property(retain, nonatomic) MatchDetails_Baseball_TeamInfo *homeParticipant; // @dynamic homeParticipant;
@property(nonatomic) int inningStatus; // @dynamic inningStatus;
@property(nonatomic) int outs; // @dynamic outs;
@property(nonatomic) int strikes; // @dynamic strikes;

@end

