//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Statistic;

@interface MatchDetails_MatchStats : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Statistic *away; // @dynamic away;
@property(nonatomic) _Bool hasAway; // @dynamic hasAway;
@property(nonatomic) _Bool hasHome; // @dynamic hasHome;
@property(retain, nonatomic) Statistic *home; // @dynamic home;

@end

