//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface MatchDetails_Lineup_TeamLineup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *coachArray; // @dynamic coachArray;
@property(readonly, nonatomic) unsigned long long coachArray_Count; // @dynamic coachArray_Count;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(retain, nonatomic) NSMutableArray *playerArray; // @dynamic playerArray;
@property(readonly, nonatomic) unsigned long long playerArray_Count; // @dynamic playerArray_Count;
@property(retain, nonatomic) NSMutableArray *substituteArray; // @dynamic substituteArray;
@property(readonly, nonatomic) unsigned long long substituteArray_Count; // @dynamic substituteArray_Count;
@property(nonatomic) int type; // @dynamic type;

@end

