//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MatchDetails_Baseball_TeamInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int errors; // @dynamic errors;
@property(nonatomic) _Bool hasErrors; // @dynamic hasErrors;
@property(nonatomic) _Bool hasHits; // @dynamic hasHits;
@property(nonatomic) _Bool hasRuns; // @dynamic hasRuns;
@property(nonatomic) int hits; // @dynamic hits;
@property(nonatomic) int runs; // @dynamic runs;

@end

