//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class PrimaryColor;

@interface MaterialColor : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPrimaryColor; // @dynamic hasPrimaryColor;
@property(retain, nonatomic) PrimaryColor *primaryColor; // @dynamic primaryColor;

@end

