//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface MDCFontDiskLoader : NSObject
{
    _Bool _isRegistered;
    _Bool _hasFailedRegistration;
    NSString *_fontName;
    NSURL *_fontURL;
}

@property(nonatomic) _Bool hasFailedRegistration; // @synthesize hasFailedRegistration=_hasFailedRegistration;
@property(nonatomic) _Bool isRegistered; // @synthesize isRegistered=_isRegistered;
@property(retain, nonatomic) NSURL *fontURL; // @synthesize fontURL=_fontURL;
@property(retain, nonatomic) NSString *fontName; // @synthesize fontName=_fontName;
- (void).cxx_destruct;
- (id)fontOfSize:(double)arg1;
- (_Bool)registerFont;
- (id)initWithFontName:(id)arg1 filename:(id)arg2 bundleFileName:(id)arg3 baseBundle:(id)arg4;
- (id)initWithName:(id)arg1 URL:(id)arg2;

@end

