//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Metadata, NSMutableArray, NSString;

@interface MedalCountResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *entityMedalsArray; // @dynamic entityMedalsArray;
@property(readonly, nonatomic) unsigned long long entityMedalsArray_Count; // @dynamic entityMedalsArray_Count;
@property(copy, nonatomic) NSString *focusedEntityMid; // @dynamic focusedEntityMid;
@property(nonatomic) _Bool hasFocusedEntityMid; // @dynamic hasFocusedEntityMid;
@property(nonatomic) _Bool hasLastUpdate; // @dynamic hasLastUpdate;
@property(nonatomic) _Bool hasMetadata; // @dynamic hasMetadata;
@property(copy, nonatomic) NSString *lastUpdate; // @dynamic lastUpdate;
@property(retain, nonatomic) Metadata *metadata; // @dynamic metadata;

@end

