//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MediaAsset_ImageUrls_DeviceSpecificImageUrls;

@interface MediaAsset_ImageUrls : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) MediaAsset_ImageUrls_DeviceSpecificImageUrls *desktop; // @dynamic desktop;
@property(nonatomic) _Bool hasDesktop; // @dynamic hasDesktop;
@property(nonatomic) _Bool hasMobile; // @dynamic hasMobile;
@property(nonatomic) _Bool hasTablet; // @dynamic hasTablet;
@property(retain, nonatomic) MediaAsset_ImageUrls_DeviceSpecificImageUrls *mobile; // @dynamic mobile;
@property(retain, nonatomic) MediaAsset_ImageUrls_DeviceSpecificImageUrls *tablet; // @dynamic tablet;

@end

