//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GeoRestrictionInfo, MediaAsset_ExpirationPolicy, MediaAsset_ImageAttribution, MediaAsset_ImageUrls, MediaAsset_VideoInformation, NSString;

@interface MediaAsset : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int assetType; // @dynamic assetType;
@property(retain, nonatomic) MediaAsset_ImageAttribution *attribution; // @dynamic attribution;
@property(retain, nonatomic) MediaAsset_ExpirationPolicy *expirationPolicy; // @dynamic expirationPolicy;
@property(retain, nonatomic) GeoRestrictionInfo *geoRestriction; // @dynamic geoRestriction;
@property(nonatomic) _Bool hasAssetType; // @dynamic hasAssetType;
@property(nonatomic) _Bool hasAttribution; // @dynamic hasAttribution;
@property(nonatomic) _Bool hasExpirationPolicy; // @dynamic hasExpirationPolicy;
@property(nonatomic) _Bool hasGeoRestriction; // @dynamic hasGeoRestriction;
@property(nonatomic) _Bool hasImageUrls; // @dynamic hasImageUrls;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool hasVideoInformation; // @dynamic hasVideoInformation;
@property(retain, nonatomic) MediaAsset_ImageUrls *imageUrls; // @dynamic imageUrls;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) MediaAsset_VideoInformation *videoInformation; // @dynamic videoInformation;

@end

