//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MediaAsset_ImageUrls_DeviceSpecificImageUrls_SizeSpecificImageUrls, NSString;

@interface MediaAsset_ImageUrls_DeviceSpecificImageUrls : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasHighRes; // @dynamic hasHighRes;
@property(nonatomic) _Bool hasLarge; // @dynamic hasLarge;
@property(nonatomic) _Bool hasLowRes; // @dynamic hasLowRes;
@property(nonatomic) _Bool hasSmall; // @dynamic hasSmall;
@property(copy, nonatomic) NSString *highRes; // @dynamic highRes;
@property(retain, nonatomic) MediaAsset_ImageUrls_DeviceSpecificImageUrls_SizeSpecificImageUrls *large; // @dynamic large;
@property(copy, nonatomic) NSString *lowRes; // @dynamic lowRes;
@property(retain, nonatomic) MediaAsset_ImageUrls_DeviceSpecificImageUrls_SizeSpecificImageUrls *small; // @dynamic small;

@end

