//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MSPFormattedString_FormattedSubstring : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSubstring; // @dynamic hasSubstring;
@property(copy, nonatomic) NSString *substring; // @dynamic substring;

@end

