//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class MSPImageSearchRequestContext, MSPSearchQuery, MSPSearchRequestOptions;

@interface MSPImageSearchRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int deprecatedSafeSearchMode; // @dynamic deprecatedSafeSearchMode;
@property(nonatomic) _Bool hasDeprecatedSafeSearchMode; // @dynamic hasDeprecatedSafeSearchMode;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(nonatomic) _Bool hasQuery; // @dynamic hasQuery;
@property(nonatomic) _Bool hasRequestContext; // @dynamic hasRequestContext;
@property(retain, nonatomic) MSPSearchRequestOptions *options; // @dynamic options;
@property(retain, nonatomic) MSPSearchQuery *query; // @dynamic query;
@property(retain, nonatomic) MSPImageSearchRequestContext *requestContext; // @dynamic requestContext;

@end

