//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWSLocalizationContext, GWSUserAgentContext, GWSZwiebackCookieRequestContext;

@interface MSPImageSearchRequestContext : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLocalizationContext; // @dynamic hasLocalizationContext;
@property(nonatomic) _Bool hasUserAgentContext; // @dynamic hasUserAgentContext;
@property(nonatomic) _Bool hasZwiebackCookieContext; // @dynamic hasZwiebackCookieContext;
@property(retain, nonatomic) GWSLocalizationContext *localizationContext; // @dynamic localizationContext;
@property(retain, nonatomic) GWSUserAgentContext *userAgentContext; // @dynamic userAgentContext;
@property(retain, nonatomic) GWSZwiebackCookieRequestContext *zwiebackCookieContext; // @dynamic zwiebackCookieContext;

@end

