//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MSPPagination : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasNextPageToken; // @dynamic hasNextPageToken;
@property(nonatomic) _Bool hasPageIndex; // @dynamic hasPageIndex;
@property(nonatomic) _Bool hasPreviousPageToken; // @dynamic hasPreviousPageToken;
@property(copy, nonatomic) NSString *nextPageToken; // @dynamic nextPageToken;
@property(nonatomic) int pageIndex; // @dynamic pageIndex;
@property(copy, nonatomic) NSString *previousPageToken; // @dynamic previousPageToken;

@end

