//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MSPRelatedQuery : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasQuery; // @dynamic hasQuery;
@property(nonatomic) _Bool hasShortQuery; // @dynamic hasShortQuery;
@property(copy, nonatomic) NSString *query; // @dynamic query;
@property(copy, nonatomic) NSString *shortQuery; // @dynamic shortQuery;

@end

