//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLocalizedString, LocalizedEntityNames, NSMutableArray;

@interface MultiParticipantEventResults_Round_Heat : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *athleteResultDataArray; // @dynamic athleteResultDataArray;
@property(readonly, nonatomic) unsigned long long athleteResultDataArray_Count; // @dynamic athleteResultDataArray_Count;
@property(retain, nonatomic) LocalizedEntityNames *finalName; // @dynamic finalName;
@property(retain, nonatomic) GWPLocalizedString *finalResultName; // @dynamic finalResultName;
@property(nonatomic) _Bool hasFinalName; // @dynamic hasFinalName;
@property(nonatomic) _Bool hasFinalResultName; // @dynamic hasFinalResultName;
@property(nonatomic) _Bool hasNumber; // @dynamic hasNumber;
@property(nonatomic) _Bool hasWindSpeed; // @dynamic hasWindSpeed;
@property(nonatomic) int number; // @dynamic number;
@property(retain, nonatomic) NSMutableArray *resultNameArray; // @dynamic resultNameArray;
@property(readonly, nonatomic) unsigned long long resultNameArray_Count; // @dynamic resultNameArray_Count;
@property(retain, nonatomic) NSMutableArray *resultPartNameArray; // @dynamic resultPartNameArray;
@property(readonly, nonatomic) unsigned long long resultPartNameArray_Count; // @dynamic resultPartNameArray_Count;
@property(nonatomic) double windSpeed; // @dynamic windSpeed;

@end

