//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLink, LocalizedEntityNames, NSMutableArray, NSString;

@interface MultiParticipantEventResults : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) LocalizedEntityNames *event; // @dynamic event;
@property(retain, nonatomic) GWPLink *eventName; // @dynamic eventName;
@property(nonatomic) int gender; // @dynamic gender;
@property(nonatomic) _Bool hasEvent; // @dynamic hasEvent;
@property(nonatomic) _Bool hasEventName; // @dynamic hasEventName;
@property(nonatomic) _Bool hasGender; // @dynamic hasGender;
@property(nonatomic) _Bool hasHighlightedHeat; // @dynamic hasHighlightedHeat;
@property(nonatomic) _Bool hasHighlightedRound; // @dynamic hasHighlightedRound;
@property(nonatomic) _Bool hasLastUpdate; // @dynamic hasLastUpdate;
@property(nonatomic) int highlightedHeat; // @dynamic highlightedHeat;
@property(nonatomic) int highlightedRound; // @dynamic highlightedRound;
@property(copy, nonatomic) NSString *lastUpdate; // @dynamic lastUpdate;
@property(retain, nonatomic) NSMutableArray *roundArray; // @dynamic roundArray;
@property(readonly, nonatomic) unsigned long long roundArray_Count; // @dynamic roundArray_Count;

@end

