//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBEnumArray, GWPLink, LocalizedEntityNames, NSMutableArray;

@interface MultiParticipantEventResults_Round : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasOrdinalType; // @dynamic hasOrdinalType;
@property(nonatomic) _Bool hasRoundName; // @dynamic hasRoundName;
@property(retain, nonatomic) NSMutableArray *heatArray; // @dynamic heatArray;
@property(readonly, nonatomic) unsigned long long heatArray_Count; // @dynamic heatArray_Count;
@property(retain, nonatomic) LocalizedEntityNames *name; // @dynamic name;
@property(nonatomic) int ordinalType; // @dynamic ordinalType;
@property(retain, nonatomic) GWPLink *roundName; // @dynamic roundName;
@property(retain, nonatomic) GPBEnumArray *usedRecordNotesArray; // @dynamic usedRecordNotesArray;
@property(readonly, nonatomic) unsigned long long usedRecordNotesArray_Count; // @dynamic usedRecordNotesArray_Count;
@property(retain, nonatomic) GPBEnumArray *usedStatusesArray; // @dynamic usedStatusesArray;
@property(readonly, nonatomic) unsigned long long usedStatusesArray_Count; // @dynamic usedStatusesArray_Count;

@end

