//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface NameConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasShowAbbreviation; // @dynamic hasShowAbbreviation;
@property(nonatomic) _Bool hasShowFull; // @dynamic hasShowFull;
@property(nonatomic) _Bool hasShowShort; // @dynamic hasShowShort;
@property(nonatomic) _Bool hasShowSpoken; // @dynamic hasShowSpoken;
@property(nonatomic) _Bool showAbbreviation; // @dynamic showAbbreviation;
@property(nonatomic) _Bool showFull; // @dynamic showFull;
@property(nonatomic) _Bool showShort; // @dynamic showShort;
@property(nonatomic) _Bool showSpoken; // @dynamic showSpoken;

@end

