//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPB2Timestamp, NSString, NewsImage, StyledText, Url;

@interface NewsResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Url *URL; // @dynamic URL;
@property(retain, nonatomic) GPB2Timestamp *currentUpdateDate; // @dynamic currentUpdateDate;
@property(nonatomic) _Bool hasCurrentUpdateDate; // @dynamic hasCurrentUpdateDate;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasSnippet; // @dynamic hasSnippet;
@property(nonatomic) _Bool hasSnippetHtml; // @dynamic hasSnippetHtml;
@property(nonatomic) _Bool hasSource; // @dynamic hasSource;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool hasTitleHtml; // @dynamic hasTitleHtml;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(retain, nonatomic) NewsImage *image; // @dynamic image;
@property(retain, nonatomic) StyledText *snippet; // @dynamic snippet;
@property(copy, nonatomic) NSString *snippetHtml; // @dynamic snippetHtml;
@property(copy, nonatomic) NSString *source; // @dynamic source;
@property(retain, nonatomic) StyledText *title; // @dynamic title;
@property(copy, nonatomic) NSString *titleHtml; // @dynamic titleHtml;

@end

