//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCharacterSet.h"

@interface NSCharacterSet (Customized)
+ (id)textConnectorCharacterSet;
+ (id)endOfParagraphCharacterSet;
+ (id)endSymbolCharacterSet;
+ (id)ignorableCharacterSet;
- (_Bool)scalarIsMember:(id)arg1;
@end

