//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@interface NSEnumerator (GRXUtil)
+ (id)grx_enumeratorWithValueSupplier:(CDUnknownBlockType)arg1;
+ (id)grx_enumeratorWithSingleValue:(id)arg1;
+ (id)grx_enumeratorWithContainer:(id)arg1;
@end

