//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSLayoutConstraint.h"

@interface NSLayoutConstraint (GKBNSLayoutConstraintDimensionAdditions)
+ (void)gkb_activateConstraintsToCenterView:(id)arg1 withinView:(id)arg2;
+ (id)gkb_constraintsToCenterView:(id)arg1 withinView:(id)arg2;
+ (void)gkb_activateFullWidthAndHeightConstraints:(id)arg1;
+ (void)gkb_activateFullHeightConstraints:(id)arg1;
+ (void)gkb_activateFullWidthConstraints:(id)arg1;
+ (id)gkb_fullWidthAndHeightConstraints:(id)arg1;
+ (id)gkb_fullHeightConstraints:(id)arg1;
+ (id)gkb_fullWidthConstraints:(id)arg1;
@end

