//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (GRPCMetadata)
+ (id)grpc_stringFromMetadataValue:(struct grpc_metadata *)arg1;
- (void)grpc_initMetadata:(struct grpc_metadata *)arg1;
@end

