//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (GKBLocalizedString)
+ (id)localizedStringForKey:(id)arg1 value:(id)arg2 bundle:(id)arg3 language:(id)arg4;
@end

