//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (GKBNSStringAdditions)
- (id)gkb_stringByRemovingURLs;
- (id)gkb_stringByRemovingAllNonBaseCharacters;
- (id)gkb_stringByRemovingAllNonAlphanumericAndSpaceCharacters;
- (id)gkb_stringByReplacingConsecutiveDuplicateWhitespaceAndNewlineCharactersSeparatedByString:(id)arg1;
- (id)gkb_stringByTrimmingWhitespaceAndNewlineCharacters;
- (id)gkb_stringByTrimmingWhitespaceCharacters;
@end

