//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface OnboardingEvent : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int clickedButton; // @dynamic clickedButton;
@property(nonatomic) _Bool hasClickedButton; // @dynamic hasClickedButton;
@property(nonatomic) _Bool hasTimeToInstallMs; // @dynamic hasTimeToInstallMs;
@property(nonatomic) long long timeToInstallMs; // @dynamic timeToInstallMs;

@end

