//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LocalizedEntityNames, MatchDetails, NSMutableArray, OneVsOneEventData_Seed, OneVsOneEventData_UniformColor, ParticipantData, WinLossRecord;

@interface OneVsOneEventData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int aggregateOutcome; // @dynamic aggregateOutcome;
@property(retain, nonatomic) LocalizedEntityNames *away; // @dynamic away;
@property(retain, nonatomic) ParticipantData *awayParticipant; // @dynamic awayParticipant;
@property(retain, nonatomic) NSMutableArray *awayParticipantAggregateResultArray; // @dynamic awayParticipantAggregateResultArray;
@property(readonly, nonatomic) unsigned long long awayParticipantAggregateResultArray_Count; // @dynamic awayParticipantAggregateResultArray_Count;
@property(retain, nonatomic) OneVsOneEventData_UniformColor *awayParticipantColors; // @dynamic awayParticipantColors;
@property(nonatomic) _Bool awayParticipantIsTbd; // @dynamic awayParticipantIsTbd;
@property(nonatomic) int awayParticipantMedal; // @dynamic awayParticipantMedal;
@property(nonatomic) _Bool awayParticipantQualified; // @dynamic awayParticipantQualified;
@property(retain, nonatomic) NSMutableArray *awayParticipantResultArray; // @dynamic awayParticipantResultArray;
@property(readonly, nonatomic) unsigned long long awayParticipantResultArray_Count; // @dynamic awayParticipantResultArray_Count;
@property(retain, nonatomic) WinLossRecord *awayParticipantWlr; // @dynamic awayParticipantWlr;
@property(retain, nonatomic) OneVsOneEventData_Seed *awaySeed; // @dynamic awaySeed;
@property(nonatomic) _Bool hasAggregateOutcome; // @dynamic hasAggregateOutcome;
@property(nonatomic) _Bool hasAway; // @dynamic hasAway;
@property(nonatomic) _Bool hasAwayParticipant; // @dynamic hasAwayParticipant;
@property(nonatomic) _Bool hasAwayParticipantColors; // @dynamic hasAwayParticipantColors;
@property(nonatomic) _Bool hasAwayParticipantIsTbd; // @dynamic hasAwayParticipantIsTbd;
@property(nonatomic) _Bool hasAwayParticipantMedal; // @dynamic hasAwayParticipantMedal;
@property(nonatomic) _Bool hasAwayParticipantQualified; // @dynamic hasAwayParticipantQualified;
@property(nonatomic) _Bool hasAwayParticipantWlr; // @dynamic hasAwayParticipantWlr;
@property(nonatomic) _Bool hasAwaySeed; // @dynamic hasAwaySeed;
@property(nonatomic) _Bool hasHome; // @dynamic hasHome;
@property(nonatomic) _Bool hasHomeParticipant; // @dynamic hasHomeParticipant;
@property(nonatomic) _Bool hasHomeParticipantColors; // @dynamic hasHomeParticipantColors;
@property(nonatomic) _Bool hasHomeParticipantIsTbd; // @dynamic hasHomeParticipantIsTbd;
@property(nonatomic) _Bool hasHomeParticipantMedal; // @dynamic hasHomeParticipantMedal;
@property(nonatomic) _Bool hasHomeParticipantQualified; // @dynamic hasHomeParticipantQualified;
@property(nonatomic) _Bool hasHomeParticipantWlr; // @dynamic hasHomeParticipantWlr;
@property(nonatomic) _Bool hasHomeSeed; // @dynamic hasHomeSeed;
@property(nonatomic) _Bool hasHostedByHomeParticipant; // @dynamic hasHostedByHomeParticipant;
@property(nonatomic) _Bool hasIsHomeTop; // @dynamic hasIsHomeTop;
@property(nonatomic) _Bool hasIsLineupDataAvailable; // @dynamic hasIsLineupDataAvailable;
@property(nonatomic) _Bool hasMatchDetails; // @dynamic hasMatchDetails;
@property(nonatomic) _Bool hasOutcome; // @dynamic hasOutcome;
@property(nonatomic) _Bool hasRoundType; // @dynamic hasRoundType;
@property(nonatomic) _Bool hasTournamentRound; // @dynamic hasTournamentRound;
@property(nonatomic) _Bool hasTypeForContext; // @dynamic hasTypeForContext;
@property(retain, nonatomic) LocalizedEntityNames *home; // @dynamic home;
@property(retain, nonatomic) ParticipantData *homeParticipant; // @dynamic homeParticipant;
@property(retain, nonatomic) NSMutableArray *homeParticipantAggregateResultArray; // @dynamic homeParticipantAggregateResultArray;
@property(readonly, nonatomic) unsigned long long homeParticipantAggregateResultArray_Count; // @dynamic homeParticipantAggregateResultArray_Count;
@property(retain, nonatomic) OneVsOneEventData_UniformColor *homeParticipantColors; // @dynamic homeParticipantColors;
@property(nonatomic) _Bool homeParticipantIsTbd; // @dynamic homeParticipantIsTbd;
@property(nonatomic) int homeParticipantMedal; // @dynamic homeParticipantMedal;
@property(nonatomic) _Bool homeParticipantQualified; // @dynamic homeParticipantQualified;
@property(retain, nonatomic) NSMutableArray *homeParticipantResultArray; // @dynamic homeParticipantResultArray;
@property(readonly, nonatomic) unsigned long long homeParticipantResultArray_Count; // @dynamic homeParticipantResultArray_Count;
@property(retain, nonatomic) WinLossRecord *homeParticipantWlr; // @dynamic homeParticipantWlr;
@property(retain, nonatomic) OneVsOneEventData_Seed *homeSeed; // @dynamic homeSeed;
@property(nonatomic) _Bool hostedByHomeParticipant; // @dynamic hostedByHomeParticipant;
@property(nonatomic) _Bool isHomeTop; // @dynamic isHomeTop;
@property(nonatomic) _Bool isLineupDataAvailable; // @dynamic isLineupDataAvailable;
@property(retain, nonatomic) MatchDetails *matchDetails; // @dynamic matchDetails;
@property(nonatomic) int outcome; // @dynamic outcome;
@property(nonatomic) int roundType; // @dynamic roundType;
@property(retain, nonatomic) LocalizedEntityNames *tournamentRound; // @dynamic tournamentRound;
@property(nonatomic) int typeForContext; // @dynamic typeForContext;

@end

