//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class AppLink, Carousel, ForumClusterResult, GPB2Timestamp, MegaSiteLinkGroup, NSMutableArray, NSString, OneLineSitelinks, StructuredMetaline, StyledText, Thumbnail, Url, Video;

@interface OrganicSearchResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Url *URL; // @dynamic URL;
@property(copy, nonatomic) NSString *URLVeName; // @dynamic URLVeName;
@property(retain, nonatomic) AppLink *appLink; // @dynamic appLink;
@property(retain, nonatomic) NSMutableArray *attributionArray; // @dynamic attributionArray;
@property(readonly, nonatomic) unsigned long long attributionArray_Count; // @dynamic attributionArray_Count;
@property(retain, nonatomic) NSMutableArray *breadcrumbArray; // @dynamic breadcrumbArray;
@property(readonly, nonatomic) unsigned long long breadcrumbArray_Count; // @dynamic breadcrumbArray_Count;
@property(retain, nonatomic) NSMutableArray *eventRichSnippetItemArray; // @dynamic eventRichSnippetItemArray;
@property(readonly, nonatomic) unsigned long long eventRichSnippetItemArray_Count; // @dynamic eventRichSnippetItemArray_Count;
@property(retain, nonatomic) ForumClusterResult *forumCluster; // @dynamic forumCluster;
@property(nonatomic) _Bool hasAppLink; // @dynamic hasAppLink;
@property(nonatomic) _Bool hasForumCluster; // @dynamic hasForumCluster;
@property(nonatomic) _Bool hasIsRoboted; // @dynamic hasIsRoboted;
@property(nonatomic) _Bool hasMegaSiteLinkGroup; // @dynamic hasMegaSiteLinkGroup;
@property(nonatomic) _Bool hasMetaline; // @dynamic hasMetaline;
@property(nonatomic) _Bool hasMobileFriendly; // @dynamic hasMobileFriendly;
@property(nonatomic) _Bool hasOneLineSitelinks; // @dynamic hasOneLineSitelinks;
@property(nonatomic) _Bool hasPublicationTimestamp; // @dynamic hasPublicationTimestamp;
@property(nonatomic) _Bool hasRobotedURL; // @dynamic hasRobotedURL;
@property(nonatomic) _Bool hasSnippet; // @dynamic hasSnippet;
@property(nonatomic) _Bool hasSnippetHtml; // @dynamic hasSnippetHtml;
@property(nonatomic) _Bool hasSnippetText; // @dynamic hasSnippetText;
@property(nonatomic) _Bool hasSocialAnnotation; // @dynamic hasSocialAnnotation;
@property(nonatomic) _Bool hasSourceDisplayName; // @dynamic hasSourceDisplayName;
@property(nonatomic) _Bool hasStreamCarouselResult; // @dynamic hasStreamCarouselResult;
@property(nonatomic) _Bool hasThumbnail; // @dynamic hasThumbnail;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(nonatomic) _Bool hasTitleHtml; // @dynamic hasTitleHtml;
@property(nonatomic) _Bool hasTitleText; // @dynamic hasTitleText;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(nonatomic) _Bool hasURLVeName; // @dynamic hasURLVeName;
@property(nonatomic) _Bool hasVideo; // @dynamic hasVideo;
@property(nonatomic) _Bool isRoboted; // @dynamic isRoboted;
@property(retain, nonatomic) MegaSiteLinkGroup *megaSiteLinkGroup; // @dynamic megaSiteLinkGroup;
@property(retain, nonatomic) StructuredMetaline *metaline; // @dynamic metaline;
@property(nonatomic) _Bool mobileFriendly; // @dynamic mobileFriendly;
@property(retain, nonatomic) OneLineSitelinks *oneLineSitelinks; // @dynamic oneLineSitelinks;
@property(retain, nonatomic) GPB2Timestamp *publicationTimestamp; // @dynamic publicationTimestamp;
@property(copy, nonatomic) NSString *robotedURL; // @dynamic robotedURL;
@property(retain, nonatomic) StyledText *snippet; // @dynamic snippet;
@property(copy, nonatomic) NSString *snippetHtml; // @dynamic snippetHtml;
@property(copy, nonatomic) NSString *snippetText; // @dynamic snippetText;
@property(copy, nonatomic) NSString *socialAnnotation; // @dynamic socialAnnotation;
@property(retain, nonatomic) StyledText *sourceDisplayName; // @dynamic sourceDisplayName;
@property(retain, nonatomic) Carousel *streamCarouselResult; // @dynamic streamCarouselResult;
@property(retain, nonatomic) Thumbnail *thumbnail; // @dynamic thumbnail;
@property(retain, nonatomic) StyledText *title; // @dynamic title;
@property(copy, nonatomic) NSString *titleHtml; // @dynamic titleHtml;
@property(copy, nonatomic) NSString *titleText; // @dynamic titleText;
@property(retain, nonatomic) Video *video; // @dynamic video;

@end

