//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPImage, GWPLink, NSString;

@interface ParticipantData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(retain, nonatomic) GWPImage *image; // @dynamic image;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;
@property(retain, nonatomic) GWPLink *name; // @dynamic name;

@end

