//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface PBGeneratedMessage (GD4ParsingPBCPP)
+ (id)gd4_parseFromCPPProtobuf:(const struct MessageLite *)arg1;
- (void)gd4_serializeToCPPProtobuf:(struct MessageLite *)arg1;
@end

