//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray, PBServiceOptions;

@interface PBServiceDescriptorProto : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasMethodArray; // @dynamic hasMethodArray;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasOptions; // @dynamic hasOptions;
@property(nonatomic) _Bool hasStreamArray; // @dynamic hasStreamArray;
@property(retain, nonatomic) PBMutableArray *methodArray; // @dynamic methodArray;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) PBServiceOptions *options; // @dynamic options;
@property(retain, nonatomic) PBMutableArray *streamArray; // @dynamic streamArray;

@end

