//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray;

@interface PBSourceCodeInfo_Location : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLeadingComments; // @dynamic hasLeadingComments;
@property(nonatomic) _Bool hasLeadingDetachedCommentsArray; // @dynamic hasLeadingDetachedCommentsArray;
@property(nonatomic) _Bool hasPathArray; // @dynamic hasPathArray;
@property(nonatomic) _Bool hasSpanArray; // @dynamic hasSpanArray;
@property(nonatomic) _Bool hasTrailingComments; // @dynamic hasTrailingComments;
@property(retain, nonatomic) NSString *leadingComments; // @dynamic leadingComments;
@property(retain, nonatomic) PBMutableArray *leadingDetachedCommentsArray; // @dynamic leadingDetachedCommentsArray;
@property(retain, nonatomic) PBMutableArray *pathArray; // @dynamic pathArray;
@property(retain, nonatomic) PBMutableArray *spanArray; // @dynamic spanArray;
@property(retain, nonatomic) NSString *trailingComments; // @dynamic trailingComments;

@end

