//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface PlayerStatsCardResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasSubHeader; // @dynamic hasSubHeader;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *subHeader; // @dynamic subHeader;
@property(retain, nonatomic) NSMutableArray *visualTableArray; // @dynamic visualTableArray;
@property(readonly, nonatomic) unsigned long long visualTableArray_Count; // @dynamic visualTableArray_Count;

@end

