//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Event, NSMutableArray, SportsTeam;

@interface PreviousEventsStatsResult_PreviousEventStats : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Event *event; // @dynamic event;
@property(nonatomic) _Bool hasEvent; // @dynamic hasEvent;
@property(nonatomic) _Bool hasOpponentTeam; // @dynamic hasOpponentTeam;
@property(retain, nonatomic) SportsTeam *opponentTeam; // @dynamic opponentTeam;
@property(retain, nonatomic) NSMutableArray *statisticArray; // @dynamic statisticArray;
@property(readonly, nonatomic) unsigned long long statisticArray_Count; // @dynamic statisticArray_Count;

@end

