//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ProtoMethod : NSObject
{
    NSString *_package;
    NSString *_service;
    NSString *_method;
}

@property(readonly, nonatomic) NSString *method; // @synthesize method=_method;
@property(readonly, nonatomic) NSString *service; // @synthesize service=_service;
@property(readonly, nonatomic) NSString *package; // @synthesize package=_package;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *HTTPPath;
- (id)initWithPackage:(id)arg1 service:(id)arg2 method:(id)arg3;

@end

