//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, PBMutableArray;

@interface QueryRule_Metadata : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) PBMutableArray *contextWordArray; // @dynamic contextWordArray;
@property(nonatomic) _Bool hasContextWordArray; // @dynamic hasContextWordArray;
@property(nonatomic) _Bool hasSquery; // @dynamic hasSquery;
@property(nonatomic) _Bool hasTermArray; // @dynamic hasTermArray;
@property(retain, nonatomic) NSString *squery; // @dynamic squery;
@property(retain, nonatomic) PBMutableArray *termArray; // @dynamic termArray;

@end

