//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class Conv2QueryInitialization, NSString;

@interface QueryPredictionEvent : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) Conv2QueryInitialization *conv2QueryInit; // @dynamic conv2QueryInit;
@property(nonatomic) _Bool hasConv2QueryInit; // @dynamic hasConv2QueryInit;
@property(nonatomic) _Bool hasHasSearchResultInteraction; // @dynamic hasHasSearchResultInteraction;
@property(nonatomic) _Bool hasQuery; // @dynamic hasQuery;
@property(nonatomic) _Bool hasQueryIndex; // @dynamic hasQueryIndex;
@property(nonatomic) _Bool hasQueryPredictionTrigger; // @dynamic hasQueryPredictionTrigger;
@property(nonatomic) _Bool hasQueryRule; // @dynamic hasQueryRule;
@property(nonatomic) _Bool hasQuerySelected; // @dynamic hasQuerySelected;
@property(nonatomic) _Bool hasQuerySuggested; // @dynamic hasQuerySuggested;
@property(nonatomic) _Bool hasSearchResultInteraction; // @dynamic hasSearchResultInteraction;
@property(retain, nonatomic) NSString *query; // @dynamic query;
@property(nonatomic) int queryIndex; // @dynamic queryIndex;
@property(nonatomic) int queryPredictionTrigger; // @dynamic queryPredictionTrigger;
@property(retain, nonatomic) NSString *queryRule; // @dynamic queryRule;
@property(nonatomic) _Bool querySelected; // @dynamic querySelected;
@property(nonatomic) _Bool querySuggested; // @dynamic querySuggested;

@end

