//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, RichSnippetReviewSource;

@interface RichSnippetReview : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSource; // @dynamic hasSource;
@property(copy, nonatomic) NSString *ratingText; // @dynamic ratingText;
@property(retain, nonatomic) RichSnippetReviewSource *source; // @dynamic source;
@property(nonatomic) float starRating; // @dynamic starRating;
@property(copy, nonatomic) NSString *voteOrReviewCountMessage; // @dynamic voteOrReviewCountMessage;

@end

