//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBDoubleValue;

@interface ScaleHint : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPreferredAspectRatio; // @dynamic hasPreferredAspectRatio;
@property(retain, nonatomic) GPBDoubleValue *preferredAspectRatio; // @dynamic preferredAspectRatio;

@end

