//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class LocalizedEntityNames, ScheduleResult_TextToSpeech_EventIndex;

@interface ScheduleResult_TextToSpeech : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) LocalizedEntityNames *entity; // @dynamic entity;
@property(nonatomic) int focusedAnswer; // @dynamic focusedAnswer;
@property(nonatomic) _Bool hasEntity; // @dynamic hasEntity;
@property(nonatomic) _Bool hasFocusedAnswer; // @dynamic hasFocusedAnswer;
@property(nonatomic) _Bool hasInProgressMatch; // @dynamic hasInProgressMatch;
@property(nonatomic) _Bool hasLastMatch; // @dynamic hasLastMatch;
@property(nonatomic) _Bool hasNextMatch; // @dynamic hasNextMatch;
@property(retain, nonatomic) ScheduleResult_TextToSpeech_EventIndex *inProgressMatch; // @dynamic inProgressMatch;
@property(retain, nonatomic) ScheduleResult_TextToSpeech_EventIndex *lastMatch; // @dynamic lastMatch;
@property(retain, nonatomic) ScheduleResult_TextToSpeech_EventIndex *nextMatch; // @dynamic nextMatch;

@end

