//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPLink, LocalizedEntityNames, NSMutableArray, NSString;

@interface ScheduleResult_ScheduleForPeriod : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *date; // @dynamic date;
@property(nonatomic) _Bool hasDate; // @dynamic hasDate;
@property(nonatomic) _Bool hasPeriodEntity; // @dynamic hasPeriodEntity;
@property(nonatomic) _Bool hasPeriodOrdinal; // @dynamic hasPeriodOrdinal;
@property(nonatomic) _Bool hasPeriodType; // @dynamic hasPeriodType;
@property(nonatomic) _Bool hasTitle; // @dynamic hasTitle;
@property(retain, nonatomic) LocalizedEntityNames *periodEntity; // @dynamic periodEntity;
@property(nonatomic) int periodOrdinal; // @dynamic periodOrdinal;
@property(nonatomic) int periodType; // @dynamic periodType;
@property(retain, nonatomic) NSMutableArray *scheduleDataArray; // @dynamic scheduleDataArray;
@property(readonly, nonatomic) unsigned long long scheduleDataArray_Count; // @dynamic scheduleDataArray_Count;
@property(retain, nonatomic) GWPLink *title; // @dynamic title;

@end

