//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface SearchResultInteraction : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasResultIndex; // @dynamic hasResultIndex;
@property(nonatomic) _Bool hasSearchCard; // @dynamic hasSearchCard;
@property(nonatomic) _Bool hasSearchCardUserAction; // @dynamic hasSearchCardUserAction;
@property(nonatomic) int resultIndex; // @dynamic resultIndex;
@property(nonatomic) int searchCard; // @dynamic searchCard;
@property(nonatomic) int searchCardUserAction; // @dynamic searchCardUserAction;

@end

