//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class SearchResultInteraction;

@interface SearchEvent : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLocationPermissionResult; // @dynamic hasLocationPermissionResult;
@property(nonatomic) _Bool hasNetworkStatus; // @dynamic hasNetworkStatus;
@property(nonatomic) _Bool hasRateGboardInteraction; // @dynamic hasRateGboardInteraction;
@property(nonatomic) _Bool hasSearchRequestTimedOut; // @dynamic hasSearchRequestTimedOut;
@property(nonatomic) _Bool hasSearchResultInteraction; // @dynamic hasSearchResultInteraction;
@property(nonatomic) _Bool hasSearchTab; // @dynamic hasSearchTab;
@property(nonatomic) _Bool hasSearchUserAction; // @dynamic hasSearchUserAction;
@property(nonatomic) int locationPermissionResult; // @dynamic locationPermissionResult;
@property(nonatomic) int networkStatus; // @dynamic networkStatus;
@property(nonatomic) int rateGboardInteraction; // @dynamic rateGboardInteraction;
@property(nonatomic) _Bool searchRequestTimedOut; // @dynamic searchRequestTimedOut;
@property(retain, nonatomic) SearchResultInteraction *searchResultInteraction; // @dynamic searchResultInteraction;
@property(nonatomic) int searchTab; // @dynamic searchTab;
@property(nonatomic) int searchUserAction; // @dynamic searchUserAction;

@end

