//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface SettingsEvent : PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasKeyboardSetting; // @dynamic hasKeyboardSetting;
@property(nonatomic) _Bool hasOpenedSettingPage; // @dynamic hasOpenedSettingPage;
@property(nonatomic) _Bool hasSearchSetting; // @dynamic hasSearchSetting;
@property(nonatomic) _Bool hasSettingStatus; // @dynamic hasSettingStatus;
@property(nonatomic) int keyboardSetting; // @dynamic keyboardSetting;
@property(nonatomic) int openedSettingPage; // @dynamic openedSettingPage;
@property(nonatomic) int searchSetting; // @dynamic searchSetting;
@property(nonatomic) int settingStatus; // @dynamic settingStatus;

@end

