//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class EntityColorsCollection, EntityImagesCollection, LocalizedEntityNamesCollection, NSMutableArray;

@interface SportsResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *bracketsArray; // @dynamic bracketsArray;
@property(readonly, nonatomic) unsigned long long bracketsArray_Count; // @dynamic bracketsArray_Count;
@property(retain, nonatomic) EntityColorsCollection *colors; // @dynamic colors;
@property(retain, nonatomic) NSMutableArray *detailedMatchArray; // @dynamic detailedMatchArray;
@property(readonly, nonatomic) unsigned long long detailedMatchArray_Count; // @dynamic detailedMatchArray_Count;
@property(nonatomic) _Bool hasColors; // @dynamic hasColors;
@property(nonatomic) _Bool hasImages; // @dynamic hasImages;
@property(nonatomic) _Bool hasNames; // @dynamic hasNames;
@property(nonatomic) _Bool hasResponseType; // @dynamic hasResponseType;
@property(retain, nonatomic) EntityImagesCollection *images; // @dynamic images;
@property(retain, nonatomic) NSMutableArray *leadersArray; // @dynamic leadersArray;
@property(readonly, nonatomic) unsigned long long leadersArray_Count; // @dynamic leadersArray_Count;
@property(retain, nonatomic) NSMutableArray *leagueMembersArray; // @dynamic leagueMembersArray;
@property(readonly, nonatomic) unsigned long long leagueMembersArray_Count; // @dynamic leagueMembersArray_Count;
@property(retain, nonatomic) NSMutableArray *leaguesArray; // @dynamic leaguesArray;
@property(readonly, nonatomic) unsigned long long leaguesArray_Count; // @dynamic leaguesArray_Count;
@property(retain, nonatomic) LocalizedEntityNamesCollection *names; // @dynamic names;
@property(retain, nonatomic) NSMutableArray *playerStatsArray; // @dynamic playerStatsArray;
@property(readonly, nonatomic) unsigned long long playerStatsArray_Count; // @dynamic playerStatsArray_Count;
@property(nonatomic) int responseType; // @dynamic responseType;
@property(retain, nonatomic) NSMutableArray *rosterArray; // @dynamic rosterArray;
@property(readonly, nonatomic) unsigned long long rosterArray_Count; // @dynamic rosterArray_Count;
@property(retain, nonatomic) NSMutableArray *scheduleArray; // @dynamic scheduleArray;
@property(readonly, nonatomic) unsigned long long scheduleArray_Count; // @dynamic scheduleArray_Count;
@property(retain, nonatomic) NSMutableArray *standingsArray; // @dynamic standingsArray;
@property(readonly, nonatomic) unsigned long long standingsArray_Count; // @dynamic standingsArray_Count;

@end

