//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Event, GPBEnumArray, GWPImage, GWPLink, LocalizedEntityNames, NSMutableArray, NSString;

@interface StandingsResult_GroupedStandings_StandingsTable_StandingsEntry : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *clinchArray; // @dynamic clinchArray;
@property(readonly, nonatomic) unsigned long long clinchArray_Count; // @dynamic clinchArray_Count;
@property(copy, nonatomic) NSString *color; // @dynamic color;
@property(retain, nonatomic) GPBEnumArray *eliminationArray; // @dynamic eliminationArray;
@property(readonly, nonatomic) unsigned long long eliminationArray_Count; // @dynamic eliminationArray_Count;
@property(retain, nonatomic) LocalizedEntityNames *entity; // @dynamic entity;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) _Bool hasEntity; // @dynamic hasEntity;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasIsTied; // @dynamic hasIsTied;
@property(nonatomic) _Bool hasLastEvent; // @dynamic hasLastEvent;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(nonatomic) _Bool hasName; // @dynamic hasName;
@property(nonatomic) _Bool hasPosition; // @dynamic hasPosition;
@property(nonatomic) _Bool hasPositionConference; // @dynamic hasPositionConference;
@property(nonatomic) _Bool hasPositionLeague; // @dynamic hasPositionLeague;
@property(retain, nonatomic) GWPImage *image; // @dynamic image;
@property(nonatomic) _Bool isTied; // @dynamic isTied;
@property(retain, nonatomic) Event *lastEvent; // @dynamic lastEvent;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;
@property(retain, nonatomic) GWPLink *name; // @dynamic name;
@property(nonatomic) int position; // @dynamic position;
@property(nonatomic) int positionConference; // @dynamic positionConference;
@property(nonatomic) int positionLeague; // @dynamic positionLeague;
@property(retain, nonatomic) NSMutableArray *statisticArray; // @dynamic statisticArray;
@property(readonly, nonatomic) unsigned long long statisticArray_Count; // @dynamic statisticArray_Count;

@end

