//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface StandingsResult_GroupedStandings_StandingsTable_Allocation : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasQualifyThrough; // @dynamic hasQualifyThrough;
@property(nonatomic) _Bool hasTarget; // @dynamic hasTarget;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(nonatomic) int qualifyThrough; // @dynamic qualifyThrough;
@property(nonatomic) int target; // @dynamic target;
@property(nonatomic) int type; // @dynamic type;

@end

