//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class Metadata, StandingsResult_GroupedStandings, StandingsResult_IndexList, StandingsResult_TextToSpeech, SubRequestIdentifier;

@interface StandingsResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) StandingsResult_GroupedStandings *groupedStandings; // @dynamic groupedStandings;
@property(nonatomic) _Bool hasGroupedStandings; // @dynamic hasGroupedStandings;
@property(nonatomic) _Bool hasIdentifier; // @dynamic hasIdentifier;
@property(nonatomic) _Bool hasIsSkiViking; // @dynamic hasIsSkiViking;
@property(nonatomic) _Bool hasMetadata; // @dynamic hasMetadata;
@property(nonatomic) _Bool hasSelectedEntityIndices; // @dynamic hasSelectedEntityIndices;
@property(nonatomic) _Bool hasTextToSpeech; // @dynamic hasTextToSpeech;
@property(retain, nonatomic) SubRequestIdentifier *identifier; // @dynamic identifier;
@property(nonatomic) _Bool isSkiViking; // @dynamic isSkiViking;
@property(retain, nonatomic) Metadata *metadata; // @dynamic metadata;
@property(retain, nonatomic) StandingsResult_IndexList *selectedEntityIndices; // @dynamic selectedEntityIndices;
@property(retain, nonatomic) StandingsResult_TextToSpeech *textToSpeech; // @dynamic textToSpeech;

@end

