//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface StatisticProperty_DisplayFormat : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *formatPattern; // @dynamic formatPattern;
@property(nonatomic) _Bool hasFormatPattern; // @dynamic hasFormatPattern;
@property(retain, nonatomic) NSMutableArray *valueInformationArray; // @dynamic valueInformationArray;
@property(readonly, nonatomic) unsigned long long valueInformationArray_Count; // @dynamic valueInformationArray_Count;

@end

