//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@interface StructuredMetaline_ReviewData_Rating : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double bestRating; // @dynamic bestRating;
@property(nonatomic) _Bool hasBestRating; // @dynamic hasBestRating;
@property(nonatomic) _Bool hasRating; // @dynamic hasRating;
@property(nonatomic) _Bool hasReviewStars; // @dynamic hasReviewStars;
@property(nonatomic) _Bool hasWorstRating; // @dynamic hasWorstRating;
@property(nonatomic) double rating; // @dynamic rating;
@property(nonatomic) double reviewStars; // @dynamic reviewStars;
@property(nonatomic) double worstRating; // @dynamic worstRating;

@end

