//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPB2Date, NSString, StructuredMetaline_ReviewData_Rating;

@interface StructuredMetaline_ReviewData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasPhoneNumber; // @dynamic hasPhoneNumber;
@property(nonatomic) _Bool hasPriceRange; // @dynamic hasPriceRange;
@property(nonatomic) _Bool hasRating; // @dynamic hasRating;
@property(nonatomic) _Bool hasReviewDate; // @dynamic hasReviewDate;
@property(nonatomic) _Bool hasReviewer; // @dynamic hasReviewer;
@property(nonatomic) int numReviews; // @dynamic numReviews;
@property(nonatomic) int numVotes; // @dynamic numVotes;
@property(copy, nonatomic) NSString *phoneNumber; // @dynamic phoneNumber;
@property(copy, nonatomic) NSString *priceRange; // @dynamic priceRange;
@property(retain, nonatomic) StructuredMetaline_ReviewData_Rating *rating; // @dynamic rating;
@property(retain, nonatomic) GPB2Date *reviewDate; // @dynamic reviewDate;
@property(copy, nonatomic) NSString *reviewer; // @dynamic reviewer;
@property(readonly, nonatomic) int votesOrReviewsOneOfCase; // @dynamic votesOrReviewsOneOfCase;

@end

