//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, StructuredMetaline_RecipeData_CookTime;

@interface StructuredMetaline_RecipeData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *calories; // @dynamic calories;
@property(retain, nonatomic) StructuredMetaline_RecipeData_CookTime *cookTime; // @dynamic cookTime;
@property(nonatomic) _Bool hasCalories; // @dynamic hasCalories;
@property(nonatomic) _Bool hasCookTime; // @dynamic hasCookTime;
@property(nonatomic) _Bool hasNumSteps; // @dynamic hasNumSteps;
@property(nonatomic) int numSteps; // @dynamic numSteps;

@end

