//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray;

@interface StructuredMetaline_ApplicationData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int category; // @dynamic category;
@property(nonatomic) _Bool hasCategory; // @dynamic hasCategory;
@property(retain, nonatomic) NSMutableArray *supportedPlatformsArray; // @dynamic supportedPlatformsArray;
@property(readonly, nonatomic) unsigned long long supportedPlatformsArray_Count; // @dynamic supportedPlatformsArray_Count;

@end

