//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class TextStyle;

@interface StyledTextSpan : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int finishIndex; // @dynamic finishIndex;
@property(nonatomic) _Bool hasStyle; // @dynamic hasStyle;
@property(nonatomic) int startIndex; // @dynamic startIndex;
@property(retain, nonatomic) TextStyle *style; // @dynamic style;

@end

