//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class DawnDuskTimes, SunriseSunsetLocation, SunriseSunsetTimes;

@interface SunriseSunsetResult : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) DawnDuskTimes *dawnDusk; // @dynamic dawnDusk;
@property(nonatomic) _Bool hasDawnDusk; // @dynamic hasDawnDusk;
@property(nonatomic) _Bool hasLocation; // @dynamic hasLocation;
@property(nonatomic) _Bool hasSunriseSunset; // @dynamic hasSunriseSunset;
@property(retain, nonatomic) SunriseSunsetLocation *location; // @dynamic location;
@property(retain, nonatomic) SunriseSunsetTimes *sunriseSunset; // @dynamic sunriseSunset;

@end

