//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, TitleGroup_DisplayHint;

@interface TitleGroup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) TitleGroup_DisplayHint *displayHint; // @dynamic displayHint;
@property(nonatomic) _Bool hasDisplayHint; // @dynamic hasDisplayHint;
@property(retain, nonatomic) NSMutableArray *titleLineArray; // @dynamic titleLineArray;
@property(readonly, nonatomic) unsigned long long titleLineArray_Count; // @dynamic titleLineArray_Count;

@end

