//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, NameConfig;

@interface TranslationConfig : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *description_p; // @dynamic description_p;
@property(nonatomic) _Bool hasDescription_p; // @dynamic hasDescription_p;
@property(nonatomic) _Bool hasNameConfig; // @dynamic hasNameConfig;
@property(retain, nonatomic) NSMutableArray *languageArray; // @dynamic languageArray;
@property(readonly, nonatomic) unsigned long long languageArray_Count; // @dynamic languageArray_Count;
@property(retain, nonatomic) NSMutableArray *leagueArray; // @dynamic leagueArray;
@property(readonly, nonatomic) unsigned long long leagueArray_Count; // @dynamic leagueArray_Count;
@property(retain, nonatomic) NameConfig *nameConfig; // @dynamic nameConfig;

@end

