//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (Quantum)
+ (id)goo_interpolateFromColor:(id)arg1 toColor:(id)arg2 percent:(double)arg3;
- (double)goo_perceivedLuminance;
- (_Bool)goo_requiresLightContent;
@end

