//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (GOOTypography)
- (_Bool)validateText:(id)arg1 font:(struct __CTFont *)arg2;
- (_Bool)goo_fallbackToSystemFontIfNeeded;
@end

