//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class AttributionRequirement;

@interface UsagePolicy : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) AttributionRequirement *attributionRequirement; // @dynamic attributionRequirement;
@property(nonatomic) _Bool hasAttributionRequirement; // @dynamic hasAttributionRequirement;

@end

