//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface VisualSportsTableElement_VisualSportsTableCol : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int columnType; // @dynamic columnType;
@property(nonatomic) int displayPriority; // @dynamic displayPriority;
@property(nonatomic) _Bool hasColumnType; // @dynamic hasColumnType;
@property(nonatomic) _Bool hasDisplayPriority; // @dynamic hasDisplayPriority;
@property(nonatomic) _Bool hasHeader; // @dynamic hasHeader;
@property(nonatomic) _Bool hasIsHighlighted; // @dynamic hasIsHighlighted;
@property(nonatomic) _Bool hasTooltip; // @dynamic hasTooltip;
@property(nonatomic) _Bool hasWidth; // @dynamic hasWidth;
@property(copy, nonatomic) NSString *header; // @dynamic header;
@property(nonatomic) _Bool isHighlighted; // @dynamic isHighlighted;
@property(copy, nonatomic) NSString *tooltip; // @dynamic tooltip;
@property(nonatomic) double width; // @dynamic width;

@end

