//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPImage, GWPLink, NSMutableArray, NSString;

@interface VisualSportsTableElement_TableEntryLabel : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *color; // @dynamic color;
@property(retain, nonatomic) NSMutableArray *complexLabelPartArray; // @dynamic complexLabelPartArray;
@property(readonly, nonatomic) unsigned long long complexLabelPartArray_Count; // @dynamic complexLabelPartArray_Count;
@property(nonatomic) _Bool hasColor; // @dynamic hasColor;
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasMatchSchedule; // @dynamic hasMatchSchedule;
@property(nonatomic) _Bool hasTeamMid; // @dynamic hasTeamMid;
@property(nonatomic) _Bool hasTeamName; // @dynamic hasTeamName;
@property(nonatomic) _Bool hasYear; // @dynamic hasYear;
@property(retain, nonatomic) GWPImage *image; // @dynamic image;
@property(copy, nonatomic) NSString *matchSchedule; // @dynamic matchSchedule;
@property(copy, nonatomic) NSString *teamMid; // @dynamic teamMid;
@property(retain, nonatomic) GWPLink *teamName; // @dynamic teamName;
@property(copy, nonatomic) NSString *year; // @dynamic year;

@end

