//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface VisualSportsTableElement_VisualSportsTableRow : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *entryLabelArray; // @dynamic entryLabelArray;
@property(readonly, nonatomic) unsigned long long entryLabelArray_Count; // @dynamic entryLabelArray_Count;
@property(nonatomic) _Bool hasIsFooterRow; // @dynamic hasIsFooterRow;
@property(nonatomic) _Bool hasIsQualifying; // @dynamic hasIsQualifying;
@property(nonatomic) _Bool hasIsRelegating; // @dynamic hasIsRelegating;
@property(nonatomic) _Bool hasIsSelected; // @dynamic hasIsSelected;
@property(nonatomic) _Bool hasIsShown; // @dynamic hasIsShown;
@property(nonatomic) _Bool hasIsVisibleOnlyInCollapsedMode; // @dynamic hasIsVisibleOnlyInCollapsedMode;
@property(nonatomic) _Bool hasNumberedRanking; // @dynamic hasNumberedRanking;
@property(nonatomic) _Bool isFooterRow; // @dynamic isFooterRow;
@property(nonatomic) _Bool isQualifying; // @dynamic isQualifying;
@property(nonatomic) _Bool isRelegating; // @dynamic isRelegating;
@property(nonatomic) _Bool isSelected; // @dynamic isSelected;
@property(nonatomic) _Bool isShown; // @dynamic isShown;
@property(nonatomic) _Bool isVisibleOnlyInCollapsedMode; // @dynamic isVisibleOnlyInCollapsedMode;
@property(copy, nonatomic) NSString *numberedRanking; // @dynamic numberedRanking;
@property(retain, nonatomic) NSMutableArray *statisticsArray; // @dynamic statisticsArray;
@property(readonly, nonatomic) unsigned long long statisticsArray_Count; // @dynamic statisticsArray_Count;

@end

