//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32Array, NSMutableArray, NSString;

@interface VisualSportsEntity : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool abbreviateTeamNameInStandings; // @dynamic abbreviateTeamNameInStandings;
@property(retain, nonatomic) NSMutableArray *customLabelHeaderArray; // @dynamic customLabelHeaderArray;
@property(readonly, nonatomic) unsigned long long customLabelHeaderArray_Count; // @dynamic customLabelHeaderArray_Count;
@property(retain, nonatomic) GPBInt32Array *customLabelSizeArray; // @dynamic customLabelSizeArray;
@property(readonly, nonatomic) unsigned long long customLabelSizeArray_Count; // @dynamic customLabelSizeArray_Count;
@property(nonatomic) int customLogoHeight; // @dynamic customLogoHeight;
@property(nonatomic) int customLogoWidth; // @dynamic customLogoWidth;
@property(nonatomic) _Bool displayIcons; // @dynamic displayIcons;
@property(nonatomic) _Bool displayIndexColumn; // @dynamic displayIndexColumn;
@property(nonatomic) _Bool forceLeagueNameAboveTeamColumn; // @dynamic forceLeagueNameAboveTeamColumn;
@property(nonatomic) _Bool hasAbbreviateTeamNameInStandings; // @dynamic hasAbbreviateTeamNameInStandings;
@property(nonatomic) _Bool hasCustomLogoHeight; // @dynamic hasCustomLogoHeight;
@property(nonatomic) _Bool hasCustomLogoWidth; // @dynamic hasCustomLogoWidth;
@property(nonatomic) _Bool hasDisplayIcons; // @dynamic hasDisplayIcons;
@property(nonatomic) _Bool hasDisplayIndexColumn; // @dynamic hasDisplayIndexColumn;
@property(nonatomic) _Bool hasForceLeagueNameAboveTeamColumn; // @dynamic hasForceLeagueNameAboveTeamColumn;
@property(nonatomic) _Bool hasMid; // @dynamic hasMid;
@property(nonatomic) _Bool hasShowAffiliationNames; // @dynamic hasShowAffiliationNames;
@property(nonatomic) _Bool hasShowLeagueNameForTeamStandings; // @dynamic hasShowLeagueNameForTeamStandings;
@property(nonatomic) _Bool hasShowOnlyTeamTable; // @dynamic hasShowOnlyTeamTable;
@property(nonatomic) _Bool hasShowStandingsInTabs; // @dynamic hasShowStandingsInTabs;
@property(nonatomic) _Bool hasShowStandingsTableEntityHeaderAboveTable; // @dynamic hasShowStandingsTableEntityHeaderAboveTable;
@property(nonatomic) _Bool hasShowVideoIfAvailable; // @dynamic hasShowVideoIfAvailable;
@property(nonatomic) _Bool hasShowVideoThumbnailForAllGames; // @dynamic hasShowVideoThumbnailForAllGames;
@property(copy, nonatomic) NSString *mid; // @dynamic mid;
@property(nonatomic) _Bool showAffiliationNames; // @dynamic showAffiliationNames;
@property(nonatomic) _Bool showLeagueNameForTeamStandings; // @dynamic showLeagueNameForTeamStandings;
@property(nonatomic) _Bool showOnlyTeamTable; // @dynamic showOnlyTeamTable;
@property(nonatomic) _Bool showStandingsInTabs; // @dynamic showStandingsInTabs;
@property(nonatomic) _Bool showStandingsTableEntityHeaderAboveTable; // @dynamic showStandingsTableEntityHeaderAboveTable;
@property(nonatomic) _Bool showVideoIfAvailable; // @dynamic showVideoIfAvailable;
@property(nonatomic) _Bool showVideoThumbnailForAllGames; // @dynamic showVideoThumbnailForAllGames;

@end

