//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class GWPImage, NSString;

@interface VisualSportsTableElement_ComplexLabelPart : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasIsCenterAligned; // @dynamic hasIsCenterAligned;
@property(nonatomic) _Bool hasOnlyShowInBigDisplay; // @dynamic hasOnlyShowInBigDisplay;
@property(nonatomic) _Bool hasOnlyShowInSmallDisplay; // @dynamic hasOnlyShowInSmallDisplay;
@property(nonatomic) _Bool hasShowEntityImage; // @dynamic hasShowEntityImage;
@property(nonatomic) _Bool hasSize; // @dynamic hasSize;
@property(nonatomic) _Bool hasText; // @dynamic hasText;
@property(retain, nonatomic) GWPImage *image; // @dynamic image;
@property(nonatomic) _Bool isCenterAligned; // @dynamic isCenterAligned;
@property(nonatomic) _Bool onlyShowInBigDisplay; // @dynamic onlyShowInBigDisplay;
@property(nonatomic) _Bool onlyShowInSmallDisplay; // @dynamic onlyShowInSmallDisplay;
@property(nonatomic) _Bool showEntityImage; // @dynamic showEntityImage;
@property(nonatomic) int size; // @dynamic size;
@property(copy, nonatomic) NSString *text; // @dynamic text;

@end

