//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class WeatherCondition, WindCondition;

@interface WeatherState : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) double chanceOfPrecipitation; // @dynamic chanceOfPrecipitation;
@property(retain, nonatomic) WeatherCondition *condition; // @dynamic condition;
@property(nonatomic) double feelsLikeTempF; // @dynamic feelsLikeTempF;
@property(nonatomic) _Bool hasChanceOfPrecipitation; // @dynamic hasChanceOfPrecipitation;
@property(nonatomic) _Bool hasCondition; // @dynamic hasCondition;
@property(nonatomic) _Bool hasFeelsLikeTempF; // @dynamic hasFeelsLikeTempF;
@property(nonatomic) _Bool hasHumidity; // @dynamic hasHumidity;
@property(nonatomic) _Bool hasTempF; // @dynamic hasTempF;
@property(nonatomic) _Bool hasWind; // @dynamic hasWind;
@property(nonatomic) double humidity; // @dynamic humidity;
@property(nonatomic) double tempF; // @dynamic tempF;
@property(retain, nonatomic) WindCondition *wind; // @dynamic wind;

@end

