//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WeatherLocation : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *city; // @dynamic city;
@property(copy, nonatomic) NSString *formattedAddress; // @dynamic formattedAddress;
@property(nonatomic) _Bool hasCity; // @dynamic hasCity;
@property(nonatomic) _Bool hasFormattedAddress; // @dynamic hasFormattedAddress;
@property(nonatomic) _Bool hasTimezone; // @dynamic hasTimezone;
@property(copy, nonatomic) NSString *timezone; // @dynamic timezone;

@end

