//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, WPOFDPerPlatformImages;

@interface WPOFDUseOverTime : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasImage; // @dynamic hasImage;
@property(nonatomic) _Bool hasTerm; // @dynamic hasTerm;
@property(retain, nonatomic) WPOFDPerPlatformImages *image; // @dynamic image;
@property(copy, nonatomic) NSString *term; // @dynamic term;

@end

