//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface WPOFDNymGroup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasRegister_p; // @dynamic hasRegister_p;
@property(retain, nonatomic) NSMutableArray *nymsArray; // @dynamic nymsArray;
@property(readonly, nonatomic) unsigned long long nymsArray_Count; // @dynamic nymsArray_Count;
@property(copy, nonatomic) NSString *register_p; // @dynamic register_p;

@end

