//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WPOFDWebDefinition : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *definition; // @dynamic definition;
@property(nonatomic) _Bool hasDefinition; // @dynamic hasDefinition;
@property(nonatomic) _Bool hasSourceURL; // @dynamic hasSourceURL;
@property(copy, nonatomic) NSString *sourceURL; // @dynamic sourceURL;

@end

