//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, WPOFDEtymology, WPOFDLabelSet, WPOFDNote;

@interface WPOFDEntry : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool containsWordRelevantToQuery; // @dynamic containsWordRelevantToQuery;
@property(retain, nonatomic) NSMutableArray *crossReferencesArray; // @dynamic crossReferencesArray;
@property(readonly, nonatomic) unsigned long long crossReferencesArray_Count; // @dynamic crossReferencesArray_Count;
@property(nonatomic) float definitionQuality; // @dynamic definitionQuality;
@property(retain, nonatomic) NSMutableArray *derivativesArray; // @dynamic derivativesArray;
@property(readonly, nonatomic) unsigned long long derivativesArray_Count; // @dynamic derivativesArray_Count;
@property(copy, nonatomic) NSString *displayedHomographIndex; // @dynamic displayedHomographIndex;
@property(nonatomic) int entrySeqNo; // @dynamic entrySeqNo;
@property(retain, nonatomic) WPOFDEtymology *etymology; // @dynamic etymology;
@property(nonatomic) _Bool hasContainsWordRelevantToQuery; // @dynamic hasContainsWordRelevantToQuery;
@property(nonatomic) _Bool hasDefinitionQuality; // @dynamic hasDefinitionQuality;
@property(nonatomic) _Bool hasDisplayedHomographIndex; // @dynamic hasDisplayedHomographIndex;
@property(nonatomic) _Bool hasEntrySeqNo; // @dynamic hasEntrySeqNo;
@property(nonatomic) _Bool hasEtymology; // @dynamic hasEtymology;
@property(nonatomic) _Bool hasHeadword; // @dynamic hasHeadword;
@property(nonatomic) _Bool hasHeadwordMatchesUserQuery; // @dynamic hasHeadwordMatchesUserQuery;
@property(nonatomic) _Bool hasHomographIndex; // @dynamic hasHomographIndex;
@property(nonatomic) _Bool hasLabelSet; // @dynamic hasLabelSet;
@property(nonatomic) _Bool hasLocale; // @dynamic hasLocale;
@property(nonatomic) _Bool hasMatchesUserIntent; // @dynamic hasMatchesUserIntent;
@property(nonatomic) _Bool hasNote; // @dynamic hasNote;
@property(nonatomic) _Bool hasReferenceId; // @dynamic hasReferenceId;
@property(nonatomic) _Bool hasSyllabifiedHeadword; // @dynamic hasSyllabifiedHeadword;
@property(nonatomic) _Bool hasTerm; // @dynamic hasTerm;
@property(nonatomic) _Bool hasUserIntent; // @dynamic hasUserIntent;
@property(nonatomic) _Bool hasVariantDescription; // @dynamic hasVariantDescription;
@property(copy, nonatomic) NSString *headword; // @dynamic headword;
@property(nonatomic) _Bool headwordMatchesUserQuery; // @dynamic headwordMatchesUserQuery;
@property(retain, nonatomic) NSMutableArray *headwordVariantsArray; // @dynamic headwordVariantsArray;
@property(readonly, nonatomic) unsigned long long headwordVariantsArray_Count; // @dynamic headwordVariantsArray_Count;
@property(nonatomic) int homographIndex; // @dynamic homographIndex;
@property(retain, nonatomic) NSMutableArray *indexingKeysArray; // @dynamic indexingKeysArray;
@property(readonly, nonatomic) unsigned long long indexingKeysArray_Count; // @dynamic indexingKeysArray_Count;
@property(retain, nonatomic) WPOFDLabelSet *labelSet; // @dynamic labelSet;
@property(copy, nonatomic) NSString *locale; // @dynamic locale;
@property(nonatomic) _Bool matchesUserIntent; // @dynamic matchesUserIntent;
@property(retain, nonatomic) WPOFDNote *note; // @dynamic note;
@property(retain, nonatomic) NSMutableArray *partsOfSpeechArray; // @dynamic partsOfSpeechArray;
@property(readonly, nonatomic) unsigned long long partsOfSpeechArray_Count; // @dynamic partsOfSpeechArray_Count;
@property(retain, nonatomic) NSMutableArray *phoneticsArray; // @dynamic phoneticsArray;
@property(readonly, nonatomic) unsigned long long phoneticsArray_Count; // @dynamic phoneticsArray_Count;
@property(copy, nonatomic) NSString *referenceId; // @dynamic referenceId;
@property(retain, nonatomic) NSMutableArray *referencedTargetsArray; // @dynamic referencedTargetsArray;
@property(readonly, nonatomic) unsigned long long referencedTargetsArray_Count; // @dynamic referencedTargetsArray_Count;
@property(retain, nonatomic) NSMutableArray *senseFamiliesArray; // @dynamic senseFamiliesArray;
@property(readonly, nonatomic) unsigned long long senseFamiliesArray_Count; // @dynamic senseFamiliesArray_Count;
@property(retain, nonatomic) NSMutableArray *subentriesArray; // @dynamic subentriesArray;
@property(readonly, nonatomic) unsigned long long subentriesArray_Count; // @dynamic subentriesArray_Count;
@property(copy, nonatomic) NSString *syllabifiedHeadword; // @dynamic syllabifiedHeadword;
@property(copy, nonatomic) NSString *term; // @dynamic term;
@property(retain, nonatomic) NSMutableArray *thesaurusEntriesArray; // @dynamic thesaurusEntriesArray;
@property(readonly, nonatomic) unsigned long long thesaurusEntriesArray_Count; // @dynamic thesaurusEntriesArray_Count;
@property(nonatomic) int userIntent; // @dynamic userIntent;
@property(copy, nonatomic) NSString *variantDescription; // @dynamic variantDescription;
@property(retain, nonatomic) NSMutableArray *variantGroupArray; // @dynamic variantGroupArray;
@property(readonly, nonatomic) unsigned long long variantGroupArray_Count; // @dynamic variantGroupArray_Count;
@property(retain, nonatomic) NSMutableArray *variantMessagesArray; // @dynamic variantMessagesArray;
@property(readonly, nonatomic) unsigned long long variantMessagesArray_Count; // @dynamic variantMessagesArray_Count;
@property(retain, nonatomic) NSMutableArray *variantsArray; // @dynamic variantsArray;
@property(readonly, nonatomic) unsigned long long variantsArray_Count; // @dynamic variantsArray_Count;

@end

