//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface WPOFDVariantGroup : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *closingBracket; // @dynamic closingBracket;
@property(nonatomic) _Bool hasClosingBracket; // @dynamic hasClosingBracket;
@property(nonatomic) _Bool hasOpeningBracket; // @dynamic hasOpeningBracket;
@property(nonatomic) _Bool hasSeparator; // @dynamic hasSeparator;
@property(copy, nonatomic) NSString *openingBracket; // @dynamic openingBracket;
@property(copy, nonatomic) NSString *separator; // @dynamic separator;
@property(retain, nonatomic) NSMutableArray *variantsArray; // @dynamic variantsArray;
@property(readonly, nonatomic) unsigned long long variantsArray_Count; // @dynamic variantsArray_Count;

@end

