//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, WPOFDAnnotatedText, WPOFDPerPlatformImages;

@interface WPOFDEtymology : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *deprecatedEtymology; // @dynamic deprecatedEtymology;
@property(retain, nonatomic) WPOFDAnnotatedText *etymology; // @dynamic etymology;
@property(nonatomic) _Bool hasDeprecatedEtymology; // @dynamic hasDeprecatedEtymology;
@property(nonatomic) _Bool hasEtymology; // @dynamic hasEtymology;
@property(nonatomic) _Bool hasImages; // @dynamic hasImages;
@property(retain, nonatomic) WPOFDPerPlatformImages *images; // @dynamic images;

@end

