//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface WPOFDPhonetic : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *drEyeAudio; // @dynamic drEyeAudio;
@property(nonatomic) _Bool hasDrEyeAudio; // @dynamic hasDrEyeAudio;
@property(nonatomic) _Bool hasOxfordAudio; // @dynamic hasOxfordAudio;
@property(nonatomic) _Bool hasText; // @dynamic hasText;
@property(nonatomic) _Bool hasTtsAudio; // @dynamic hasTtsAudio;
@property(nonatomic) _Bool hasType; // @dynamic hasType;
@property(copy, nonatomic) NSString *oxfordAudio; // @dynamic oxfordAudio;
@property(copy, nonatomic) NSString *text; // @dynamic text;
@property(copy, nonatomic) NSString *ttsAudio; // @dynamic ttsAudio;
@property(copy, nonatomic) NSString *type; // @dynamic type;

@end

