//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString;

@interface WPOFDAnnotatedText : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *fragmentsArray; // @dynamic fragmentsArray;
@property(readonly, nonatomic) unsigned long long fragmentsArray_Count; // @dynamic fragmentsArray_Count;
@property(nonatomic) _Bool hasText; // @dynamic hasText;
@property(copy, nonatomic) NSString *text; // @dynamic text;

@end

