//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, WPOFDPerPlatformImages;

@interface WPOFDSynonymBigramsComparison : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *comparisonTermPhrasesArray; // @dynamic comparisonTermPhrasesArray;
@property(readonly, nonatomic) unsigned long long comparisonTermPhrasesArray_Count; // @dynamic comparisonTermPhrasesArray_Count;
@property(nonatomic) _Bool hasSynonymBigramComparisonImage; // @dynamic hasSynonymBigramComparisonImage;
@property(retain, nonatomic) NSMutableArray *queryTermPhrasesArray; // @dynamic queryTermPhrasesArray;
@property(readonly, nonatomic) unsigned long long queryTermPhrasesArray_Count; // @dynamic queryTermPhrasesArray_Count;
@property(retain, nonatomic) WPOFDPerPlatformImages *synonymBigramComparisonImage; // @dynamic synonymBigramComparisonImage;

@end

