//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, WPOFDLabelSet, WPOFDNote;

@interface WPOFDSenseFamily : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool containsAntonyms; // @dynamic containsAntonyms;
@property(nonatomic) _Bool containsSynonyms; // @dynamic containsSynonyms;
@property(retain, nonatomic) NSMutableArray *formsArray; // @dynamic formsArray;
@property(readonly, nonatomic) unsigned long long formsArray_Count; // @dynamic formsArray_Count;
@property(copy, nonatomic) NSString *formsDescription; // @dynamic formsDescription;
@property(copy, nonatomic) NSString *grammarData; // @dynamic grammarData;
@property(nonatomic) _Bool hasContainsAntonyms; // @dynamic hasContainsAntonyms;
@property(nonatomic) _Bool hasContainsSynonyms; // @dynamic hasContainsSynonyms;
@property(nonatomic) _Bool hasFormsDescription; // @dynamic hasFormsDescription;
@property(nonatomic) _Bool hasGrammarData; // @dynamic hasGrammarData;
@property(nonatomic) _Bool hasInflection; // @dynamic hasInflection;
@property(nonatomic) _Bool hasLabelSet; // @dynamic hasLabelSet;
@property(nonatomic) _Bool hasNote; // @dynamic hasNote;
@property(nonatomic) _Bool hasRelevantToQuery; // @dynamic hasRelevantToQuery;
@property(nonatomic) _Bool hasVariantDescription; // @dynamic hasVariantDescription;
@property(retain, nonatomic) NSMutableArray *indexingKeysArray; // @dynamic indexingKeysArray;
@property(readonly, nonatomic) unsigned long long indexingKeysArray_Count; // @dynamic indexingKeysArray_Count;
@property(copy, nonatomic) NSString *inflection; // @dynamic inflection;
@property(retain, nonatomic) WPOFDLabelSet *labelSet; // @dynamic labelSet;
@property(retain, nonatomic) NSMutableArray *morphUnitsArray; // @dynamic morphUnitsArray;
@property(readonly, nonatomic) unsigned long long morphUnitsArray_Count; // @dynamic morphUnitsArray_Count;
@property(retain, nonatomic) WPOFDNote *note; // @dynamic note;
@property(retain, nonatomic) NSMutableArray *partsOfSpeechArray; // @dynamic partsOfSpeechArray;
@property(readonly, nonatomic) unsigned long long partsOfSpeechArray_Count; // @dynamic partsOfSpeechArray_Count;
@property(retain, nonatomic) NSMutableArray *phoneticsArray; // @dynamic phoneticsArray;
@property(readonly, nonatomic) unsigned long long phoneticsArray_Count; // @dynamic phoneticsArray_Count;
@property(nonatomic) float relevantToQuery; // @dynamic relevantToQuery;
@property(retain, nonatomic) NSMutableArray *sensesArray; // @dynamic sensesArray;
@property(readonly, nonatomic) unsigned long long sensesArray_Count; // @dynamic sensesArray_Count;
@property(copy, nonatomic) NSString *variantDescription; // @dynamic variantDescription;
@property(retain, nonatomic) NSMutableArray *variantGroupArray; // @dynamic variantGroupArray;
@property(readonly, nonatomic) unsigned long long variantGroupArray_Count; // @dynamic variantGroupArray_Count;
@property(retain, nonatomic) NSMutableArray *variantMessagesArray; // @dynamic variantMessagesArray;
@property(readonly, nonatomic) unsigned long long variantMessagesArray_Count; // @dynamic variantMessagesArray_Count;
@property(retain, nonatomic) NSMutableArray *variantsArray; // @dynamic variantsArray;
@property(readonly, nonatomic) unsigned long long variantsArray_Count; // @dynamic variantsArray_Count;

@end

