//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, WPOFDImage;

@interface WPOFDPerPlatformImages : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *URL; // @dynamic URL;
@property(retain, nonatomic) WPOFDImage *desktop; // @dynamic desktop;
@property(nonatomic) _Bool hasDesktop; // @dynamic hasDesktop;
@property(nonatomic) _Bool hasMobile; // @dynamic hasMobile;
@property(nonatomic) _Bool hasTablet; // @dynamic hasTablet;
@property(nonatomic) _Bool hasURL; // @dynamic hasURL;
@property(retain, nonatomic) WPOFDImage *mobile; // @dynamic mobile;
@property(retain, nonatomic) WPOFDImage *tablet; // @dynamic tablet;

@end

